import {test,expect,type Page,type APIRequestContext} from '@playwright/test';
const api='http://127.0.0.1:5011';
interface Person{phone:string;password:string;organizationId:string;branchId:string;membershipId:string}
interface Fixture extends Person{people:Record<'employee'|'colleague'|'reviewer'|'inactive',Person>}
let fixture:Fixture,errors:string[];
test.beforeEach(async({page,request})=>{fixture=await(await request.post(api+'/__test/fixture',{data:{modules:['hr_plus'],hrFixture:true}})).json();errors=[];page.on('pageerror',e=>errors.push(e.name));});
test.afterEach(()=>expect(errors).toEqual([]));
async function login(page:Page,p:Person=fixture){expect((await page.request.post(api+'/__test/client-phase')).status()).toBe(200);await page.goto('/login');await page.getByLabel('Phone or email').fill(p.phone);await page.getByLabel('Password',{exact:true}).fill(p.password);await page.getByRole('button',{name:'Sign In to Ekavio'}).click();await expect(page).toHaveURL(/dashboard/);}
async function logout(page:Page){await page.getByRole('button',{name:'Sign out',exact:true}).click();await expect(page.getByLabel('Phone or email')).toBeVisible();}
async function headers(request:APIRequestContext,p:Person=fixture){const r=await request.post(api+'/api/auth/login',{data:{phone:p.phone,password:p.password}});expect(r.status()).toBe(200);return {authorization:'Bearer '+(await r.json()).accessToken,'x-tenant-id':p.organizationId,'x-branch-id':p.branchId};}
async function seed(request:APIRequestContext){const h=await headers(request);const type=await request.post(api+'/api/hr/types',{headers:h,data:{name:'QA Whole-day Leave',requiresReason:true,countNonWorking:true}});expect(type.status()).toBe(201);const template=await request.post(api+'/api/hr/templates',{headers:h,data:{name:'QA Morning Shift',startTime:'09:00',endTime:'17:00',overnight:false,breakMinutes:30}});expect(template.status()).toBe(201);return {h,type:(await type.json()).data,template:(await template.json()).data};}
async function command(request:APIRequestContext,h:Record<string,string>,path:string,data:unknown,status=200){const r=await request.post(api+'/api/hr/'+path,{headers:h,data});expect(r.status()).toBe(status);return (await r.json()).data;}
const date='2026-12-14',leaveDate='2026-12-15';
test('real UI calendar, holiday, template, scheduling, employee request, HR approval and immutable conflict',async({page,request})=>{
 await login(page);await page.goto('/hr');await expect(page.getByRole('heading',{name:'HR Plus',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Recorded Attendance (separate)'})).toHaveCount(0);
 await page.getByRole('button',{name:'Leave Types',exact:true}).click();await page.getByRole('button',{name:'Add leave type'}).click();let d=page.getByRole('dialog');await d.getByLabel('Name',{exact:true}).fill('QA Annual Leave');await d.getByLabel('Reason required').check();await d.getByLabel('Count non-working days').check();await d.getByRole('button',{name:'Save configuration'}).click();await expect(d).not.toBeVisible();
 await page.getByRole('button',{name:'Work Calendar',exact:true}).click();await page.getByRole('button',{name:'Configure working week'}).click();d=page.getByRole('dialog');await d.getByLabel('Name',{exact:true}).fill('QA Explicit week');await d.getByLabel('Saturday').check();await d.getByRole('button',{name:'Save configuration'}).click();await expect(d).not.toBeVisible();await page.getByLabel('Window starts').fill(date);await page.getByRole('button',{name:'Add calendar day'}).click();d=page.getByRole('dialog');await d.getByLabel('Name',{exact:true}).fill('QA Manual Holiday');await d.getByLabel('Calendar date').fill('2026-12-16');await d.getByRole('button',{name:'Save configuration'}).click();await expect(d).not.toBeVisible();await expect(page.getByText(/2026-12-16.*QA Manual Holiday/)).toBeVisible();
 await page.getByRole('button',{name:'Shift Templates',exact:true}).click();await page.getByRole('button',{name:'Add shift template'}).click();d=page.getByRole('dialog');await d.getByLabel('Name',{exact:true}).fill('QA Day Shift');await d.getByLabel('Local start time').fill('09:00');await d.getByLabel('Local end time').fill('17:00');await d.getByLabel('Planned break minutes').fill('30');await d.getByRole('button',{name:'Save configuration'}).click();await expect(d).not.toBeVisible();
 await page.getByRole('button',{name:'Shifts',exact:true}).click();await page.getByRole('button',{name:'Create draft schedule'}).click();d=page.getByRole('dialog');await d.getByLabel('Employee',{exact:true}).selectOption({label:'QA employee'});await d.getByLabel('Shift template').selectOption({label:'QA Day Shift (09:00–17:00)'});await d.getByLabel('Schedule starts on').fill(date);await d.getByRole('button',{name:'Create draft schedule'}).click();await expect(d).not.toBeVisible();await page.getByRole('button',{name:'Publish shift',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirm published'}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await expect(page.getByText(/Main.*2026-12-14.*published/)).toBeVisible();
 await logout(page);await login(page,fixture.people.employee);await page.goto('/hr');await page.getByLabel('Window starts').fill(date);await expect(page.getByRole('heading',{name:'My Schedule'})).toBeVisible();await expect(page.getByText(/Main.*2026-12-14.*published/)).toBeVisible();await expect(page.getByRole('button',{name:'Leave',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Request leave',exact:true}).click();d=page.getByRole('dialog');await d.getByLabel('Leave type',{exact:true}).selectOption({label:'QA Annual Leave'});await d.getByLabel('Leave starts').fill(leaveDate);await d.getByLabel('Leave ends').fill(leaveDate);await d.getByLabel('Reason (avoid unnecessary medical information)').fill('QA PRIVATE REASON sentinel');await d.getByRole('button',{name:'Review request'}).click();await d.getByRole('button',{name:'Confirm submission'}).click();await expect(d).not.toBeVisible();await expect(page.getByText(/counted whole-request days.*pending/)).toBeVisible();
 await logout(page);await login(page,fixture.people.reviewer);await page.goto('/hr');await page.getByLabel('Window starts').fill(date);await expect(page.getByText('Private request reason: QA PRIVATE REASON sentinel',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Approve leave',exact:true}).click();d=page.getByRole('dialog');await d.getByLabel('Reviewer note (private to authorized reviewers)').fill('QA PRIVATE NOTE sentinel');await d.getByRole('button',{name:'Confirm approved'}).click();await expect(d).not.toBeVisible();await expect(page.getByText(/counted whole-request days.*approved/)).toBeVisible();
 await logout(page);await login(page,fixture.people.employee);await page.goto('/hr');await page.getByLabel('Window starts').fill(date);await expect(page.getByText(/counted whole-request days.*approved/)).toBeVisible();await page.getByRole('button',{name:'View leave history'}).click();await expect(page.getByRole('dialog').getByText(/leave.approved/)).toBeVisible();await expect(page.getByText(/QA PRIVATE NOTE sentinel/)).toHaveCount(0);await page.getByRole('dialog').getByRole('button',{name:'Close modal'}).click();
 const h=await headers(request),ctx=(await(await request.get(api+'/api/hr/context',{headers:h,params:{from:date,to:leaveDate}})).json()).data;const r=await request.post(api+'/api/hr/shifts',{headers:h,data:{membershipId:fixture.people.employee.membershipId,templateId:ctx.templates[0].id,from:leaveDate,to:leaveDate,workingDaysOnly:false,idempotencyKey:crypto.randomUUID()}});expect(r.status()).toBe(409);
 const colleague=await headers(request,fixture.people.colleague);expect((await request.get(api+'/api/hr/leave',{headers:colleague,params:{from:date,to:leaveDate}})).status()).toBe(403);const own=await request.get(api+'/api/hr/me/leave',{headers:colleague,params:{from:date,to:leaveDate}});expect(JSON.stringify(await own.json())).not.toContain('sentinel');
});
test('HTTP live isolation, subject spoofing, readonly custom role and Attendance independence',async({page,request})=>{
 const s=await seed(request),none:Person=await(await request.post(api+'/__test/fixture',{data:{permissions:['hr_plus.read','hr_plus.manage','hr_plus.approve']}})).json(),nh=await headers(request,none),range={from:date,to:leaveDate};expect((await request.get(api+'/api/hr/context',{headers:nh,params:range})).status()).toBe(403);expect((await request.get(api+'/api/hr/context',{headers:{...s.h,'x-tenant-id':none.organizationId},params:range})).status()).toBe(403);expect((await request.get(api+'/api/hr/context',{headers:{...s.h,'x-branch-id':none.branchId},params:range})).status()).toBe(403);
 const readonly:Person=await(await request.post(api+'/__test/fixture',{data:{modules:['hr_plus'],permissions:['hr_plus.read']}})).json(),rh=await headers(request,readonly);expect((await request.post(api+'/api/hr/types',{headers:rh,data:{name:'Denied'}})).status()).toBe(403);await login(page,readonly);await page.goto('/hr');await expect(page.getByRole('button',{name:'Leave Types',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Shifts',exact:true})).toBeVisible();
 const employee=await headers(request,fixture.people.employee);expect((await request.post(api+'/api/hr/me/leave',{headers:employee,data:{leaveTypeId:s.type.id,startDate:date,endDate:date,reason:'QA',membershipId:fixture.people.colleague.membershipId,idempotencyKey:crypto.randomUUID()}})).status()).toBe(400);expect((await request.get(api+'/api/hr/me/schedule',{headers:employee,params:range})).status()).toBe(200);expect((await request.get(api+'/api/attendance',{headers:s.h,params:{date}})).status()).toBe(403);expect((await request.post(api+'/api/auth/login',{data:{phone:fixture.people.inactive.phone,password:fixture.people.inactive.password}})).status()).toBe(403);
 const attendance:Person=await(await request.post(api+'/__test/fixture',{data:{modules:['attendance']}})).json(),ah=await headers(request,attendance);expect((await request.get(api+'/api/attendance',{headers:ah,params:{date}})).status()).toBe(200);expect((await request.get(api+'/api/hr/context',{headers:ah,params:range})).status()).toBe(403);
});
test('four curated reports, safe CSV, widgets and notification attention omit private text',async({page,request})=>{
 const s=await seed(request),eh=await headers(request,fixture.people.employee),rh=await headers(request,fixture.people.reviewer);const leave=await command(request,eh,'me/leave',{leaveTypeId:s.type.id,startDate:date,endDate:date,reason:'QA PRIVATE sentinel',idempotencyKey:crypto.randomUUID()},201);await command(request,rh,'leave/'+leave.id+'/review',{status:'approved',expectedVersion:1,note:'QA PRIVATE note',idempotencyKey:crypto.randomUUID()});const shifts=await command(request,s.h,'shifts',{membershipId:fixture.people.employee.membershipId,templateId:s.template.id,from:leaveDate,to:leaveDate,workingDaysOnly:false,idempotencyKey:crypto.randomUUID()},201);await command(request,s.h,'shifts/'+shifts[0].id+'/status',{status:'published',expectedVersion:1,idempotencyKey:crypto.randomUUID()});
 await login(page);await page.goto('/reports');await page.getByRole('combobox',{name:'Report',exact:true}).selectOption('hr-leave');await page.getByLabel('From business date',{exact:true}).fill(date);await page.getByLabel('To business date',{exact:true}).fill(leaveDate);for(const key of ['hr-leave','hr-approved','hr-shifts','hr-coverage']){await page.getByRole('combobox',{name:'Report',exact:true}).selectOption(key);await page.getByLabel('From business date',{exact:true}).fill(date);await page.getByLabel('To business date',{exact:true}).fill(leaveDate);await expect(page.getByRole('cell',{name:key==='hr-coverage'?'Main':'QA employee',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Export CSV'})).toBeEnabled();const result=page.waitForResponse(r=>r.url().includes('/reports/'+key+'/export'));await page.getByRole('button',{name:'Export CSV'}).click();const response=await result;expect(response.status()).toBe(200);const csv=await response.text();expect(csv).not.toContain('PRIVATE');expect(csv).toContain(key==='hr-coverage'?'Main':'QA employee');}await page.goto('/dashboard');await expect(page.getByRole('heading',{name:'Pending leave requests',exact:true})).toBeVisible();await page.goto('/notifications');await expect(page.getByText(/QA PRIVATE/)).toHaveCount(0);
});
for(const width of [360,390,768,1440])for(const theme of ['light','dark','system'])test(`HR workspace ${width}px ${theme}`,async({page,request})=>{
 await seed(request);await page.setViewportSize({width,height:900});await login(page);await page.goto('/settings?section=appearance');await page.getByRole('radio',{name:new RegExp(theme,'i')}).click();await page.goto('/hr');await expect(page.getByRole('heading',{name:'HR Plus',exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.getByRole('button',{name:'Request leave',exact:true}).click();const d=page.getByRole('dialog');await d.getByLabel('Leave type',{exact:true}).selectOption({label:'QA Whole-day Leave'});await d.getByLabel('Leave starts').fill(date);await d.getByLabel('Leave ends').fill(leaveDate);await d.getByLabel('Reason (avoid unnecessary medical information)').fill('QA ordinary leave');await d.getByRole('button',{name:'Review request'}).click();await expect(d.getByRole('heading',{name:'Confirm leave request'})).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await d.getByRole('button',{name:'Close modal'}).click();await page.getByRole('button',{name:'Shifts',exact:true}).click();await page.getByRole('button',{name:'Create draft schedule'}).click();await expect(page.getByRole('dialog').getByLabel('Employee',{exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();if(width===390&&theme==='dark')await page.screenshot({path:'test-results/hr/hr-390-dark.png'});
});
