import { test,expect,type Page,type APIRequestContext } from '@playwright/test';
const api='http://127.0.0.1:5011';
interface Fixture{phone:string;password:string;organizationId:string;branchId:string}
let fixture:Fixture,errors:string[];
test.beforeEach(async({page,request})=>{fixture=await(await request.post(api+'/__test/fixture',{data:{modules:['crm']}})).json();errors=[];page.on('pageerror',e=>errors.push(e.name));});
test.afterEach(()=>expect(errors).toEqual([]));
async function reviewSave(page:Page,label:string){await page.getByRole('dialog').getByRole('button',{name:'Review',exact:true}).click();const review=page.getByRole('dialog'),title=await review.locator('h2[id]').innerText();await review.getByRole('button',{name:label,exact:true}).click();await expect(page.getByRole('dialog',{name:title,exact:true})).not.toBeVisible();}
async function login(page:Page,f=fixture){await page.goto('/login');await page.getByLabel('Phone or email').fill(f.phone);await page.getByLabel('Password',{exact:true}).fill(f.password);await page.getByRole('button',{name:'Sign In to Ekavio'}).click();await expect(page).toHaveURL(/dashboard/);}
async function headers(request:APIRequestContext,f=fixture){const r=await request.post(api+'/api/auth/login',{data:{phone:f.phone,password:f.password}});expect(r.status()).toBe(200);const d=await r.json();return {authorization:'Bearer '+d.accessToken,'x-tenant-id':f.organizationId,'x-branch-id':f.branchId};}
async function seed(request:APIRequestContext){const h=await headers(request);expect((await request.post(api+'/api/crm/stages/recommended',{headers:h,data:{}})).status()).toBe(201);const stages=(await(await request.get(api+'/api/crm/stages',{headers:h})).json()).data;return {h,stages};}
test('owner creates stages, typed lead, assignment, stage move and manual follow-up',async({page,request})=>{
 const h=await headers(request);
 expect((await request.post(api+'/api/forms/lead/definitions',{headers:h,data:{key:'interest',label:'Lead interest',help:'Plain bounded information',fieldType:'text',status:'active',required:true,searchable:true,filterable:true,reportable:true,defaultValue:null,options:[]}})).status()).toBe(200);
 await login(page);await expect(page.getByRole('heading',{name:'Active leads',exact:true})).toBeVisible();
 await page.goto('/crm');await expect(page.getByRole('heading',{name:'No leads yet'})).toBeVisible();await page.getByRole('button',{name:'Pipeline settings',exact:true}).click();await page.getByRole('button',{name:'Create recommended stages'}).click();await expect(page.getByRole('heading',{name:'Decision',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Create lead',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Create lead'});await dialog.getByLabel('Lead name',{exact:true}).fill('QA CRM enquiry');await dialog.getByLabel('Lead interest',{exact:false}).fill('Consultation');await expect(dialog.getByRole('combobox',{name:'Assigned staff',exact:true}).getByRole('option',{name:'QA owner',exact:true})).toHaveCount(1);await dialog.getByRole('combobox',{name:'Assigned staff',exact:true}).selectOption({label:'QA owner'});await reviewSave(page,'Save lead');await expect(dialog).not.toBeVisible();await page.getByRole('button',{name:'leads',exact:true}).click();
 await page.getByRole('button',{name:'View QA CRM enquiry',exact:true}).click();const detail=page.getByRole('dialog',{name:'Lead details'});await expect(detail.getByText('Consultation',{exact:true})).toBeVisible();await detail.getByLabel('Move stage').selectOption({label:'Contacted'});await expect(detail.getByText('Stage: Contacted',{exact:true})).toBeVisible();await detail.getByLabel('Add activity note').fill('Called manually');await detail.getByRole('button',{name:'Add note',exact:true}).click();await expect(detail.getByText('Called manually',{exact:true})).toBeVisible();
 await detail.getByRole('button',{name:'Add follow-up',exact:true}).click();const follow=page.getByRole('dialog',{name:'Add follow-up'});await follow.getByLabel('Follow-up subject').fill('QA call today');const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());await follow.getByLabel('Due date and time').fill(today+'T10:30');await reviewSave(page,'Save follow-up');await expect(follow).not.toBeVisible();await expect(detail.getByRole('heading',{name:'QA call today',exact:true})).toBeVisible();await detail.getByRole('button',{name:'Complete follow-up'}).click();await detail.getByRole('button',{name:'Confirm follow-up status'}).click();await expect(detail.getByText('Follow-up completed',{exact:false})).toBeVisible();await detail.getByRole('button',{name:'Close modal'}).click();
 await page.getByLabel('Search leads').fill('Consultation');await expect(page.getByRole('heading',{name:'QA CRM enquiry',exact:true})).toBeVisible();await page.getByLabel('Search leads').fill('No such lead');await expect(page.getByRole('heading',{name:'No matching leads'})).toBeVisible();
 await page.goto('/reports');await page.getByRole('combobox',{name:'Report',exact:true}).selectOption('crm-leads');await expect(page.getByRole('cell',{name:'QA CRM enquiry',exact:true})).toBeVisible();await page.getByText('Choose columns',{exact:true}).click();await page.getByRole('checkbox',{name:'Lead interest',exact:true}).check();await expect(page.getByRole('cell',{name:'Consultation',exact:true})).toBeVisible();const exported=page.waitForResponse(r=>r.url().includes('/reports/crm-leads/export'));await page.getByRole('button',{name:'Export CSV'}).click();expect((await exported).status()).toBe(200);await page.getByRole('combobox',{name:'Report',exact:true}).selectOption('crm-followups');await expect(page.getByRole('cell',{name:'QA call today',exact:true})).toBeVisible();const followExport=page.waitForResponse(r=>r.url().includes('/reports/crm-followups/export'));await page.getByRole('button',{name:'Export CSV'}).click();expect((await followExport).status()).toBe(200);await page.goto('/dashboard');await expect(page.getByRole('heading',{name:'Active leads',exact:true})).toBeVisible();
});
test('conversion requires Customer custom fields and opens permanent canonical Customer',async({page,request})=>{
 const {h,stages}=await seed(request);
 expect((await request.post(api+'/api/forms/customer/definitions',{headers:h,data:{key:'extra_contact',label:'Customer required information',help:'',fieldType:'text',status:'active',required:true,searchable:false,filterable:false,reportable:false,defaultValue:null,options:[]}})).status()).toBe(200);
 const r=await request.post(api+'/api/crm/leads',{headers:h,data:{name:'QA converted lead',pipelineStageId:stages[0].id}});expect(r.status()).toBe(201);const lead=(await r.json()).data;
 await login(page);await page.goto('/crm?lead='+lead.id);const detail=page.getByRole('dialog',{name:'Lead details'});await expect(detail.getByRole('heading',{name:'QA converted lead'})).toBeVisible();await detail.getByRole('button',{name:'Convert to Customer'}).click();const conversion=page.getByRole('dialog',{name:'Convert lead to Customer'});await expect(conversion.getByRole('button',{name:'Review',exact:true})).toBeDisabled();await conversion.getByLabel('Customer required information',{exact:false}).fill('Provided');await reviewSave(page,'Confirm conversion');await expect(conversion).not.toBeVisible();await expect(detail.getByRole('link',{name:'Open Customer'})).toBeVisible();const after=(await(await request.get(api+'/api/crm/leads/'+lead.id,{headers:h})).json()).data;expect(after.status).toBe('converted');expect((await request.post(api+'/api/crm/leads/'+lead.id+'/convert',{headers:h,data:{mode:'existing',expectedVersion:after.version,customerId:after.converted_customer_id}})).status()).toBe(409);await detail.getByRole('link',{name:'Open Customer'}).click();await expect(page).toHaveURL(/customers/);await expect(page.getByRole('dialog',{name:'Customer details'}).getByText('Provided',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'CRM origin · selected branch'})).toBeVisible();
});
test('unentitled navigation and direct API deny, read-only role, tenant and branch negatives',async({page,request})=>{
 const {h,stages}=await seed(request),created=await request.post(api+'/api/crm/leads',{headers:h,data:{name:'Private lead',pipelineStageId:stages[0].id}});const lead=(await created.json()).data;
 const none:Fixture=await(await request.post(api+'/__test/fixture',{data:{permissions:['crm.read','crm.manage','reports.read']}})).json();await login(page,none);await expect(page.getByRole('link',{name:'CRM & Follow-ups',exact:true})).toHaveCount(0);await page.goto('/crm');await expect(page.getByText('Upgrade Required',{exact:true})).toBeVisible();const nh=await headers(request,none);for(const path of ['/crm/leads','/reports/crm-leads','/reports/crm-leads/export','/forms/lead/values/'+lead.id])expect((await request.get(api+'/api'+path,{headers:nh})).status()).toBe(403);
 expect((await request.get(api+'/api/crm/leads',{headers:{...h,'x-tenant-id':none.organizationId}})).status()).toBe(403);expect((await request.get(api+'/api/crm/leads/'+lead.id,{headers:{...h,'x-branch-id':none.branchId}})).status()).toBe(403);
 const readonly:Fixture=await(await request.post(api+'/__test/fixture',{data:{modules:['crm'],permissions:['crm.read']}})).json(),rh=await headers(request,readonly);expect((await request.post(api+'/api/crm/stages/recommended',{headers:rh,data:{}})).status()).toBe(403);const signedOut=page.waitForResponse(r=>r.url().endsWith('/api/auth/logout')&&r.request().method()==='POST');await page.getByRole('button',{name:'Sign out',exact:true}).click();expect((await signedOut).status()).toBe(200);await expect(page.getByLabel('Phone or email')).toBeVisible();await login(page,readonly);await page.goto('/crm');await expect(page.getByRole('button',{name:'Create lead',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Pipeline settings',exact:true})).toHaveCount(0);
});
for(const width of [360,390,768,1440])for(const theme of ['light','dark','system'])test(`CRM fits ${width}px ${theme}`,async({page,request})=>{
 const {h,stages}=await seed(request);const name='QA descriptive CRM lead '.repeat(7).slice(0,190),r=await request.post(api+'/api/crm/leads',{headers:h,data:{name,company:'QA '.repeat(60),pipelineStageId:stages[0].id}});expect(r.status()).toBe(201);const lead=(await r.json()).data;
 expect((await request.post(api+'/api/crm/followups',{headers:h,data:{leadId:lead.id,type:'task',subject:'QA overdue follow-up',localDue:'2026-01-01T10:30',note:'Plain bounded QA note '.repeat(50)}})).status()).toBe(201);
 await page.setViewportSize({width,height:900});await login(page);await page.goto('/settings?section=appearance');await page.getByRole('radio',{name:new RegExp(theme,'i')}).click();await page.goto('/crm');await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.getByRole('button',{name:'View '+name,exact:true}).click();const detail=page.getByRole('dialog',{name:'Lead details'});await expect(detail.getByRole('heading',{name,exact:true})).toBeVisible();await expect(detail.getByText('Follow-up created',{exact:false})).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await detail.getByRole('button',{name:'Close modal'}).click();
 await page.getByRole('button',{name:'Follow-ups',exact:true}).click();await page.getByLabel('Follow-up view').selectOption('overdue');await expect(page.getByRole('heading',{name:'QA overdue follow-up'})).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
