import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { client } from '../../api/client';
import { useAppStore } from '../../store/useAppStore';
import { Input } from '../ui/Input';
import type { FormSchema } from '../forms/formSchema';
export function CustomerReportFilter({onApply,entity='customer'}:{entity?:'customer'|'lead';onApply:(key:string,value:string,operator:string)=>void}){
 const {activeTenantId,user}=useAppStore(),[key,setKey]=useState(''),[value,setValue]=useState(''),[operator,setOperator]=useState('eq');
 const query=useQuery({queryKey:['entity-report-fields',user?.id,activeTenantId,entity],queryFn:async()=>(await client.get<{data:FormSchema}>(`/forms/${entity}/schema`)).data.data,staleTime:30_000});
 const definitions=query.data?.definitions.filter(f=>f.status==='active'&&f.filterable&&f.field_type!=='multiselect')??[],field=definitions.find(f=>f.key===key);
 return <div className="page-stack">{query.isError&&<p role="alert">Custom filters unavailable. <button onClick={()=>void query.refetch()}>Retry fields</button></p>}{Boolean(definitions.length)&&<><label>{entity==='lead'?'Lead':'Customer'} field filter<select className="w-full" value={key} onChange={e=>{setKey(e.target.value);setValue('');setOperator('eq');}}><option value="">No custom filter</option>{definitions.map(f=><option value={f.key} key={f.key}>{f.label}</option>)}</select></label>{field&&<><label>Comparison<select className="w-full" value={operator} onChange={e=>setOperator(e.target.value)}><option value="eq">Equals</option>{['number','currency','date','datetime'].includes(field.field_type)&&<><option value="gte">At least / on or after</option><option value="lte">At most / on or before</option></>}</select></label>{['select','radio','checkbox'].includes(field.field_type)?<label>Field value<select className="w-full" value={value} onChange={e=>setValue(e.target.value)}><option value="">Choose value</option>{field.field_type==='checkbox'?<><option value="true">Yes</option><option value="false">No</option></>:field.options.map(o=><option key={o.id} value={o.id}>{o.label}{o.status==='archived'?' (archived)':''}</option>)}</select></label>:<Input label={field.field_type==='currency'?'Field value (INR minor units)':'Field value'} value={value} maxLength={1000} onChange={e=>setValue(e.target.value)}/>}</>}<button className="quiet-button" disabled={Boolean(key)&&!value} onClick={()=>onApply(key,value,operator)}>Apply {entity==='lead'?'lead':'customer'} field filter</button></>}</div>;
}
