import { test,expect,type Page,type APIRequestContext } from '@playwright/test';
const api='http://127.0.0.1:5011';
interface Fixture {phone:string;password:string;organizationId:string;branchId:string}
let fixture:Fixture,errors:string[];
test.beforeEach(async({page,request})=>{fixture=await(await request.post(api+'/__test/fixture',{data:{modules:['purchasing','inventory']}})).json();errors=[];page.on('pageerror',e=>errors.push(e.name));});
test.afterEach(()=>expect(errors).toEqual([]));
async function login(page:Page,f=fixture){await page.goto('/login');await page.getByLabel('Phone or email').fill(f.phone);await page.getByLabel('Password',{exact:true}).fill(f.password);await page.getByRole('button',{name:'Sign In to Ekavio'}).click();await expect(page).toHaveURL(/dashboard/);}
async function signOut(page:Page){const result=page.waitForResponse(r=>r.url().endsWith('/api/auth/logout')&&r.request().method()==='POST');await page.getByRole('button',{name:'Sign out',exact:true}).click();expect((await result).status()).toBe(200);await expect(page.getByLabel('Phone or email')).toBeVisible();}
async function headers(request:APIRequestContext,f=fixture){const r=await request.post(api+'/api/auth/login',{data:{phone:f.phone,password:f.password}});expect(r.status()).toBe(200);return {authorization:'Bearer '+(await r.json()).accessToken,'x-tenant-id':f.organizationId,'x-branch-id':f.branchId};}
async function seed(request:APIRequestContext,name='QA Purchasing Supplier'){
 const h=await headers(request),sr=await request.post(api+'/api/suppliers',{headers:h,data:{name}});expect(sr.status()).toBe(201);const supplier=(await sr.json()).data;
 const items=[];for(const name of ['QA flour','QA rice']){const r=await request.post(api+'/api/inventory',{headers:h,data:{name,unitCode:'kg',reorderThreshold:'0',price:'999.00',currency:'INR',idempotencyKey:crypto.randomUUID()}});expect(r.status()).toBe(201);items.push((await r.json()).data);}
 const r=await request.post(api+'/api/purchasing/orders',{headers:h,data:{supplierId:supplier.id,orderDate:'2026-10-08',expectedDeliveryDate:'2026-10-09',lines:[{itemId:items[0].id,quantity:'10',unitPrice:'1.25'},{itemId:items[1].id,quantity:'1.250',unitPrice:'10.01'}]}});expect(r.status()).toBe(201);const order=(await r.json()).data;
 return {h,supplier,items,order};
}
async function ordered(request:APIRequestContext,name?:string){const f=await seed(request,name);expect((await request.post(api+'/api/purchasing/orders/'+f.order.id+'/status',{headers:f.h,data:{expectedVersion:f.order.version,status:'ordered'}})).status()).toBe(200);const detail=(await(await request.get(api+'/api/purchasing/orders/'+f.order.id,{headers:f.h})).json()).data;return {...f,order:detail};}
test('owner sees honest empty suppliers, orders and item selection with optional contacts',async({page})=>{
 await login(page);await page.goto('/suppliers');await expect(page.getByRole('heading',{name:'No suppliers yet'})).toBeVisible();await page.getByRole('button',{name:'Add Supplier',exact:true}).click();const d=page.getByRole('dialog',{name:'Add Supplier'});await d.getByLabel('Supplier name').fill('QA first name-only supplier');await d.getByRole('button',{name:'Save Supplier'}).click();await expect(d).not.toBeVisible();await page.getByRole('button',{name:'View QA first name-only supplier',exact:true}).click();await expect(page.getByRole('dialog',{name:'Supplier details'}).getByText('0 orders · Last ordered: Never',{exact:true})).toBeVisible();await page.getByRole('dialog',{name:'Supplier details'}).getByRole('button',{name:'Close modal'}).click();await page.goto('/purchasing');await expect(page.getByRole('heading',{name:'No Purchase Orders yet'})).toBeVisible();await page.getByRole('button',{name:'Create Purchase Order',exact:true}).click();const editor=page.getByRole('dialog',{name:'Create Purchase Order'});await expect(editor.getByText('No active matching Inventory items. Create items in Inventory first.',{exact:true})).toBeVisible();await expect(editor.getByRole('button',{name:'Save draft'})).toBeDisabled();
});

test('Purchase Order references remain contained with wider fallback font metrics',async({page,request})=>{
 const f=await ordered(request,'QA descriptive purchasing supplier '.repeat(6).slice(0,190).trim());await page.setViewportSize({width:360,height:900});await login(page);
 await page.goto('/purchasing?order='+f.order.id);await expect(page.getByRole('dialog',{name:'Purchase Order details'})).toBeVisible();
 await expect(page.getByRole('button',{name:'View '+f.order.human_reference,exact:true})).toBeVisible();
 await page.addStyleTag({content:'body, body * { font-family: monospace !important; font-size: 18px !important; }'});
 const dimensions=await page.evaluate(()=>({viewport:innerWidth,document:document.documentElement.scrollWidth,overflowing:[...document.querySelectorAll('main *')].map(e=>({tag:e.tagName,classes:e.className,right:e.getBoundingClientRect().right,width:e.getBoundingClientRect().width})).filter(e=>e.right>innerWidth).slice(0,12)}));
 expect(dimensions.document,JSON.stringify(dimensions)).toBeLessThanOrEqual(dimensions.viewport);
});
test('supplier directory and UI two-line draft, partial and full canonical receiving',async({page,request})=>{
 const f=await seed(request);await login(page);await page.goto('/suppliers');await page.getByRole('button',{name:'Add Supplier',exact:true}).click();const supplier=page.getByRole('dialog',{name:'Add Supplier'});await supplier.getByLabel('Supplier name').fill('QA name-only supplier');await supplier.getByRole('button',{name:'Save Supplier'}).click();await expect(supplier).not.toBeVisible();await page.getByLabel('Search suppliers').fill('QA name-only supplier');await page.getByRole('button',{name:'Edit QA name-only supplier',exact:true}).click();const editSupplier=page.getByRole('dialog',{name:'Edit Supplier'});await editSupplier.getByLabel('Supplier lifecycle').selectOption('archived');await editSupplier.getByRole('button',{name:'Save Supplier'}).click();await expect(editSupplier).not.toBeVisible();await expect(page.getByText('archived',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Edit QA name-only supplier',exact:true}).click();await editSupplier.getByLabel('Supplier lifecycle').selectOption('active');await editSupplier.getByRole('button',{name:'Save Supplier'}).click();await expect(editSupplier).not.toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'QA name-only supplier',exact:true})).toBeVisible();
 await page.goto('/purchasing');await page.getByRole('button',{name:'Create Purchase Order',exact:true}).click();const editor=page.getByRole('dialog',{name:'Create Purchase Order'});await editor.getByLabel('Order supplier').selectOption({label:'QA Purchasing Supplier'});await editor.getByLabel('Order date',{exact:true}).fill('2026-10-08');await editor.getByLabel('Expected delivery date (optional)').fill('2026-10-10');await editor.getByRole('button',{name:'Add QA flour · kg',exact:true}).click();await editor.getByRole('button',{name:'Add QA rice · kg',exact:true}).click();await editor.getByLabel('Ordered quantity — QA flour').fill('10');await editor.getByLabel('Agreed unit price INR — QA flour').fill('1.25');await editor.getByLabel('Ordered quantity — QA rice').fill('1.250');await editor.getByLabel('Agreed unit price INR — QA rice').fill('10.01');await expect(editor.getByText('Ordered purchase value: ₹25.01',{exact:true})).toBeVisible();const saved=page.waitForResponse(r=>r.url().endsWith('/api/purchasing/orders')&&r.request().method()==='POST');await editor.getByRole('button',{name:'Save draft'}).click();const response=await saved;expect(response.status()).toBe(201);const po=(await response.json()).data;await expect(editor).not.toBeVisible();expect((await(await request.get(api+'/api/inventory/'+f.items[0].id,{headers:f.h})).json()).data.quantity).toBe('0.000');
 await page.getByRole('button',{name:'View '+po.human_reference,exact:true}).click();const detail=page.getByRole('dialog',{name:'Purchase Order details'});await detail.getByRole('button',{name:'Mark as Ordered',exact:true}).click();await page.getByRole('dialog',{name:'Mark as Ordered'}).getByRole('button',{name:'Confirm Mark as Ordered'}).click();await expect(page.getByRole('dialog',{name:'Mark as Ordered'})).not.toBeVisible();await page.getByRole('button',{name:'View '+po.human_reference,exact:true}).click();await detail.getByRole('button',{name:'Receive Goods',exact:true}).click();let receive=page.getByRole('dialog',{name:'Receive Goods'});await expect(receive.getByLabel('Quantity actually received — QA flour')).toHaveValue('');await expect(receive.getByRole('button',{name:'Review receipt'})).toBeDisabled();await receive.getByLabel('Quantity actually received — QA flour').fill('4');await receive.getByRole('button',{name:'Review receipt'}).click();await receive.getByRole('button',{name:'Confirm Receive Goods'}).click();await expect(receive).not.toBeVisible();await expect(detail.getByText('Ordered 10.000 · Received 4.000 · Remaining 6.000',{exact:true})).toBeVisible();await expect(detail.getByText(/partially received · Version/)).toBeVisible();await expect(detail.getByRole('link',{name:'View canonical movement',exact:true})).toHaveCount(1);expect((await(await request.get(api+'/api/inventory/'+f.items[0].id,{headers:f.h})).json()).data.quantity).toBe('4.000');
 await detail.getByRole('button',{name:'Receive Goods',exact:true}).click();receive=page.getByRole('dialog',{name:'Receive Goods'});await receive.getByLabel('Quantity actually received — QA flour').fill('6.001');await expect(receive.getByRole('button',{name:'Review receipt'})).toBeDisabled();await receive.getByLabel('Quantity actually received — QA flour').fill('6');await receive.getByLabel('Quantity actually received — QA rice').fill('1.250');await receive.getByRole('button',{name:'Review receipt'}).click();await receive.getByRole('button',{name:'Confirm Receive Goods'}).click();await expect(receive).not.toBeVisible();await expect(detail.getByText('Ordered 10.000 · Received 10.000 · Remaining 0.000',{exact:true})).toBeVisible();await expect(detail.getByText('Ordered 1.250 · Received 1.250 · Remaining 0.000',{exact:true})).toBeVisible();await expect(detail.getByRole('button',{name:'Receive Goods'})).toHaveCount(0);await detail.getByRole('button',{name:'Close modal'}).click();await page.reload();await page.getByRole('button',{name:'View '+po.human_reference,exact:true}).click();await expect(detail.getByText(/received · Version/)).toBeVisible();const canonical=(await(await request.get(api+'/api/inventory/'+f.items[0].id,{headers:f.h})).json()).data;expect(canonical.quantity).toBe('10.000');expect(canonical.price).toBe('999.00');await detail.getByRole('button',{name:'Close modal'}).click();await page.goto('/suppliers');await page.getByRole('button',{name:'View QA Purchasing Supplier',exact:true}).click();const supplierHistory=page.getByRole('dialog',{name:'Supplier details'});await expect(supplierHistory.getByText(po.human_reference,{exact:true})).toBeVisible();await expect(supplierHistory.getByText(/^purchase · received · /)).toBeVisible();await supplierHistory.getByRole('button',{name:'Close modal'}).click();await page.goto('/purchasing?order='+po.id);await detail.locator('a[href^="/inventory?item='+f.items[0].id+'&movement="]').first().click();const inventoryDetail=page.getByRole('dialog',{name:'Inventory item details'});await expect(inventoryDetail.getByRole('heading',{name:'QA flour',exact:true})).toBeVisible();await expect(inventoryDetail.getByRole('heading',{name:'Movement history',exact:true})).toBeVisible();await expect(inventoryDetail.getByText(/Purchasing receipt — independent reversal blocked/).first()).toBeVisible();await expect(inventoryDetail.getByRole('button',{name:'Reverse movement'})).toHaveCount(0);
});
test('HTTP idempotency, over-receive, altered retry and reversal protect physical stock',async({request})=>{
 const f=await ordered(request),command={expectedVersion:f.order.version,idempotencyKey:crypto.randomUUID(),lines:[{orderLineId:f.order.lines[0].id,quantity:'4'}]},path=api+'/api/purchasing/orders/'+f.order.id+'/receive';const responses=await Promise.all([request.post(path,{headers:f.h,data:command}),request.post(path,{headers:f.h,data:command})]);for(const r of responses)expect(r.status()).toBe(201);expect((await responses[0].json()).data.id).toBe((await responses[1].json()).data.id);expect((await request.post(path,{headers:f.h,data:{...command,lines:[{orderLineId:f.order.lines[0].id,quantity:'3'}]}})).status()).toBe(409);let d=(await(await request.get(api+'/api/purchasing/orders/'+f.order.id,{headers:f.h})).json()).data;expect((await request.post(path,{headers:f.h,data:{...command,expectedVersion:d.version,idempotencyKey:crypto.randomUUID(),lines:[{orderLineId:d.lines[0].id,quantity:'6.001'}]}})).status()).toBe(409);expect((await request.post(api+'/api/inventory/movements/'+d.receipts[0].lines[0].movement_id+'/reversal',{headers:f.h,data:{reason:'QA prohibited reversal',idempotencyKey:crypto.randomUUID()}})).status()).toBe(409);d=(await(await request.get(api+'/api/inventory/'+f.items[0].id,{headers:f.h})).json()).data;expect(d.quantity).toBe('4.000');
});
test('module, tenant, branch and independently managed stock authorities fail closed',async({page,request})=>{
 const f=await ordered(request),none:Fixture=await(await request.post(api+'/__test/fixture',{data:{permissions:['purchasing.read','purchasing.manage','inventory.read','inventory.manage']}})).json();const nh=await headers(request,none);expect((await request.get(api+'/api/suppliers',{headers:nh})).status()).toBe(403);await login(page,none);await expect(page.getByRole('link',{name:'Suppliers',exact:true})).toHaveCount(0);await page.goto('/purchasing');await expect(page.getByText('Upgrade Required',{exact:true})).toBeVisible();expect((await request.get(api+'/api/purchasing/orders/'+f.order.id,{headers:{...f.h,'x-tenant-id':none.organizationId}})).status()).toBe(403);expect((await request.get(api+'/api/purchasing/orders/'+f.order.id,{headers:{...f.h,'x-branch-id':none.branchId}})).status()).toBe(403);
 const readonly:Fixture=await(await request.post(api+'/__test/fixture',{data:{modules:['purchasing','inventory'],permissions:['purchasing.read','inventory.read']}})).json(),rh=await headers(request,readonly);expect((await request.post(api+'/api/suppliers',{headers:rh,data:{name:'Denied'}})).status()).toBe(403);expect((await request.get(api+'/api/purchasing/orders/'+f.order.id,{headers:rh})).status()).toBe(404);await signOut(page);await login(page,readonly);await page.goto('/purchasing');await expect(page.getByRole('heading',{name:'No Purchase Orders yet'})).toBeVisible();await expect(page.getByRole('button',{name:'Create Purchase Order'})).toHaveCount(0);
 const purchasingOnly:Fixture=await(await request.post(api+'/__test/fixture',{data:{modules:['purchasing'],permissions:['purchasing.read','purchasing.manage','inventory.read','inventory.manage']}})).json(),ph=await headers(request,purchasingOnly);expect((await request.post(api+'/api/suppliers',{headers:ph,data:{name:'Purchasing-only supplier'}})).status()).toBe(201);expect((await request.get(api+'/api/purchasing/orders',{headers:ph})).status()).toBe(403);expect((await request.post(api+'/api/purchasing/orders/'+f.order.id+'/receive',{headers:ph,data:{expectedVersion:1,idempotencyKey:crypto.randomUUID(),lines:[{orderLineId:f.order.lines[0].id,quantity:'1'}]}})).status()).toBe(403);await signOut(page);await login(page,purchasingOnly);await page.goto('/purchasing');await expect(page.getByRole('heading',{name:'Inventory access required for Purchase Orders'})).toBeVisible();await page.goto('/suppliers');await expect(page.getByRole('heading',{name:'Purchasing-only supplier',exact:true})).toBeVisible();
});
test('three reports and formula-safe CSV show ordered facts not paid amounts',async({page,request})=>{
 const f=await ordered(request,'=QA Purchasing CSV');expect((await request.post(api+'/api/purchasing/orders/'+f.order.id+'/receive',{headers:f.h,data:{expectedVersion:f.order.version,idempotencyKey:crypto.randomUUID(),lines:[{orderLineId:f.order.lines[0].id,quantity:'4'}]}})).status()).toBe(201);await login(page);await page.goto('/reports');for(const key of ['purchase-orders','goods-received','supplier-purchases']){await page.getByRole('combobox',{name:'Report',exact:true}).selectOption(key);await expect(page.getByRole('cell',{name:'=QA Purchasing CSV',exact:true})).toBeVisible();const result=page.waitForResponse(r=>r.url().includes('/reports/'+key+'/export'));await page.getByRole('button',{name:'Export CSV'}).click();const response=await result;expect(response.status()).toBe(200);expect(await response.text()).toContain('"\'=QA Purchasing CSV"');}await page.goto('/dashboard');await expect(page.getByRole('heading',{name:'Open Purchase Orders',exact:true})).toBeVisible();
});
for(const width of [360,390,768,1440])for(const theme of ['light','dark','system'])test(`Purchasing fits ${width}px ${theme}`,async({page,request})=>{
 const name='QA descriptive purchasing supplier '.repeat(6).slice(0,190).trim(),f=await ordered(request,name);await page.setViewportSize({width,height:900});await login(page);await page.goto('/settings?section=appearance');await page.getByRole('radio',{name:new RegExp(theme,'i')}).click();await page.goto('/suppliers');await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.getByRole('button',{name:'Edit '+name,exact:true}).click();await expect(page.getByRole('dialog',{name:'Edit Supplier'}).getByLabel('Supplier name')).toHaveValue(name);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.getByRole('dialog',{name:'Edit Supplier'}).getByRole('button',{name:'Close modal'}).click();await page.goto('/purchasing?order='+f.order.id);const detail=page.getByRole('dialog',{name:'Purchase Order details'});await expect(detail.getByRole('heading',{name,exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await detail.getByRole('button',{name:'Receive Goods',exact:true}).click();const receive=page.getByRole('dialog',{name:'Receive Goods'});await expect(receive.getByLabel('Quantity actually received — QA flour')).toHaveValue('');await receive.getByLabel('Quantity actually received — QA flour').fill('4');await receive.getByRole('button',{name:'Review receipt'}).click();await expect(receive.getByRole('heading',{name:'Confirm actual goods received'})).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();if(width===390&&theme==='dark')await page.screenshot({path:'test-results/purchasing/receiving-390-dark.png'});await receive.getByRole('button',{name:'Close modal'}).click();await page.getByRole('button',{name:'Create Purchase Order',exact:true}).click();const editor=page.getByRole('dialog',{name:'Create Purchase Order'});await editor.getByLabel('Order supplier').selectOption({label:name});await editor.getByLabel('Order date',{exact:true}).fill('2026-10-08');await editor.getByRole('button',{name:'Add QA flour · kg',exact:true}).click();await editor.getByLabel('Ordered quantity — QA flour').fill('1.250');await editor.getByLabel('Agreed unit price INR — QA flour').fill('10.01');await expect(editor.getByText('Ordered purchase value: ₹12.51',{exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
