import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdtemp,readdir,copyFile,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { PostgresDatabase } from '../src/postgres/database.js';
import { migrate,getMigrationStatus } from '../src/postgres/migrations.js';
import { PostgresAccountRepository } from '../src/postgres/accountRepository.js';
import { PostgresCustomerRepository } from '../src/domains/customers/repository.js';
import { PostgresServiceRepository } from '../src/domains/services/repository.js';
import { PostgresCustomerDuesRepository } from '../src/domains/customerDues/repository.js';
import { PostgresInventoryRepository } from '../src/domains/inventory/repository.js';
import { PostgresAppointmentRepository } from '../src/domains/appointments/repository.js';
import { DynamicFieldsService,type DefinitionInput } from '../src/domains/dynamicFields/service.js';
import { DashboardAnalyticsService } from '../src/domains/analytics/dashboardService.js';
import { ReportService } from '../src/domains/analytics/reportService.js';
import { NotificationService,notifyOrganizationChange } from '../src/domains/notifications/service.js';
import { OrganizationAdministrationService } from '../src/services/organizationAdministrationService.js';
import { permissionsForRole } from '../src/services/authorizationPolicy.js';
import type { AuthorizationContext } from '../src/services/requestContextService.js';
test('analytics reports notifications against isolated local PostgreSQL',async t=>{
 const url=new URL(process.env.POSTGRES_TEST_URL??'');assert.ok(['postgres','localhost','127.0.0.1'].includes(url.hostname)&&url.pathname==='/postgres');const admin=new PostgresDatabase(url.href),name='ekavio_v208e_'+randomUUID().replaceAll('-','');await admin.query('CREATE DATABASE '+name);url.pathname='/'+name;const db=new PostgresDatabase(url.href);
 t.after(async()=>{await db.close();await admin.query('SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname=$1',[name]);await admin.query('DROP DATABASE '+name);await admin.close();});
 await t.test('015 upgrade, immutable historical checksums and idempotent 016',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'v208e-'));try{for(const f of (await readdir('postgres/migrations')).filter(f=>f.endsWith('.sql')&&Number(f.slice(0,3))<=15))await copyFile(path.join('postgres/migrations',f),path.join(dir,f));await migrate(db,dir);const before=(await db.query('SELECT name,checksum FROM schema_migrations ORDER BY name')).rows;await migrate(db);await migrate(db);assert.equal((await getMigrationStatus(db)).length, 19);assert.deepEqual((await db.query("SELECT name,checksum FROM schema_migrations WHERE name<'016' ORDER BY name")).rows,before);}finally{await rm(dir,{recursive:true});}});
 const accounts=new PostgresAccountRepository(db);
 const a=await accounts.registerAdmin({orgName:'QA analytics A',orgType:'shop',userName:'QA A',phone:'+919876540011',passwordHash:'fixture-only'}),b=await accounts.registerAdmin({orgName:'QA analytics B',orgType:'shop',userName:'QA B',phone:'+919876540012',passwordHash:'fixture-only'});
 const org=String(a.user.tenantId),user=String(a.user.id),branch=String((a.branch as {id:string}).id),foreign=String(b.user.tenantId),foreignBranch=String((b.branch as {id:string}).id),membership=String((await db.query('SELECT id FROM memberships WHERE user_id=$1',[user])).rows[0]!.id);
 await db.query("UPDATE branches SET timezone='Asia/Kolkata'");
 const c:AuthorizationContext={organizationId:org,userId:user,membershipId:membership,branchId:branch,sessionId:'fixture',role:'admin',permissions:permissionsForRole('admin'),platformOperator:false};
 const modules=new Set(['queue','attendance','ledger','inventory']),enabled=async()=>modules,dashboard=new DashboardAnalyticsService(db,enabled),reports=new ReportService(db,enabled),notifications=new NotificationService(db),fields=new DynamicFieldsService(db);
 const customer=await new PostgresCustomerRepository(db).create({organizationId:org,name:'=SUM(1,1)',notes:'Disposable local notes'}),service=await new PostgresServiceRepository(db).createForBranch({organizationId:org,branchId:branch,name:'QA service',durationMinutes:30});
 await t.test('every curated query executes and unauthorized dashboard payload is absent',async()=>{for(const report of await reports.catalogue(c)){const data=await reports.run(c,report.key,{});assert.equal(data.scope,report.scope);}const limited=await dashboard.get({...c,permissions:['customers.read','services.read']});assert.deepEqual(limited.widgets.map(w=>w.key),['customers','services']);assert.equal(limited.totalQueue,undefined);assert.equal(limited.lowStockItems,undefined);assert.equal(limited.presentStaff,undefined);assert.equal((await dashboard.get(c)).widgets.find(w=>w.key==='customers')!.value,'1');});
 await t.test('report access matrix rejects missing reports/domain/entitlement',async()=>{for(const key of ['inventory','appointments','attendance','dues-balances']){await assert.rejects(reports.run({...c,permissions:['reports.read']},key,{}),/denied/);await assert.rejects(reports.run({...c,permissions:c.permissions.filter(p=>p!=='reports.read')},key,{}),/denied/);}const none=new ReportService(db,async()=>new Set());for(const key of ['inventory','appointments','attendance','dues-journal'])await assert.rejects(none.run(c,key,{}),/denied/);assert.equal((await none.run(c,'customers',{})).total,1);assert.equal((await none.run(c,'services',{})).total,1);assert.equal((await new DashboardAnalyticsService(db,async()=>new Set()).get(c)).widgets.some(w=>['queue','attendance','dues','inventory'].includes(w.key)),false);});
 await t.test('branch/filter isolation and closed ranges',async()=>{await assert.rejects(reports.run(c,'customers',{branchId:foreignBranch}),/branch/);await assert.rejects(reports.run(c,'appointments',{customerId:randomUUID()}),/unavailable/);await assert.rejects(reports.run(c,'appointments',{from:'2025-01-01',to:'2026-10-07'}),/366/);await assert.rejects(reports.run(c,'customers',{sql:'injected'}),/Invalid/);await assert.rejects(reports.run(c,'dues-balances',{from:'2026-10-01'}),/all-time/);});
 const definition=(key:string,type:DefinitionInput['fieldType']='text'):DefinitionInput=>({key,label:'QA '+key,help:'',fieldType:type,status:'active',required:false,searchable:false,filterable:type!=='multiselect',reportable:true,defaultValue:null,options:[]});
 await t.test('batch reportable fields, choices retain archived labels and CSV safety',async()=>{
  const choice=await fields.saveDefinition(c,'customer',{...definition('choice','select'),options:[{key:'old',label:'Historical choice',status:'active'}]}),multi=await fields.saveDefinition(c,'customer',{...definition('multi','multiselect'),options:[{key:'one',label:'One',status:'active'},{key:'two',label:'Two',status:'active'}]});
  await fields.saveDefinition(c,'customer',definition('money','currency'));await fields.saveDefinition(c,'customer',{...definition('private'),reportable:false});await fields.saveDefinition(c,'customer',definition('danger'));
  await fields.mutate(c,'customer',{choice:choice.options[0]!.id,multi:multi.options.map(o=>o.id),money:'900719925474099399',private:'Not reportable',danger:' =CMD()'},false,async()=>({id:customer.id}));
  await fields.saveDefinition(c,'customer',{...definition('choice','select'),version:1,options:[...choice.options.map(o=>({...o,status:'archived' as const})),{key:'new',label:'Current choice',status:'active'}]},choice.id);
  const data=await reports.run(c,'customers',{columns:'name,custom:choice,custom:multi,custom:money,custom:danger'});assert.equal(data.rows[0]!['custom:choice'],'Historical choice');assert.equal(data.rows[0]!['custom:multi'],'One; Two');assert.equal(data.rows[0]!['custom:money'],'900719925474099399');assert.ok(!data.columns.some(col=>col.key==='custom:private'));await assert.rejects(reports.run(c,'customers',{columns:'custom:private'}),/columns/);
  const csv=await reports.run(c,'customers',{columns:'name,custom:danger,custom:money'},true);assert.ok('csv' in csv);assert.match(csv.csv,/"'=SUM/);assert.match(csv.csv,/"'=CMD/);assert.match(csv.csv,/₹9007199254740993.99/);assert.equal((await db.query('SELECT row_count FROM report_export_events')).rows[0]!.row_count,1);await assert.rejects(db.query('DELETE FROM report_export_events'),/history|append|immutable/i);
  assert.equal((await reports.run(c,'customers',{customKey:'danger',customValue:' =CMD()'})).total,1);
 });
 await t.test('all-time branch Dues sum preserves charges/payments/adjustments/reversals',async()=>{
  const dues=new PostgresCustomerDuesRepository(db),base={organizationId:org,branchId:branch,customerId:customer.id,currency:'INR' as const,dueDate:null,description:'Disposable QA',sourceType:null,sourceId:null,actorMembershipId:membership,commandFingerprint:'a'.repeat(64),occurredAt:new Date()};
  for(const [entryType,amountMinor] of [['charge',10001n],['payment',1234n],['adjustment_increase',333n],['adjustment_decrease',100n]] as const)await dues.create({...base,entryType,amountMinor,idempotencyKey:randomUUID()});
  const extra=await dues.create({...base,entryType:'payment',amountMinor:200n,idempotencyKey:randomUUID()});await dues.reverse({organizationId:org,branchId:branch,targetEntryId:extra.id,description:'QA reversal',actorMembershipId:membership,commandFingerprint:'b'.repeat(64),idempotencyKey:randomUUID(),occurredAt:new Date()});
  assert.equal((await reports.run(c,'dues-balances',{})).summary.outstanding_minor,'9000');assert.equal((await reports.run(c,'dues-journal',{})).summary.net_effect_minor,'9000');assert.equal((await dashboard.get(c)).widgets.find(w=>w.key==='dues')!.value,'9000');
 });
 await t.test('Inventory current branch stock reuses canonical quantity/threshold projection',async()=>{const item=await new PostgresInventoryRepository(db).createItem({organizationId:org,branchId:branch,name:'QA low item',sku:null,barcode:null,unitCode:'piece',priceMinor:101n,currency:'INR',reorderThreshold:'2.000',openingQuantity:'1.250',actorMembershipId:membership,idempotencyKey:randomUUID(),commandFingerprint:'c'.repeat(64),occurredAt:new Date()});const result=await reports.run(c,'inventory',{stockStatus:'low'});assert.equal(result.rows[0]!.quantity,item.quantity);assert.equal((await dashboard.get(c)).widgets.find(w=>w.key==='inventory')!.value,'1');});
 await t.test('dashboard optimistic persistence rejects stale/invalid and ignores newly unauthorized widgets',async()=>{await dashboard.save(c,{order:['inventory','customers'],hidden:['services'],version:0});await assert.rejects(dashboard.save(c,{order:[],hidden:[],version:0}),/changed/);const full=await dashboard.get(c);assert.equal(full.layout.version,1);const limited=await dashboard.get({...c,permissions:['customers.read']});assert.deepEqual(limited.layout.order,['customers']);assert.deepEqual(limited.layout.hidden,[]);await assert.rejects(db.query("INSERT INTO dashboard_preferences(organization_id,user_id) VALUES($1,$2)",[foreign,user]));});
 await t.test('all five reportable entities use typed batch values and live definition flags',async()=>{
  const item=String((await db.query('SELECT id FROM inventory_items WHERE organization_id=$1',[org])).rows[0]!.id);
  const appointment=await new PostgresAppointmentRepository(db).create({organizationId:org,branchId:branch,customerId:customer.id,serviceId:service.id,startsAt:new Date(),endsAt:new Date(Date.now()+1800000),actorMembershipId:membership});
  for(const [entity,key,id] of [['service','services',service.id],['appointment','appointments',appointment.id],['inventory_item','inventory',item],['membership','staff',membership]] as const){await fields.saveDefinition(c,entity,definition('typed','number'));await fields.mutate(c,entity,{typed:'123.456'},false,async()=>({id}));assert.equal((await reports.run(c,key,{columns:'custom:typed'})).rows[0]!['custom:typed'],'123.456000');}
  for(const [key,type,value] of [['day','date','2026-09-26'],['moment','datetime','2026-09-26T05:00:00.000Z'],['yes','checkbox',true]] as const){await fields.saveDefinition(c,'customer',definition(key,type));await fields.mutate(c,'customer',{[key]:value},false,async()=>({id:customer.id}));}
  const typed=await reports.run(c,'customers',{columns:'custom:day,custom:moment,custom:yes'});assert.equal(typed.rows[0]!['custom:day'],'2026-09-26');assert.match(String(typed.rows[0]!['custom:moment']),/^2026-09-26 10:30/);assert.equal(typed.rows[0]!['custom:yes'],'Yes');
  const visible=await fields.saveDefinition(c,'customer',definition('visibility'));await fields.saveDefinition(c,'customer',{...definition('visibility'),version:1,reportable:false},visible.id);await assert.rejects(reports.run(c,'customers',{columns:'custom:visibility'}),/columns/);
  await fields.saveDefinition(c,'customer',{...definition('visibility'),version:2,status:'archived'},visible.id);assert.ok(!(await reports.run(c,'customers',{})).columns.some(col=>col.key==='custom:visibility'));
  const foreignContext={...c,organizationId:foreign,userId:String(b.user.id),membershipId:String((await db.query('SELECT id FROM memberships WHERE organization_id=$1',[foreign])).rows[0]!.id),branchId:foreignBranch};await fields.saveDefinition(foreignContext,'customer',definition('foreign_only'));await assert.rejects(reports.run(c,'customers',{columns:'custom:foreign_only'}),/columns/);
 });
 await t.test('membership mutation and attention message share the transaction',async()=>{
  await new OrganizationAdministrationService(db).saveMember(c,membership,{role:'admin',customRoleId:null,status:'active',branchIds:[branch],version:1});
  assert.equal((await notifications.list(c,{})).unread,1);
 });
 await t.test('notification recipient resolution, duplicate suppression, ownership and read timestamp',async()=>{
  await db.transaction(client=>notifyOrganizationChange(client,org,membership,null,'membership.updated',2));await db.transaction(client=>notifyOrganizationChange(client,org,membership,null,'membership.updated',2));let list=await notifications.list(c,{});assert.equal(list.unread,1);assert.equal(list.rows.length,1);const id=String(list.rows[0]!.id);await assert.rejects(notifications.read({...c,userId:String(b.user.id)},id,true),/not found/);await notifications.read(c,id,true);list=await notifications.list(c,{});assert.equal(list.unread,0);assert.ok(list.rows[0]!.readAt);await notifications.read(c,id,false);assert.equal((await notifications.list(c,{})).unread,1);await notifications.readAll(c);assert.equal((await notifications.list(c,{})).unread,0);
  await assert.rejects(db.query("INSERT INTO user_notifications(organization_id,membership_id,user_id,category,event_key,title,message,action_key,dedupe_key) VALUES($1,$2,$3,'organization','membership.updated','t','m','settings','foreign')",[org,membership,String(b.user.id)]));
 });
 await t.test('notification preferences and inactive recipients deny optional fanout',async()=>{await notifications.savePreferences(c,{organizationChanges:false});await db.transaction(client=>notifyOrganizationChange(client,org,membership,null,'membership.updated',3));assert.equal((await notifications.list(c,{})).total,1);await assert.rejects(notifications.savePreferences(c,{organizationChanges:true,userId:String(b.user.id)}),/Invalid/);await notifications.savePreferences(c,{organizationChanges:true});await db.query("UPDATE memberships SET status='inactive' WHERE id=$1",[membership]);await db.transaction(client=>notifyOrganizationChange(client,org,membership,null,'membership.updated',4));await db.query("UPDATE memberships SET status='active' WHERE id=$1",[membership]);assert.equal((await notifications.list(c,{})).total,1);});
 await t.test('custom-role changes fan out only to active assigned own-workspace recipients',async()=>{
  const administration=new OrganizationAdministrationService(db),role=await administration.saveRole(c,{name:'QA recipient role',description:'',permissions:['customers.read']});
  const member=String((await db.query("INSERT INTO memberships(organization_id,user_id,role,custom_role_id,status,created_at,updated_at) VALUES($1,$2,'staff',$3,'active',now(),now()) RETURNING id",[org,String(b.user.id),role.id])).rows[0]!.id);await db.query('INSERT INTO membership_branch_assignments(organization_id,membership_id,branch_id) VALUES($1,$2,$3)',[org,member,branch]);
  await administration.saveRole(c,{name:'QA recipient role',description:'Changed safely',permissions:['customers.read','services.read'],version:1},String(role.id));
  const recipient={...c,userId:String(b.user.id),membershipId:member};const list=await notifications.list(recipient,{});assert.equal(list.total,1);assert.equal(list.rows[0]!.title,'Your role permissions changed');assert.ok(!String(list.rows[0]!.message).includes('QA recipient'));
  await db.query('DELETE FROM membership_branch_assignments WHERE membership_id=$1',[member]);await administration.saveRole(c,{name:'QA recipient role',description:'',permissions:['customers.read'],version:2},String(role.id));assert.equal((await notifications.list(recipient,{})).total,1);assert.equal((await notifications.list({...recipient,organizationId:foreign},{})).total,0);
 });
 await t.test('multiple customers, negative credit and a second branch never net away positive debt',async()=>{
  const second=await new PostgresCustomerRepository(db).create({organizationId:org,name:'QA credit customer'}),otherBranch=await new OrganizationAdministrationService(db).saveBranch(c,{name:'QA second',code:'QA2',timezone:'Asia/Kolkata',status:'active'});await db.query('INSERT INTO membership_branch_assignments(organization_id,membership_id,branch_id) VALUES($1,$2,$3)',[org,membership,otherBranch.id]);
  const dues=new PostgresCustomerDuesRepository(db),base={organizationId:org,currency:'INR' as const,dueDate:null,description:'Disposable QA branch isolation',sourceType:null,sourceId:null,actorMembershipId:membership,commandFingerprint:'d'.repeat(64),occurredAt:new Date()};
  await dues.create({...base,branchId:branch,customerId:second.id,entryType:'adjustment_decrease',amountMinor:500n,idempotencyKey:randomUUID()});await dues.create({...base,branchId:otherBranch.id,customerId:customer.id,entryType:'charge',amountMinor:1000n,idempotencyKey:randomUUID()});
  const balance=await reports.run(c,'dues-balances',{});assert.equal(balance.total,2);assert.equal(balance.summary.outstanding_minor,'9000');assert.equal(balance.summary.customers_owing,'1');assert.ok(balance.rows.some(row=>row.balance_minor==='-500'));assert.equal((await reports.run(c,'dues-journal',{})).summary.net_effect_minor,'8500');assert.equal((await reports.run({...c,branchId:String(otherBranch.id)},'dues-balances',{})).summary.outstanding_minor,'1000');assert.equal((await dashboard.get(c)).widgets.find(w=>w.key==='dues')!.value,'9000');
 });
 await t.test('wide text budget rejects oversized exports without truncation or audit leakage',async()=>{
  await fields.saveDefinition(c,'customer',definition('long_text','textarea'));await fields.mutate(c,'customer',{long_text:'x'.repeat(10000)},false,async()=>({id:customer.id}));
  await db.query("INSERT INTO customers(organization_id,name) SELECT $1,'QA export budget '||i FROM generate_series(1,80) i",[org]);
  const before=(await db.query('SELECT count(*) FROM report_export_events')).rows[0]!.count;await assert.rejects(reports.run(c,'customers',{columns:'name,custom:long_text'},true),/row budget/);assert.equal((await db.query('SELECT count(*) FROM report_export_events')).rows[0]!.count,before);await assert.rejects(reports.run(c,'customers',{columns:'name,custom:long_text',limit:100}),/too wide/);
 });
 await t.test('safe metadata-only export audit, notification retention and administrator/platform facts',async()=>{const administration=new OrganizationAdministrationService(db);const overview=await administration.overview({...c,permissions:['organization.read']});assert.equal(overview!.active_staff,undefined);assert.ok(await administration.platformOverview());await db.query("UPDATE user_notifications SET created_at=now()-interval '100 days',read_at=now()-interval '95 days' WHERE organization_id=$1",[org]);assert.equal(await notifications.pruneRead(),2);assert.equal((await db.query('SELECT count(*) FROM report_export_events')).rows[0]!.count,'1');const plan=(await db.query('EXPLAIN SELECT * FROM user_notifications WHERE organization_id=$1 AND user_id=$2 ORDER BY created_at DESC LIMIT 25',[org,user])).rows;assert.ok(plan.length);});
 assert.ok(service.id);
});
