import { test, expect, type Page } from '@playwright/test';
import { relationshipFixture } from './fixtures';
import { fits } from '../e2e-operations-visual/fixtures';
async function close(page: Page) { await page.getByRole('dialog').getByRole('button', { name: 'Close modal', exact: true }).click(); const discard = page.getByRole('button', { name: 'Discard changes', exact: true }); if (await discard.count()) await discard.click(); }
for (const width of [320, 360, 390, 430, 768, 1024, 1440, 1920]) for (const theme of ['light', 'dark', 'system']) test(`relationships loaded journeys ${width}px ${theme}`, async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.name));
  await page.setViewportSize({ width, height: 900 }); await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' }); const f = await relationshipFixture(page);
  await page.addInitScript(mode => localStorage.setItem('ekavio-ui-preferences', JSON.stringify({ mode, primaryColor: '#4F46E5' })), theme);
  const shot = async (name: string) => { await fits(page); for (const placeholder of await page.locator('.crm-workspace [data-dynamic-form]>section>div:empty').all()) expect(await placeholder.evaluate(e => e.getBoundingClientRect().height)).toBe(0); await page.screenshot({ path: `test-results/relationships-visual/${width}-${theme}-${name}.png`, fullPage: false }); };
  await page.goto('/crm'); await expect(page.getByRole('button', { name: 'View ' + f.lead.name, exact: true })).toBeVisible(); await expect(page.locator('html')).toHaveAttribute('data-theme', theme === 'system' ? 'dark' : theme); await shot('crm-overview'); await page.getByRole('heading', { name: 'Lead directory', exact: true }).scrollIntoViewIfNeeded(); await shot('crm-leads');
  if (theme === 'system') { await page.emulateMedia({ colorScheme: 'light' }); await expect(page.locator('html')).toHaveAttribute('data-theme', 'light'); await page.emulateMedia({ colorScheme: 'dark' }); }
  await page.getByRole('button', { name: 'pipeline', exact: true }).click(); await page.getByText('Lead filters', { exact: true }).click(); if (width < 768) await page.setViewportSize({ width, height: 1100 }); const pipelineStages = page.locator(width < 768 ? '.field.table-mobile' : '.pipeline-stages.table-desktop'); await pipelineStages.scrollIntoViewIfNeeded(); const pipelineLead = page.getByRole('button', { name: 'View ' + f.lead.name, exact: true }); await pipelineLead.scrollIntoViewIfNeeded(); await expect(pipelineStages).toBeInViewport(); await expect(pipelineLead).toBeInViewport(); const pipelineControl = width < 768 ? page.getByLabel('Pipeline stage for this branch') : page.getByRole('button', { name: 'View stage ' + f.stage.name, exact: true }); expect(await pipelineControl.evaluate(e => { const r = e.getBoundingClientRect(); return e.contains(document.elementFromPoint(r.x + r.width / 2, r.y + r.height / 2)); })).toBe(true); await shot('pipeline'); if (width < 768) await page.setViewportSize({ width, height: 900 }); await page.getByRole('button', { name: 'leads', exact: true }).click();
  await page.getByRole('button', { name: 'Create lead', exact: true }).click(); await page.getByLabel('Lead name', { exact: true }).fill('QA reviewed enquiry'); await shot('lead-form'); await page.getByRole('button', { name: 'Review', exact: true }).click(); await shot('lead-review'); await close(page);
  await page.getByRole('button', { name: 'View ' + f.lead.name, exact: true }).click(); await expect(page.getByRole('dialog').getByText('Lead created', { exact: false })).toBeVisible(); await shot('lead-detail');
  await page.getByRole('dialog').getByRole('button', { name: 'Add follow-up', exact: true }).click(); await expect(page.getByRole('dialog')).toHaveCount(1); await page.getByLabel('Follow-up subject').fill('QA review next action'); await page.getByLabel('Due date and time').fill('2026-10-07T10:30'); await shot('followup-form'); await page.getByRole('button', { name: 'Review', exact: true }).click(); await shot('followup-review'); await close(page);
  await page.getByRole('dialog', { name: 'Lead details' }).getByRole('button', { name: 'Convert to Customer' }).click(); await page.getByLabel('Customer name', { exact: true }).fill('QA canonical Customer'); await page.getByRole('button', { name: 'Review', exact: true }).click(); await shot('conversion-review'); await close(page); await close(page);
  await page.getByRole('button', { name: 'Follow-ups', exact: true }).click(); await expect(page.getByRole('heading', { name: 'QA discuss the next consultation', exact: true })).toBeVisible(); await page.getByLabel('Follow-up view').scrollIntoViewIfNeeded(); await shot('followups');
  await page.goto('/suppliers'); const supplierAction = page.getByRole('button', { name: 'View ' + f.supplier.name, exact: true }); await expect(supplierAction).toBeVisible(); await supplierAction.scrollIntoViewIfNeeded(); await expect(supplierAction).toBeInViewport(); await shot('suppliers'); await supplierAction.click(); await expect(page.getByRole('dialog').getByRole('heading', { name: f.supplier.name, exact: true })).toBeVisible(); await shot('supplier-detail'); await close(page);
  await page.getByRole('button', { name: 'Add Supplier', exact: true }).click(); await page.getByLabel('Supplier name').fill('QA name-only supplier'); await shot('supplier-form'); await close(page);
  await page.goto('/purchasing'); await expect(page.getByRole('button', { name: 'View ' + f.order.human_reference, exact: true })).toBeVisible(); await page.getByRole('heading', { name: 'Purchase Order directory', exact: true }).scrollIntoViewIfNeeded(); await shot('purchase-orders'); await page.getByRole('button', { name: 'Create Purchase Order', exact: true }).click();
  await page.getByLabel('Order supplier').selectOption(f.supplier.id); await page.getByLabel('Order date', { exact: true }).fill('2026-10-07');
  for (const [i, item] of f.items.entries()) { await page.getByLabel('Choose Inventory item').selectOption(item.id); await page.getByRole('button', { name: 'Add selected item', exact: true }).click(); await page.getByLabel('Ordered quantity — ' + item.name).fill(i ? '1.250' : '10'); await page.getByLabel('Agreed unit price INR — ' + item.name).fill(i ? '10.01' : '1.25'); }
  await expect(page.getByText('Ordered purchase value: ₹25.01', { exact: true })).toBeVisible(); await shot('po-editor'); await page.getByRole('button', { name: 'Review', exact: true }).click(); await shot('po-review'); await close(page);
  await page.getByRole('button', { name: 'View ' + f.order.human_reference, exact: true }).click(); await expect(page.getByRole('heading', { name: 'Recent receipts (latest 50)' })).toBeVisible(); await shot('po-detail'); await page.getByRole('button', { name: 'Receive Goods', exact: true }).click(); await expect(page.getByLabel('Quantity actually received — QA flour')).toHaveValue(''); await page.getByLabel('Quantity actually received — QA flour').fill('2.125'); await shot('partial-receipt'); await page.getByRole('button', { name: 'Review receipt', exact: true }).click(); await shot('receipt-confirmation'); await close(page);
  await page.getByRole('button', { name: 'Receiving history', exact: true }).click(); const receiptAction = page.getByRole('button', { name: 'View linked Purchase Order', exact: true }); await expect(receiptAction).toBeVisible(); await receiptAction.scrollIntoViewIfNeeded(); await expect(receiptAction).toBeInViewport(); await shot('receipt-history'); expect(errors).toEqual([]);
});
for (const path of ['/crm', '/suppliers', '/purchasing']) for (const width of [390, 1440]) test(`${path} loaded read-only/empty/error ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 }); const f = await relationshipFixture(page, true); await page.goto(path); await expect(page.getByText(/Read-only/)).toBeVisible(); await fits(page); await page.screenshot({ path: `test-results/relationships-visual/${width}-${path.slice(1)}-readonly.png` });
  f.empty(); await page.reload(); const emptyHeading = page.getByRole('heading', { name: path === '/crm' ? 'No leads yet' : path === '/suppliers' ? 'No suppliers yet' : 'No Purchase Orders yet', exact: true }); await expect(emptyHeading).toBeVisible(); await emptyHeading.scrollIntoViewIfNeeded(); await expect(emptyHeading).toBeInViewport(); await fits(page); await page.screenshot({ path: `test-results/relationships-visual/${width}-${path.slice(1)}-empty.png` });
  f.fail(); await page.reload(); await expect(page.getByRole('alert').filter({ hasText: 'Disposable simulated outage' }).first()).toBeVisible(); await fits(page); await page.screenshot({ path: `test-results/relationships-visual/${width}-${path.slice(1)}-error.png` });
});
test('short phone review footer, focus trap and discard stay reachable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 430 }); await relationshipFixture(page); await page.goto('/suppliers'); await page.getByRole('button', { name: 'Add Supplier', exact: true }).click(); await page.getByLabel('Supplier name').fill('QA short screen'); await page.getByRole('button', { name: 'Review', exact: true }).click(); await fits(page); await page.screenshot({ path: 'test-results/relationships-visual/short-review.png' }); await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(1); await expect(page.getByRole('heading', { name: 'Discard unsaved changes?' })).toBeVisible(); await fits(page); await page.getByRole('button', { name: 'Keep editing' }).click(); await fits(page);
});
