import { useId,useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { client } from '../../api/client';
import { Input } from '../../components/ui/Input';
import { getErrorMessage } from '../../api/errors';
import { weekdays,type Context,type LeaveType,type Holiday,type Template,type Leave,type Shift,type Availability } from './contracts';
export function ErrorNotice({error}:{error:unknown}){return error?<p role="alert" className="error-text">{getErrorMessage(error,'HR command failed safely; reload to resolve conflicts.')}</p>:null;}
function Select({label,value,onChange,children}:{label:string;value:string;onChange:(v:string)=>void;children:React.ReactNode}){const id=useId();return <div className="field"><label htmlFor={id}>{label}</label><select id={id} required className="min-w-0 max-w-full" value={value} onChange={e=>onChange(e.target.value)}>{children}</select></div>;}
function Check({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-center gap-3"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/>{label}</label>;}
export function ConfigurationForm({kind,context,editing,done}:{kind:'type'|'calendar'|'holiday'|'template';context:Context;editing?:LeaveType|Holiday|Template;done:()=>Promise<void>}){
 const type=kind==='type'?editing as LeaveType|undefined:undefined,holiday=kind==='holiday'?editing as Holiday|undefined:undefined,template=kind==='template'?editing as Template|undefined:undefined;
 const [name,setName]=useState(editing?.name??(kind==='calendar'?context.calendar?.name??'':'')),[description,setDescription]=useState(type?.description??''),[status,setStatus]=useState(editing?.status??'active'),[reason,setReason]=useState(type?.requires_reason??false),[past,setPast]=useState(type?.allow_past??false),[notice,setNotice]=useState(String(type?.minimum_notice_days??0)),[countOff,setCountOff]=useState(type?.count_non_working??false),[days,setDays]=useState(context.calendar?.working_days??[1,2,3,4,5]),[day,setDay]=useState(holiday?.day??''),[off,setOff]=useState(holiday?.non_working??true),[start,setStart]=useState(template?.start_time.slice(0,5)??''),[end,setEnd]=useState(template?.end_time.slice(0,5)??''),[overnight,setOvernight]=useState(template?.overnight??false),[breakMinutes,setBreak]=useState(String(template?.break_minutes??0));
 const save=useMutation({mutationFn:()=>{
  const expectedVersion=editing?.version??(kind==='calendar'?context.calendar?.version:undefined),version=expectedVersion?{expectedVersion}:{};
  const path=kind==='type'?'/hr/types':kind==='calendar'?'/hr/calendar':kind==='holiday'?'/hr/holidays':'/hr/templates';
  const value=kind==='type'?{name,description,status,requiresReason:reason,allowPast:past,minimumNoticeDays:Number(notice),countNonWorking:countOff}:kind==='calendar'?{name,workingDays:days}:kind==='holiday'?{name,day,nonWorking:off,status}:{name,startTime:start,endTime:end,overnight,breakMinutes:Number(breakMinutes),status};
  return client[kind==='calendar'?'put':editing?'patch':'post'](path+(editing?'/'+editing.id:''),{...value,...version});
 },onSuccess:done});
 return <form className="page-stack" onSubmit={e=>{e.preventDefault();save.mutate();}}><Input label="Name" value={name} onChange={e=>setName(e.target.value)} required maxLength={100}/>{kind!=='calendar'&&<Select label="Status" value={status} onChange={v=>setStatus(v as 'active'|'archived')}><option value="active">Active</option><option value="archived">Archived (history retained)</option></Select>}
 {kind==='type'&&<><Input label="Description (not medical details)" value={description} onChange={e=>setDescription(e.target.value)} maxLength={500}/><Check label="Reason required" value={reason} onChange={setReason}/><Check label="Past-dated requests allowed" value={past} onChange={setPast}/><Input label="Minimum advance notice (calendar days)" type="number" min={0} max={365} step={1} value={notice} onChange={e=>setNotice(e.target.value)}/><Check label="Count non-working days" value={countOff} onChange={setCountOff}/><p>Whole-day leave always requires a different authorized reviewer. No balance, accrual, payroll or legal entitlement is implied.</p></>}
 {kind==='calendar'&&<><p>Edit this suggested working week to match your business. Weekdays use {context.timezone}; no holiday feed is assumed.</p><fieldset><legend>Working weekdays</legend><div className="page-stack">{weekdays.map((label,index)=><Check key={label} label={label} value={days.includes(index)} onChange={checked=>setDays(old=>checked?[...old,index]:old.filter(d=>d!==index))}/>)}</div></fieldset></>}
 {kind==='holiday'&&<><Input label="Calendar date" type="date" required value={day} onChange={e=>setDay(e.target.value)}/><Check label="Non-working day" value={off} onChange={setOff}/><p>An active entry overrides the weekly pattern on this date only. Archive retains the record.</p></>}
 {kind==='template'&&<><Input label="Local start time" type="time" required value={start} onChange={e=>setStart(e.target.value)}/><Input label="Local end time" type="time" required value={end} onChange={e=>setEnd(e.target.value)}/><Check label="Ends on the following day (overnight)" value={overnight} onChange={setOvernight}/><Input label="Planned break minutes" type="number" min={0} max={720} step={1} required value={breakMinutes} onChange={e=>setBreak(e.target.value)}/><p>Templates describe expected work, never actual Attendance. Ambiguous/nonexistent DST times are rejected.</p></>}
 <ErrorNotice error={save.error}/><button className="action-link" disabled={save.isPending||(kind==='calendar'&&!days.length)}>{save.isPending?'Saving…':'Save configuration'}</button></form>;
}
// Sensitive commands retain their exact payload/key after an uncertain response.
// A retry cannot silently change the confirmed business intent.
export function LeaveForm({context,done}:{context:Context;done:()=>Promise<void>}){
 const [type,setType]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[reason,setReason]=useState(''),[prepared,setPrepared]=useState<Record<string,unknown>|null>(null),[reviewing,setReviewing]=useState(false);
 const selected=context.types.find(t=>t.id===type),save=useMutation({mutationFn:(value:Record<string,unknown>)=>client.post('/hr/me/leave',value),onSuccess:done});
 return <form className="page-stack" onSubmit={e=>{e.preventDefault();if(!reviewing){setReviewing(true);return;}const value=prepared??{leaveTypeId:type,startDate:start,endDate:end,reason,idempotencyKey:crypto.randomUUID()};setPrepared(value);save.mutate(value);}}>
 {!reviewing?<><Select label="Leave type" value={type} onChange={setType}><option value="">Select an active leave type</option>{context.types.filter(t=>t.status==='active').map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</Select><Input label="Leave starts" type="date" required value={start} onChange={e=>setStart(e.target.value)}/><Input label="Leave ends" type="date" required min={start} value={end} onChange={e=>setEnd(e.target.value)}/><label className="field">Reason (avoid unnecessary medical information)<textarea maxLength={2000} required={selected?.requires_reason} value={reason} onChange={e=>setReason(e.target.value)}/></label>{selected&&<p>{selected.count_non_working?'All calendar days count.':'Working days in the selected branch calendar count.'} Leave applies to your organization membership across all assigned branches. Advance notice: {selected.minimum_notice_days} calendar days. {selected.allow_past?'Past-dated requests permitted.':'Past-dated requests prohibited.'}</p>}</>:<section className="panel page-stack"><h3>Confirm leave request</h3><p>{selected?.name} · {start} to {end}</p><p>Approval is not automatic and creates no Attendance mark. This request blocks overlapping pending/approved leave across your organization membership.</p><p>Your reason is restricted to you and authorized reviewers; it is not exported or copied into notifications.</p></section>}
 <ErrorNotice error={save.error}/>{reviewing&&!prepared&&<button className="quiet-button" type="button" onClick={()=>setReviewing(false)}>Change request</button>}<button className="action-link" disabled={save.isPending||!type||!start||!end}>{save.isPending?'Submitting…':prepared?'Retry same confirmed request':reviewing?'Confirm submission':'Review request'}</button></form>;
}
export function ScheduleForm({context,staff,shift,done}:{context:Context;staff:Availability[];shift?:Shift;done:()=>Promise<void>}){
 const [member,setMember]=useState(shift?.membership_id??''),[template,setTemplate]=useState(shift?.template_id??''),[from,setFrom]=useState(shift?.business_date??''),[to,setTo]=useState(''),[working,setWorking]=useState(true),[prepared,setPrepared]=useState<Record<string,unknown>|null>(null);
 const save=useMutation({mutationFn:(v:Record<string,unknown>)=>shift?client.patch('/hr/shifts/'+shift.id,v):client.post('/hr/shifts',v),onSuccess:done});
 return <form className="page-stack" onSubmit={e=>{e.preventDefault();const value=prepared??(shift?{templateId:template,day:from,expectedVersion:shift.version}:{membershipId:member,templateId:template,from,to:to||from,workingDaysOnly:working,idempotencyKey:crypto.randomUUID()});setPrepared(value);save.mutate(value);}}><p>Drafts reserve expected work time across branches. Publication is a separate action. Maximum 31 calendar days; one employee per atomic batch.</p><fieldset disabled={save.isPending||Boolean(prepared)} className="page-stack">{!shift&&<Select label="Employee" value={member} onChange={setMember}><option value="">Select active branch employee</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select>}<Select label="Shift template" value={template} onChange={setTemplate}><option value="">Select active template</option>{context.templates.filter(t=>t.status==='active').map(t=><option key={t.id} value={t.id}>{t.name} ({t.start_time.slice(0,5)}–{t.end_time.slice(0,5)}{t.overnight?' next day':''})</option>)}</Select><Input label="Schedule starts on" type="date" required value={from} onChange={e=>setFrom(e.target.value)}/>{!shift&&<><Input label="Repeat through (optional; at most 31 days)" type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/><Check label="Working days only" value={working} onChange={setWorking}/></>}</fieldset><ErrorNotice error={save.error}/><button className="action-link" disabled={save.isPending||!member||!template||!from}>{save.isPending?'Saving…':prepared?'Retry unchanged command':shift?'Save draft shift':'Create draft schedule'}</button></form>;
}
export function TransitionForm({leave,shift,action,self,done}:{leave?:Leave;shift?:Shift;action:string;self?:boolean;done:()=>Promise<void>}){
 const [note,setNote]=useState(''),[prepared,setPrepared]=useState<Record<string,unknown>|null>(null),record=leave??shift!;
 const save=useMutation({mutationFn:(v:Record<string,unknown>)=>client.post(leave?'/hr/'+(self?'me/leave/'+leave.id+'/cancel':'leave/'+leave.id+'/review'):'/hr/shifts/'+shift!.id+'/status',v),onSuccess:done});
 return <form className="page-stack" onSubmit={e=>{e.preventDefault();const value=prepared??{expectedVersion:record.version,idempotencyKey:crypto.randomUUID(),...(!self?{status:action,...(leave?{note}:{})}:{})};setPrepared(value);save.mutate(value);}}><p>{leave?`${leave.employee} · ${leave.start_date} to ${leave.end_date}`:`${shift!.employee} · ${shift!.business_date}`}</p><p>Confirm {action}. Changes are versioned and retained. Conflicting approved leave or published shifts must be resolved explicitly; no Attendance record is changed.</p>{leave&&!self&&<label className="field">Reviewer note (private to authorized reviewers)<textarea maxLength={500} required={action!=='approved'} disabled={Boolean(prepared)} value={note} onChange={e=>setNote(e.target.value)}/></label>}<ErrorNotice error={save.error}/><button className="action-link" disabled={save.isPending}>{save.isPending?'Saving…':prepared?'Retry unchanged command':'Confirm '+action}</button></form>;
}
