import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery,useQueryClient } from '@tanstack/react-query';
import { useAppStore } from '../../store/useAppStore';
import { hasEntitlement } from '../../commercial/catalogue';
import { Input } from '../../components/ui/Input';
import { AdvancedModal } from '../../components/ui/AdvancedModal';
import { get,addDays,localTime,useHrAccess,weekdays,type Context,type Page,type Leave,type Shift,type Availability,type History,type LeaveType,type Holiday,type Template } from './contracts';
import { ConfigurationForm,LeaveForm,ScheduleForm,TransitionForm,ErrorNotice } from './forms';
type Editor={kind:'type'|'calendar'|'holiday'|'template';record?:LeaveType|Holiday|Template}|{kind:'request'}|{kind:'schedule';shift?:Shift}|{kind:'transition';action:string;leave?:Leave;shift?:Shift;self?:boolean}|{kind:'history';id:string;self:boolean};
export default function HrPage(){const {scope}=useHrAccess();return <Workspace key={JSON.stringify(scope)}/>;}
function Pager({page,total,change}:{page:number;total:number;change:(n:number)=>void}){return <div className="record-actions"><button className="quiet-button" disabled={page===1} onClick={()=>change(page-1)}>Previous</button><span>Page {page} of {Math.max(1,Math.ceil(total/20))}</span><button className="quiet-button" disabled={page*20>=total||page>=200} onClick={()=>change(page+1)}>Next</button></div>;}
function Workspace(){
 const access=useHrAccess(),cache=useQueryClient(),{user,entitlements}=useAppStore(),[tab,setTab]=useState(access.read?'Overview':'My Work'),[anchor,setAnchor]=useState(''),[span,setSpan]=useState(7),[page,setPage]=useState(1),[search,setSearch]=useState(''),[editor,setEditor]=useState<Editor|null>(null);
 const fallback=new Date().toISOString().slice(0,10),probe=useQuery({queryKey:['hr',...access.scope,'clock'],queryFn:()=>get<Context>('/hr/context',{from:fallback,to:fallback})}),from=anchor||probe.data?.businessDate||fallback,to=addDays(from,span-1),params={from,to,page,limit:20,search};
 const context=useQuery({queryKey:['hr',...access.scope,'context',from,to],enabled:Boolean(probe.data),queryFn:()=>get<Context>('/hr/context',{from,to})});
 const self=tab==='My Work',leave=useQuery({queryKey:['hr',...access.scope,'leave',self,params],enabled:self||access.read,queryFn:()=>get<Page<Leave>>('/hr/'+(self?'me/leave':'leave'),params)}),shifts=useQuery({queryKey:['hr',...access.scope,'shifts',self,params],enabled:self||access.read,queryFn:()=>get<Page<Shift>>('/hr/'+(self?'me/schedule':'shifts'),params)}),team=useQuery({queryKey:['hr',...access.scope,'team',params],enabled:access.read&&(tab==='Team Availability'||tab==='Overview'||editor?.kind==='schedule'),queryFn:()=>get<Page<Availability>&{calendarConfigured:boolean}>('/hr/availability',params)});
 const history=useQuery({queryKey:['hr',...access.scope,'history',editor?.kind==='history'?editor.id:null],enabled:editor?.kind==='history',queryFn:()=>editor?.kind==='history'?get<History>('/hr/'+(editor.self?'me/leave/'+editor.id+'/history':'history/'+editor.id)):Promise.reject(new Error('Select history'))});
 const done=async()=>{await Promise.all(['hr','dashboard','notifications','reports'].map(key=>cache.invalidateQueries({queryKey:[key]})));setEditor(null);};
 const choose=(t:string)=>{setTab(t);setPage(1);setSearch('');};
 const attendance=hasEntitlement(entitlements,'attendance')&&user?.permissions?.includes('attendance.read');
 return <div className="page-stack min-w-0"><header className="page-heading"><div><h1>HR Plus</h1><p>Leave, work calendars and expected shifts · {context.data?.timezone??'Resolving branch timezone…'}</p></div><div className="record-actions"><button className="action-link" onClick={()=>setEditor({kind:'request'})} disabled={!context.data?.types.some(t=>t.status==='active')}>Request leave</button>{attendance&&<Link className="quiet-button" to="/attendance">Recorded Attendance (separate)</Link>}</div></header>
 <p>Schedules and approved leave are not Attendance marks. No payroll, leave balance or legal-compliance claim.</p>
 <nav className="record-actions" aria-label="HR workspace">{['My Work',...(access.read?['Overview','Leave','Shifts','Team Availability']:[]),...(access.manage?['Work Calendar','Leave Types','Shift Templates']:[])].map(t=><button className={tab===t?'action-link':'quiet-button'} key={t} onClick={()=>choose(t)} aria-current={tab===t?'page':undefined}>{t}</button>)}</nav>
 <section className="panel"><div className="record-actions"><Input label="Window starts" type="date" value={from} onChange={e=>{setAnchor(e.target.value);setPage(1);}}/><button className="quiet-button" onClick={()=>{setSpan(1);setPage(1);}}>Daily view</button><button className="quiet-button" onClick={()=>{setSpan(7);setPage(1);}}>Weekly view</button><Input label="Search employee" value={search} maxLength={200} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div><p>{from} to {to} · Calendar dates stay in the branch context, not the device timezone.</p></section>
 {(probe.isPending||context.isPending)&&<p role="status">Loading HR context…</p>}{(probe.isError||context.isError)&&<><ErrorNotice error={probe.error??context.error}/><button className="quiet-button" onClick={()=>{void probe.refetch();void context.refetch();}}>Retry HR context</button></>}
 {tab==='Overview'&&<section className="panel page-stack"><h2>Selected-branch workforce overview</h2><p>The Dashboard has independently authorized HR counts. Team availability below distinguishes scheduled work, approved leave and non-working days; no shift is not absence.</p><Link className="action-link" to="/dashboard">Open factual Dashboard widgets</Link>{user?.permissions?.includes('reports.read')&&<Link className="action-link" to="/reports">Open HR reports and safe CSV</Link>}</section>}
 {['My Work','Leave','Overview'].includes(tab)&&<section className="page-stack"><h2>{self?'My Leave':'Leave requests'}</h2><p>Organization-membership leave applies across assigned branches. Working-day counts are frozen at submission; later calendar edits do not rewrite history.</p>{leave.isPending&&<p role="status">Loading leave…</p>}<ErrorNotice error={leave.error}/>{leave.isError&&<button className="quiet-button" onClick={()=>void leave.refetch()}>Retry leave</button>}{leave.data?.data.length===0&&<section className="panel">No leave requests overlap this window. {self?'Request leave when an active leave type is configured.':'Configure leave types or choose another window.'}</section>}{leave.data?.data.map(l=><article className="panel page-stack" key={l.id}><h3>{l.employee} · {l.type_name_snapshot}</h3><p>{l.start_date} to {l.end_date} · {l.counted_days} counted whole-request days · {l.status}</p>{l.reason&&<p className="whitespace-pre-wrap break-words">Private request reason: {l.reason}</p>}<div className="record-actions"><button className="quiet-button" onClick={()=>setEditor({kind:'history',id:l.id,self})}>View leave history</button>{self&&l.status==='pending'&&<button className="quiet-button" onClick={()=>setEditor({kind:'transition',leave:l,action:'cancelled',self:true})}>Cancel pending request</button>}{!self&&access.approve&&l.can_review&&l.status==='pending'&&<><button className="quiet-button" onClick={()=>setEditor({kind:'transition',leave:l,action:'approved'})}>Approve leave</button><button className="quiet-button" onClick={()=>setEditor({kind:'transition',leave:l,action:'rejected'})}>Reject leave</button></>}{!self&&access.approve&&l.can_review&&l.status==='approved'&&<button className="quiet-button" onClick={()=>setEditor({kind:'transition',leave:l,action:'cancelled'})}>Cancel approved leave</button>}</div></article>)}{leave.data&&<Pager page={page} total={leave.data.total} change={setPage}/>}</section>}
 {['My Work','Shifts'].includes(tab)&&<section className="page-stack"><div className="record-actions"><h2>{self?'My Schedule':'Branch shifts'}</h2>{!self&&access.manage&&<button className="action-link" onClick={()=>setEditor({kind:'schedule'})}>Create draft schedule</button>}</div><p>{self?'Only your published/cancelled shifts are visible.':'Drafts reserve time but remain private until published.'} Expected work is not hours actually worked.</p>{shifts.isPending&&<p role="status">Loading schedule…</p>}<ErrorNotice error={shifts.error}/>{shifts.isError&&<button className="quiet-button" onClick={()=>void shifts.refetch()}>Retry schedule</button>}{shifts.data?.data.length===0&&<section className="panel">No {self?'published':'recorded'} shifts in this window.</section>}{shifts.data?.data.map(s=><article className="panel page-stack" key={s.id}><h3>{s.employee} · {s.template_name_snapshot}</h3><p>{s.branch_name} · {s.business_date} · {s.status}</p><p>{localTime(s.starts_at,s.timezone_snapshot)} to {localTime(s.ends_at,s.timezone_snapshot)} ({s.timezone_snapshot}); planned break {s.break_minutes} minutes.</p>{!self&&access.manage&&<div className="record-actions">{s.status==='draft'&&<><button className="quiet-button" onClick={()=>setEditor({kind:'schedule',shift:s})}>Edit draft shift</button><button className="quiet-button" onClick={()=>setEditor({kind:'transition',shift:s,action:'published'})}>Publish shift</button></>}{s.status!=='cancelled'&&<button className="quiet-button" onClick={()=>setEditor({kind:'transition',shift:s,action:'cancelled'})}>Cancel shift</button>}<button className="quiet-button" onClick={()=>setEditor({kind:'history',id:s.id,self:false})}>View shift history</button></div>}</article>)}{shifts.data&&<Pager page={page} total={shifts.data.total} change={setPage}/>}</section>}
 {['Overview','Team Availability'].includes(tab)&&<section className="page-stack"><h2>Team availability</h2>{team.isPending&&<p role="status">Loading availability…</p>}<ErrorNotice error={team.error}/>{team.isError&&<button className="quiet-button" onClick={()=>void team.refetch()}>Retry availability</button>}{team.data&&!team.data.calendarConfigured&&<p>Work calendar is not configured; non-working days are not inferred.</p>}{team.data?.data.map(s=><article className="panel page-stack" key={s.id}><h3>{s.name}</h3>{s.days.map(d=><p key={d.day}>{d.day} · {d.state}</p>)}</article>)}{team.data?.data.length===0&&<p>No active assigned employees match.</p>}{team.data&&<Pager page={page} total={team.data.total} change={setPage}/>}</section>}
 {context.data&&['Work Calendar','My Work'].includes(tab)&&<section className="panel page-stack"><h2>Branch work calendar</h2>{context.data.calendar?<><h3>{context.data.calendar.name}</h3><p>Working weekdays: {context.data.calendar.working_days.map(d=>weekdays[d]).join(', ')}</p></>:<p>No work calendar configured. An authorized manager must explicitly set it up.</p>}{tab==='Work Calendar'&&access.manage&&<div className="record-actions"><button className="quiet-button" onClick={()=>setEditor({kind:'calendar'})}>{context.data.calendar?'Edit working week':'Configure working week'}</button><button className="quiet-button" disabled={!context.data.calendar} onClick={()=>setEditor({kind:'holiday'})}>Add calendar day</button></div>}{context.data.days.length===0&&<p>No manually configured calendar days in this window.</p>}{context.data.days.map(d=><div key={d.id}><p>{d.day} · {d.name} · {d.non_working?'Non-working':'Working'} · {d.status}</p>{tab==='Work Calendar'&&access.manage&&<button className="quiet-button" onClick={()=>setEditor({kind:'holiday',record:d})}>Edit calendar day</button>}</div>)}</section>}
 {context.data&&tab==='Leave Types'&&<section className="page-stack"><h2>Leave types and basic policies</h2><button className="action-link" onClick={()=>setEditor({kind:'type'})}>Add leave type</button>{context.data.types.length===0&&<p>No leave types. Add an explicit policy; no statutory entitlement is assumed.</p>}{context.data.types.map(t=><article className="panel page-stack" key={t.id}><h3>{t.name}</h3><p>{t.description} · {t.status} · Always requires approval by another authorized member.</p><button className="quiet-button" onClick={()=>setEditor({kind:'type',record:t})}>Edit leave type</button></article>)}</section>}
 {context.data&&tab==='Shift Templates'&&<section className="page-stack"><h2>Shift templates</h2><button className="action-link" onClick={()=>setEditor({kind:'template'})}>Add shift template</button>{context.data.templates.length===0&&<p>No templates. Configure expected local working times.</p>}{context.data.templates.map(t=><article className="panel page-stack" key={t.id}><h3>{t.name}</h3><p>{t.start_time.slice(0,5)}–{t.end_time.slice(0,5)}{t.overnight?' next day':''} · {t.status}</p><button className="quiet-button" onClick={()=>setEditor({kind:'template',record:t})}>Edit shift template</button></article>)}</section>}
 <AdvancedModal isOpen={Boolean(editor)} onClose={()=>setEditor(null)} title={editor?.kind==='request'?'Request Leave':editor?.kind==='schedule'?'Draft Shift Schedule':editor?.kind==='transition'?'Confirm HR change':editor?.kind==='history'?'HR history':'HR configuration'}>{context.data&&editor&&(['type','calendar','holiday','template'].includes(editor.kind)?<ConfigurationForm kind={(editor as Extract<Editor,{record?:LeaveType|Holiday|Template}>).kind} editing={(editor as Extract<Editor,{record?:LeaveType|Holiday|Template}>).record} context={context.data} done={done}/>:editor.kind==='request'?<LeaveForm context={context.data} done={done}/>:editor.kind==='schedule'?<><p>Choose an employee from the current authorized roster page. Search or paginate Team Availability to find another employee.</p>{team.isPending&&<p role="status">Loading active employees…</p>}<ErrorNotice error={team.error}/><ScheduleForm context={context.data} staff={team.data?.data??[]} shift={editor.shift} done={done}/></>:editor.kind==='transition'?<TransitionForm leave={editor.leave} shift={editor.shift} action={editor.action} self={editor.self} done={done}/>:editor.kind==='history'?<section className="page-stack">{history.isPending&&<p role="status">Loading history…</p>}<ErrorNotice error={history.error}/>{history.data?.events.map((e,i)=><p key={i}>{e.action} · version {e.resulting_version} · {e.actor} · {new Date(e.occurred_at).toLocaleString()}</p>)}{history.data?.decisions.map((d,i)=><p key={i}>Private reviewer note · {d.status} · {d.actor}: {d.note??'No note'}</p>)}</section>:null)}</AdvancedModal>
 </div>;
}
