import { signedEffectSql } from '../customerDues/repository.js';
import { itemSelect,itemJoins } from '../inventory/repository.js';
import type { ReportKey } from './policy.js';
export interface Source { sql:string;columns:{key:string;label:string;format?:'money'}[];date:string|null;statuses:readonly string[];filters:readonly string[];scope:'organization'|'branch' }
const cols=(...pairs:string[])=>pairs.map(pair=>{const [key,label]=pair.split(':');return {key:key!,label:label!};});
// Only repository-owned SQL enters this catalogue. Caller values are parameters.
export const sources:Record<ReportKey,Source>={
 'purchase-orders':{sql:`SELECT o.id,o.human_reference AS reference,s.name,o.status,o.order_date::text,o.expected_delivery_date::text,(o.order_date::timestamp AT TIME ZONE b.timezone) AS ordered_date,(SELECT sum(line_amount_minor)::text FROM purchase_order_lines WHERE purchase_order_id=o.id) AS ordered_minor,(SELECT count(*)::text FROM purchase_receipts WHERE purchase_order_id=o.id) AS receipts FROM purchase_orders o JOIN suppliers s ON s.id=o.supplier_id AND s.organization_id=o.organization_id JOIN branches b ON b.id=o.branch_id AND b.organization_id=o.organization_id WHERE o.organization_id=$1 AND o.branch_id=$2`,columns:[...cols('reference:PO reference','name:Supplier','status:Status','order_date:Ordered date','expected_delivery_date:Expected date','receipts:Receipt count'),{key:'ordered_minor',label:'Ordered value (INR; not paid)',format:'money'}],date:'ordered_date',statuses:['draft','ordered','partially_received','received','cancelled'],filters:['search','status'],scope:'branch'},
 'goods-received':{sql:`SELECT l.id,r.human_reference AS reference,o.human_reference AS order_reference,s.name,p.item_name_snapshot AS item,p.unit_code_snapshot AS unit,l.quantity::text,r.received_at,u.name AS actor FROM purchase_receipt_lines l JOIN purchase_receipts r ON r.id=l.purchase_receipt_id JOIN purchase_orders o ON o.id=l.purchase_order_id JOIN purchase_order_lines p ON p.id=l.purchase_order_line_id JOIN suppliers s ON s.id=o.supplier_id JOIN users u ON u.id=r.created_by WHERE l.organization_id=$1 AND l.branch_id=$2`,columns:cols('reference:Receipt','order_reference:Purchase Order','name:Supplier','item:Item','quantity:Received quantity','unit:Unit','received_at:Received','actor:Actor'),date:'received_at',statuses:[],filters:['search'],scope:'branch'},
 'supplier-purchases':{sql:`SELECT s.id::text||':'||o.order_date::text AS id,s.name,o.order_date::text,(o.order_date::timestamp AT TIME ZONE b.timezone) AS ordered_date,count(*)::text AS orders,sum(t.amount)::text AS ordered_minor FROM purchase_orders o JOIN suppliers s ON s.id=o.supplier_id JOIN branches b ON b.id=o.branch_id JOIN LATERAL(SELECT sum(line_amount_minor) AS amount FROM purchase_order_lines WHERE purchase_order_id=o.id) t ON true WHERE o.organization_id=$1 AND o.branch_id=$2 AND o.status IN ('ordered','partially_received','received') GROUP BY s.id,o.order_date,b.timezone`,columns:[...cols('name:Supplier','order_date:Business date','orders:Ordered documents'),{key:'ordered_minor',label:'Ordered value (INR; not paid)',format:'money'}],date:'ordered_date',statuses:[],filters:['search'],scope:'branch'},
 'crm-leads':{sql:`SELECT l.id,l.name,l.company,l.phone,l.email,l.source,s.name AS stage,u.name AS staff,l.assigned_membership_id AS staff_id,l.status,l.created_at FROM crm_leads l JOIN crm_pipeline_stages s ON s.id=l.pipeline_stage_id AND s.organization_id=l.organization_id LEFT JOIN memberships m ON m.id=l.assigned_membership_id AND m.organization_id=l.organization_id LEFT JOIN users u ON u.id=m.user_id WHERE l.organization_id=$1 AND l.branch_id=$2`,columns:cols('name:Lead','company:Company','phone:Phone','email:Email','source:Source','stage:Stage','staff:Assigned staff','status:Status','created_at:Created'),date:'created_at',statuses:['active','converted','lost','archived'],filters:['search','status','staffId','custom'],scope:'branch'},
 'crm-followups':{sql:`SELECT f.id,l.name,u.name AS staff,f.assigned_membership_id AS staff_id,f.type,f.subject,f.status,f.due_at,f.completed_at FROM crm_follow_ups f JOIN crm_leads l ON l.id=f.lead_id AND l.organization_id=f.organization_id AND l.branch_id=f.branch_id LEFT JOIN memberships m ON m.id=f.assigned_membership_id AND m.organization_id=f.organization_id LEFT JOIN users u ON u.id=m.user_id WHERE f.organization_id=$1 AND f.branch_id=$2`,columns:cols('name:Lead','staff:Assigned staff','type:Type','subject:Subject','status:Status','due_at:Due','completed_at:Completed'),date:'due_at',statuses:['pending','completed','cancelled'],filters:['search','status','staffId'],scope:'branch'},
 customers:{sql:`SELECT id,name,display_phone AS phone,status,notes,created_at FROM customers WHERE organization_id=$1 AND status<>'merged'`,columns:cols('name:Customer','phone:Phone','status:Status','notes:Notes','created_at:Created'),date:'created_at',statuses:['active','inactive'],filters:['search','status','custom'],scope:'organization'},
 services:{sql:`SELECT s.id,s.name,s.description,s.duration_minutes,CASE WHEN s.active THEN 'active' ELSE 'inactive' END AS status,s.created_at FROM services s JOIN service_branch_availability a ON a.service_id=s.id AND a.organization_id=s.organization_id AND a.branch_id=$2 AND a.active WHERE s.organization_id=$1`,columns:cols('name:Service','description:Description','duration_minutes:Duration (minutes)','status:Status','created_at:Created'),date:'created_at',statuses:['active','inactive'],filters:['search','status'],scope:'branch'},
 appointments:{sql:`SELECT a.id,c.name AS name,s.name AS service,u.name AS staff,a.customer_id,a.service_id,a.provider_membership_id AS staff_id,a.status,a.starts_at,a.ends_at FROM appointments a JOIN customers c ON c.id=a.customer_id AND c.organization_id=a.organization_id JOIN services s ON s.id=a.service_id AND s.organization_id=a.organization_id LEFT JOIN memberships m ON m.id=a.provider_membership_id AND m.organization_id=a.organization_id LEFT JOIN users u ON u.id=m.user_id WHERE a.organization_id=$1 AND a.branch_id=$2`,columns:cols('name:Customer','service:Service','staff:Provider','status:Status','starts_at:Starts','ends_at:Ends'),date:'starts_at',statuses:['scheduled','confirmed','checked_in','completed','cancelled','no_show'],filters:['search','status','customerId','serviceId','staffId'],scope:'branch'},
 queue:{sql:`SELECT t.id,c.name AS name,s.name AS service,u.name AS staff,t.customer_id,t.service_id,t.provider_membership_id AS staff_id,t.token_number,t.status,t.created_at FROM queue_tokens t JOIN customers c ON c.id=t.customer_id AND c.organization_id=t.organization_id JOIN services s ON s.id=t.service_id AND s.organization_id=t.organization_id LEFT JOIN memberships m ON m.id=t.provider_membership_id AND m.organization_id=t.organization_id LEFT JOIN users u ON u.id=m.user_id WHERE t.organization_id=$1 AND t.branch_id=$2`,columns:cols('token_number:Token','name:Customer','service:Service','staff:Provider','status:Status','created_at:Created'),date:'created_at',statuses:['waiting','serving','completed','cancelled'],filters:['search','status','customerId','serviceId','staffId'],scope:'branch'},
 attendance:{sql:`SELECT a.id,u.name,a.membership_id AS staff_id,a.status,a.attendance_date,a.check_in_at,a.check_out_at FROM attendance_records a JOIN memberships m ON m.id=a.membership_id AND m.organization_id=a.organization_id JOIN users u ON u.id=m.user_id WHERE a.organization_id=$1 AND a.branch_id=$2`,columns:cols('name:Staff','attendance_date:Business date','status:Status','check_in_at:Check in','check_out_at:Check out'),date:'attendance_date',statuses:['present','absent','half_day'],filters:['search','status','staffId'],scope:'branch'},
 'dues-balances':{sql:`SELECT c.id,c.name,c.id AS customer_id,COALESCE(sum(${signedEffectSql()}),0)::text AS balance_minor FROM customers c JOIN customer_due_entries e ON e.customer_id=c.id AND e.organization_id=c.organization_id AND e.branch_id=$2 LEFT JOIN customer_due_entries target ON target.id=e.reverses_entry_id AND target.organization_id=e.organization_id WHERE c.organization_id=$1 GROUP BY c.id`,columns:[...cols('name:Customer'),{key:'balance_minor',label:'Branch balance (INR)',format:'money'}],date:null,statuses:[],filters:['search','customerId'],scope:'branch'},
 'dues-journal':{sql:`SELECT e.id,c.name,e.customer_id,e.entry_type, e.amount_minor::text,(${signedEffectSql()})::text AS effect_minor,e.occurred_at,e.due_date::text FROM customer_due_entries e JOIN customers c ON c.id=e.customer_id AND c.organization_id=e.organization_id LEFT JOIN customer_due_entries target ON target.id=e.reverses_entry_id AND target.organization_id=e.organization_id WHERE e.organization_id=$1 AND e.branch_id=$2`,columns:[...cols('name:Customer','entry_type:Entry type','occurred_at:Occurred','due_date:Due date'),{key:'amount_minor',label:'Magnitude (INR)',format:'money'},{key:'effect_minor',label:'Signed balance effect (INR)',format:'money'}],date:'occurred_at',statuses:[],filters:['search','customerId','entryType'],scope:'branch'},
 inventory:{sql:`SELECT ${itemSelect} FROM inventory_items i ${itemJoins} WHERE i.organization_id=$1`,columns:[...cols('name:Item','sku:SKU','unit_code:Unit','status:Status','quantity:Stock','reorder_threshold:Reorder threshold'),{key:'price_minor',label:'Reference price (INR)',format:'money'}],date:null,statuses:['active','inactive'],filters:['search','status','stockStatus'],scope:'branch'},
 'stock-movements':{sql:`SELECT m.id,i.name,i.unit_code,m.movement_type AS entry_type,m.quantity_delta,m.occurred_at FROM stock_movements m JOIN inventory_items i ON i.id=m.item_id AND i.organization_id=m.organization_id WHERE m.organization_id=$1 AND m.branch_id=$2`,columns:cols('name:Item','unit_code:Unit','entry_type:Movement type','quantity_delta:Signed quantity','occurred_at:Occurred'),date:'occurred_at',statuses:[],filters:['search','entryType'],scope:'branch'},
 staff:{sql:`SELECT m.id,u.name,COALESCE(r.name,m.role) AS role,m.status,m.created_at,ARRAY(SELECT b.name FROM membership_branch_assignments a JOIN branches b ON b.id=a.branch_id AND b.organization_id=a.organization_id WHERE a.membership_id=m.id ORDER BY b.code) AS branches FROM memberships m JOIN users u ON u.id=m.user_id LEFT JOIN organization_roles r ON r.id=m.custom_role_id AND r.organization_id=m.organization_id WHERE m.organization_id=$1`,columns:cols('name:Staff','role:Role','status:Membership status','branches:Assigned branches','created_at:Joined'),date:'created_at',statuses:['active','inactive','revoked'],filters:['search','status'],scope:'organization'},
};
