import type { PoolClient } from 'pg';
// Transactional, closed generic templates. No employee name, leave type/reason,
// internal review note, date, identifier or caller-selected recipient in payloads.
export async function notifyHr(client:PoolClient,org:string,branch:string,subject:string,event:'leave.submitted'|'leave.approved'|'leave.rejected'|'shift.published'|'shift.cancelled',target:string,version:number){
 const rows=(await client.query(`SELECT m.id,m.user_id FROM memberships m LEFT JOIN organization_roles r ON r.id=m.custom_role_id AND r.organization_id=m.organization_id LEFT JOIN notification_preferences p ON p.organization_id=m.organization_id AND p.user_id=m.user_id WHERE m.organization_id=$1 AND m.status='active' AND COALESCE(p.hr_updates,true) AND ${event==='leave.submitted'?"m.id<>$2 AND (m.role='owner' OR (m.custom_role_id IS NULL AND m.role IN ('admin','hr')) OR (r.status='active' AND EXISTS(SELECT 1 FROM organization_role_permissions p WHERE p.role_id=r.id AND p.permission='hr_plus.approve'))) AND NOT EXISTS(SELECT 1 FROM membership_branch_assignments s JOIN branches b ON b.id=s.branch_id AND b.organization_id=s.organization_id WHERE s.membership_id=$2 AND s.organization_id=$1 AND b.status='active' AND NOT EXISTS(SELECT 1 FROM membership_branch_assignments a WHERE a.membership_id=m.id AND a.organization_id=$1 AND a.branch_id=s.branch_id))":"m.id=$2"} AND EXISTS(SELECT 1 FROM membership_branch_assignments a JOIN branches b ON b.id=a.branch_id AND b.organization_id=a.organization_id WHERE a.membership_id=m.id AND a.organization_id=$1 AND b.status='active') LIMIT 101`,[org,subject])).rows;
 if(rows.length>100)throw new Error('HR notification recipient budget exceeded');
 const message=event==='leave.submitted'?'A leave request is awaiting authorized review.':event==='leave.approved'?'Your leave request was approved.':event==='leave.rejected'?'Your leave request was rejected.':event==='shift.published'?'Your work schedule was published.':'A published shift was cancelled.';
 await client.query("INSERT INTO user_notifications(organization_id,membership_id,user_id,branch_id,category,event_key,title,message,action_key,dedupe_key) SELECT $1,m.id,m.user_id,$3,'hr',$4,'HR Plus update',$5,'hr',$6 FROM memberships m WHERE m.organization_id=$1 AND m.id=ANY($2::uuid[]) ON CONFLICT(organization_id,user_id,dedupe_key) DO NOTHING",[org,rows.map(r=>r.id),event==='leave.submitted'?null:branch,event,message,event+':'+target+':'+version]);
}
