import { useState } from 'react';
import { useMutation,useQuery } from '@tanstack/react-query';
import { client } from '../../api/client';
import { Input } from '../../components/ui/Input';
import { exactRupees } from '../../components/analytics/contracts';
import { paiseToRupees } from '../../utils/money';
import type { InventoryItem,Paginated } from '../../hooks/useInventory';
import { businessDate,get,previewLine,validReceiptQuantity,usePurchasingAccess,type Order,type Page,type Supplier } from './contracts';
import { LoadError,Pager } from './shared';
import { OperationForm } from '../../components/ui/OperationForm';
import { uncertainWrite } from '../../utils/mutationOutcome';
interface DraftLine {itemId:string;quantity:string;unitPrice:string;name:string;unit:string;sku?:string|null}
export function OrderEditor({order,done,close}:{order:Order|null;done:()=>Promise<void>;close:()=>void}){
 const {scope}=usePurchasingAccess(),[supplierSearch,setSupplierSearch]=useState(''),[supplierPage,setSupplierPage]=useState(1),[itemSearch,setItemSearch]=useState(''),[itemPage,setItemPage]=useState(1);
 const [supplierId,setSupplierId]=useState(order?.supplier_id??''),[orderDate,setOrderDate]=useState(businessDate(order?.order_date)==='Not set'?'':businessDate(order?.order_date)),[delivery,setDelivery]=useState(order?.expected_delivery_date?businessDate(order.expected_delivery_date):''),[notes,setNotes]=useState(order?.notes??'');
 const [selectedItem,setSelectedItem]=useState(''),[supplierName,setSupplierName]=useState(order?.supplier_name??'');
 const [lines,setLines]=useState<DraftLine[]>(order?.lines?.map(l=>({itemId:l.inventory_item_id,quantity:l.ordered_quantity,unitPrice:paiseToRupees(l.unit_price_minor),name:l.item_name_snapshot,unit:l.unit_code_snapshot,sku:l.sku_snapshot}))??[]);
 const [initial]=useState(()=>JSON.stringify({supplierId,orderDate,delivery,notes,lines}));
 const suppliers=useQuery({queryKey:['purchasing',...scope,'supplier-choices',supplierSearch,supplierPage],queryFn:({signal})=>get<Page<Supplier>>('/suppliers',{status:'active',search:supplierSearch,page:supplierPage,limit:20},signal)});
 const items=useQuery({queryKey:['purchasing',...scope,'item-choices',itemSearch,itemPage],queryFn:async({signal})=>(await client.get<Paginated<InventoryItem>>('/inventory',{signal,params:{status:'active',search:itemSearch,page:itemPage,limit:20}})).data});
 const amounts=lines.map(l=>previewLine(l.quantity,l.unitPrice)),total=amounts.every(v=>v!==null)?amounts.reduce<bigint>((n,v)=>n+(v??0n),0n):null;
 const valid=Boolean(supplierId&&orderDate&&(!delivery||delivery>=orderDate)&&lines.length&&total!==null&&total<=9223372036854775807n);
 const save=useMutation({mutationFn:()=>client[order?'patch':'post']('/purchasing/orders'+(order?'/'+order.id:''),{supplierId,orderDate,expectedDeliveryDate:delivery||null,notes:notes||null,currency:'INR',lines:lines.map(({itemId,quantity,unitPrice})=>({itemId,quantity,unitPrice})),...(order?{expectedVersion:order.version}:{})}),onSuccess:done});
 const change=(index:number,key:'quantity'|'unitPrice',value:string)=>setLines(old=>old.map((l,i)=>i===index?{...l,[key]:value}:l));
 return <OperationForm open title={order?'Edit draft Purchase Order':'Create Purchase Order'} onClose={close} dirty={JSON.stringify({supplierId,orderDate,delivery,notes,lines})!==initial} valid={valid&&!uncertainWrite(save.error)} busy={save.isPending} error={save.error} confirmLabel="Save draft" onConfirm={()=>save.mutate()} retryAdvice="A new draft has no idempotent retry contract. Check Purchasing before resubmitting after an uncertain response." review={<section className="page-stack"><h3>{supplierName||order?.supplier_name||'Chosen supplier'}</h3><p>Order date: {orderDate} · Expected: {delivery||'Not set'}</p>{lines.map((l,i)=><article className="panel" key={l.itemId}><h4>{l.name}</h4><p>{l.quantity} {l.unit} × {l.unitPrice} INR · {exactRupees(String(amounts[i]??0n))}</p></article>)}<p>Ordered purchase value: {total===null?'Check amounts':exactRupees(String(total))}</p><p>{notes||'No notes'}</p><p>Save as Draft. No stock, invoice, payment or tax accounting is recorded.</p></section>}><div className="page-stack">
  <p>Drafts do not add stock. Agreed unit prices are separate purchasing snapshots, not item prices or payments.</p>
  <section className="detail-section"><h3>1. Supplier</h3><Input label="Search active suppliers" type="search" maxLength={200} value={supplierSearch} onChange={e=>{setSupplierSearch(e.target.value);setSupplierPage(1);}}/>
  {suppliers.isError?<LoadError error={suppliers.error} retry={()=>void suppliers.refetch()}/>:<label className="field">Order supplier<select required value={supplierId} onChange={e=>{setSupplierId(e.target.value);setSupplierName(suppliers.data?.data.find(s=>s.id===e.target.value)?.name??'');}}><option value="">Select an active supplier</option>{supplierId&&!suppliers.data?.data.some(s=>s.id===supplierId)&&<option value={supplierId}>{supplierName||order?.supplier_name} — selected, active status checked on save</option>}{suppliers.data?.data.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label>}
  {suppliers.data&&<Pager page={supplierPage} total={suppliers.data.total} onChange={setSupplierPage}/>}
  </section><section className="detail-section"><h3>2. Order details</h3><Input label="Order date" type="date" required min="1900-01-01" max="9998-12-31" value={orderDate} onChange={e=>setOrderDate(e.target.value)}/><Input label="Expected delivery date (optional)" type="date" min={orderDate||'1900-01-01'} max="9998-12-31" value={delivery} onChange={e=>setDelivery(e.target.value)}/>
  </section><section className="detail-section page-stack"><h3>3. Canonical Inventory items</h3><Input label="Search Inventory items" type="search" maxLength={200} value={itemSearch} onChange={e=>{setItemSearch(e.target.value);setItemPage(1);setSelectedItem('');}}/>{items.isPending?<p>Loading items…</p>:items.isError?<LoadError error={items.error} retry={()=>void items.refetch()}/>:items.data&&<><label className="field">Choose Inventory item<select value={selectedItem} onChange={e=>setSelectedItem(e.target.value)}><option value="">Choose an item from this server page</option>{items.data.data.map(i=><option key={i.id} value={i.id} disabled={lines.some(l=>l.itemId===i.id)}>{i.name} · {i.sku||'No SKU'} · {i.unitCode}{lines.some(l=>l.itemId===i.id)?' · Added':''}</option>)}</select></label><button type="button" className="quiet-button" disabled={!selectedItem||lines.length>=50||lines.some(l=>l.itemId===selectedItem)} onClick={()=>{const i=items.data.data.find(i=>i.id===selectedItem);if(i){setLines(old=>old.some(l=>l.itemId===i.id)?old:[...old,{itemId:i.id,name:i.name,unit:i.unitCode,sku:i.sku,quantity:'',unitPrice:''}]);setSelectedItem('');}}}>Add selected item</button><p className="muted">Search is server-backed and paginated. Up to 50 unique items; selected lines stay below.</p>{!items.data.data.length&&<p>No active matching Inventory items. Create items in Inventory first.</p>}<Pager page={itemPage} total={items.data.total} onChange={n=>{setItemPage(n);setSelectedItem('');}}/></>}</section>
  <section className="page-stack" aria-label="Purchase order lines"><h3>4. Order lines ({lines.length}/50)</h3>{!lines.length&&<p>Select at least one Inventory item above.</p>}{lines.map((l,index)=><article className="panel page-stack" key={l.itemId}><h4 className="break-words">{l.name} · {l.unit}</h4><p className="break-words">SKU: {l.sku||'Not set'}</p><Input id={'ordered-quantity-'+l.itemId} label={'Ordered quantity — '+l.name} inputMode="decimal" maxLength={32} required value={l.quantity} onChange={e=>change(index,'quantity',e.target.value)}/><Input id={'order-price-'+l.itemId} label={'Agreed unit price INR — '+l.name} inputMode="decimal" maxLength={32} required value={l.unitPrice} onChange={e=>change(index,'unitPrice',e.target.value)}/><p>Line value: {amounts[index]===null?'Enter positive quantity (up to 3 decimals) and non-negative price (up to 2 decimals)':exactRupees(String(amounts[index]))}</p><button type="button" className="quiet-button" onClick={()=>setLines(old=>old.filter((_,i)=>i!==index))}>Remove {l.name}</button></article>)}</section>
  <h3>5. Review ordered value</h3><p className="font-semibold">Ordered purchase value: {total===null?'Check line amounts':exactRupees(String(total))}</p><p className="muted">Each exact quantity × price is rounded once to paise; a positive half-paise rounds up. This is not tax accounting or amount paid.</p><label className="field">Order notes (optional)<textarea maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label></div></OperationForm>;
}
export function ReceiveEditor({order,done,close}:{order:Order;done:()=>Promise<void>;close:()=>void}){
 const [quantities,setQuantities]=useState<Record<string,string>>({}),[notes,setNotes]=useState(''),[command,setCommand]=useState<{expectedVersion:number;idempotencyKey:string;notes:string|null;lines:{orderLineId:string;quantity:string}[]}|null>(null);
 const available=order.lines?.filter(l=>validReceiptQuantity(l.remaining_quantity,l.remaining_quantity))??[];
 const entered=available.filter(l=>Boolean(quantities[l.id]?.trim())),valid=entered.length>0&&entered.every(l=>validReceiptQuantity(quantities[l.id].trim(),l.remaining_quantity));
 const save=useMutation({mutationFn:(payload:NonNullable<typeof command>)=>client.post('/purchasing/orders/'+order.id+'/receive',payload),onSuccess:done});
 const uncertain=save.isError;
 const confirmed=()=>{const payload=command??{expectedVersion:order.version,idempotencyKey:crypto.randomUUID(),notes:notes||null,lines:entered.map(l=>({orderLineId:l.id,quantity:quantities[l.id].trim()}))};setCommand(payload);save.mutate(payload);};
 return <OperationForm open title="Receive Goods" reviewLabel="Review receipt" onClose={close} dirty={Boolean(command)||Object.values(quantities).some(q=>q.trim())||Boolean(notes)} valid={Boolean(command)||valid} busy={save.isPending} error={save.error} confirmLabel={uncertain?'Retry identical receipt':'Confirm Receive Goods'} onConfirm={confirmed} retryAdvice="Retry preserves the exact confirmed quantities, original version and original command key." review={<section className="panel page-stack" aria-label="Receipt confirmation"><h3>Confirm actual goods received</h3><p>{order.human_reference} · {order.supplier_name} · {order.branch_name}</p>{(command?.lines??entered.map(l=>({orderLineId:l.id,quantity:quantities[l.id].trim()}))).map(l=><p key={l.orderLineId}>{available.find(a=>a.id===l.orderLineId)?.item_name_snapshot} · {l.quantity} {available.find(a=>a.id===l.orderLineId)?.unit_code_snapshot}</p>)}<p>{command?.notes??notes??'No receiving notes'}</p><p>All listed lines commit together and increase canonical Inventory stock in this branch. This does not record a Supplier payment or change Inventory catalogue reference prices. Independent reversal is blocked; returns/corrections are deferred.</p></section>}><div className="page-stack">
 <h2>{order.human_reference}</h2><p>{order.supplier_name} · {order.branch_name}</p><p>Enter only quantities actually received. Blank lines are excluded; quantities never default to the full order.</p>
 {available.map(l=><article className="panel page-stack" key={l.id}><h3>{l.item_name_snapshot} · {l.unit_code_snapshot}</h3><p>Ordered {l.ordered_quantity} · Received {l.received_quantity} · Remaining {l.remaining_quantity}</p><Input id={'actual-receipt-'+l.id} label={'Quantity actually received — '+l.item_name_snapshot} inputMode="decimal" maxLength={32} value={quantities[l.id]??''} onChange={e=>setQuantities(old=>({...old,[l.id]:e.target.value}))} error={quantities[l.id]&&!validReceiptQuantity(quantities[l.id].trim(),l.remaining_quantity)?'Use a positive quantity up to '+l.remaining_quantity+', with at most 3 decimal places.':undefined}/></article>)}
 <label className="field">Receiving notes (optional)<textarea maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label></div></OperationForm>;
}
