import { useState } from 'react';
import { useMutation,useQuery } from '@tanstack/react-query';
import { client } from '../../api/client';
import { Input } from '../../components/ui/Input';
import { exactRupees } from '../../components/analytics/contracts';
import { paiseToRupees } from '../../utils/money';
import type { InventoryItem,Paginated } from '../../hooks/useInventory';
import { businessDate,get,previewLine,validReceiptQuantity,usePurchasingAccess,type Order,type Page,type Supplier } from './contracts';
import { LoadError,Pager } from './shared';
interface DraftLine {itemId:string;quantity:string;unitPrice:string;name:string;unit:string;sku?:string|null}
export function OrderEditor({order,done}:{order:Order|null;done:()=>Promise<void>}){
 const {scope}=usePurchasingAccess(),[supplierSearch,setSupplierSearch]=useState(''),[supplierPage,setSupplierPage]=useState(1),[itemSearch,setItemSearch]=useState(''),[itemPage,setItemPage]=useState(1);
 const [supplierId,setSupplierId]=useState(order?.supplier_id??''),[orderDate,setOrderDate]=useState(businessDate(order?.order_date)==='Not set'?'':businessDate(order?.order_date)),[delivery,setDelivery]=useState(order?.expected_delivery_date?businessDate(order.expected_delivery_date):''),[notes,setNotes]=useState(order?.notes??'');
 const [lines,setLines]=useState<DraftLine[]>(order?.lines?.map(l=>({itemId:l.inventory_item_id,quantity:l.ordered_quantity,unitPrice:paiseToRupees(l.unit_price_minor),name:l.item_name_snapshot,unit:l.unit_code_snapshot,sku:l.sku_snapshot}))??[]);
 const suppliers=useQuery({queryKey:['purchasing',...scope,'supplier-choices',supplierSearch,supplierPage],queryFn:()=>get<Page<Supplier>>('/suppliers',{status:'active',search:supplierSearch,page:supplierPage,limit:20})});
 const items=useQuery({queryKey:['purchasing',...scope,'item-choices',itemSearch,itemPage],queryFn:async()=>(await client.get<Paginated<InventoryItem>>('/inventory',{params:{status:'active',search:itemSearch,page:itemPage,limit:20}})).data});
 const amounts=lines.map(l=>previewLine(l.quantity,l.unitPrice)),total=amounts.every(v=>v!==null)?amounts.reduce<bigint>((n,v)=>n+(v??0n),0n):null;
 const valid=Boolean(supplierId&&orderDate&&(!delivery||delivery>=orderDate)&&lines.length&&total!==null&&total<=9223372036854775807n);
 const save=useMutation({mutationFn:()=>client[order?'patch':'post']('/purchasing/orders'+(order?'/'+order.id:''),{supplierId,orderDate,expectedDeliveryDate:delivery||null,notes:notes||null,currency:'INR',lines:lines.map(({itemId,quantity,unitPrice})=>({itemId,quantity,unitPrice})),...(order?{expectedVersion:order.version}:{})}),onSuccess:done});
 const change=(index:number,key:'quantity'|'unitPrice',value:string)=>setLines(old=>old.map((l,i)=>i===index?{...l,[key]:value}:l));
 return <form className="page-stack" onSubmit={e=>{e.preventDefault();if(valid&&!save.isPending)save.mutate();}}>
  <p>Drafts do not add stock. Agreed unit prices are separate purchasing snapshots, not item prices or payments.</p>
  <Input label="Search active suppliers" type="search" maxLength={200} value={supplierSearch} onChange={e=>{setSupplierSearch(e.target.value);setSupplierPage(1);}}/>
  {suppliers.isError?<LoadError error={suppliers.error} retry={()=>void suppliers.refetch()}/>:<label className="field">Order supplier<select required value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">Select an active supplier</option>{order&&!suppliers.data?.data.some(s=>s.id===order.supplier_id)&&<option value={order.supplier_id}>{order.supplier_name} — previously selected, active status checked on save</option>}{suppliers.data?.data.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label>}
  {suppliers.data&&<Pager page={supplierPage} total={suppliers.data.total} onChange={setSupplierPage}/>}
  <Input label="Order date" type="date" required min="1900-01-01" max="9998-12-31" value={orderDate} onChange={e=>setOrderDate(e.target.value)}/><Input label="Expected delivery date (optional)" type="date" min={orderDate||'1900-01-01'} max="9998-12-31" value={delivery} onChange={e=>setDelivery(e.target.value)}/>
  <section className="page-stack"><h3>Canonical Inventory items</h3><Input label="Search Inventory items" type="search" maxLength={200} value={itemSearch} onChange={e=>{setItemSearch(e.target.value);setItemPage(1);}}/>{items.isPending?<p>Loading items…</p>:items.isError?<LoadError error={items.error} retry={()=>void items.refetch()}/>:items.data&&<><div className="record-actions">{items.data.data.map(i=><button type="button" className="quiet-button break-words" key={i.id} disabled={lines.length>=50||lines.some(l=>l.itemId===i.id)} onClick={()=>setLines(old=>[...old,{itemId:i.id,name:i.name,unit:i.unitCode,sku:i.sku,quantity:'',unitPrice:''}])}>Add {i.name} · {i.unitCode}</button>)}</div>{!items.data.data.length&&<p>No active matching Inventory items. Create items in Inventory first.</p>}<Pager page={itemPage} total={items.data.total} onChange={setItemPage}/></>}</section>
  <section className="page-stack" aria-label="Purchase order lines"><h3>Order lines ({lines.length}/50)</h3>{lines.map((l,index)=><article className="panel page-stack" key={l.itemId}><h4 className="break-words">{l.name} · {l.unit}</h4><p className="break-words">SKU: {l.sku||'Not set'}</p><Input id={'ordered-quantity-'+l.itemId} label={'Ordered quantity — '+l.name} inputMode="decimal" maxLength={32} required value={l.quantity} onChange={e=>change(index,'quantity',e.target.value)}/><Input id={'order-price-'+l.itemId} label={'Agreed unit price INR — '+l.name} inputMode="decimal" maxLength={32} required value={l.unitPrice} onChange={e=>change(index,'unitPrice',e.target.value)}/><p>Line value: {amounts[index]===null?'Enter positive quantity (up to 3 decimals) and non-negative price (up to 2 decimals)':exactRupees(String(amounts[index]))}</p><button type="button" className="quiet-button" onClick={()=>setLines(old=>old.filter((_,i)=>i!==index))}>Remove {l.name}</button></article>)}</section>
  <p className="font-semibold">Ordered purchase value: {total===null?'Check line amounts':exactRupees(String(total))}</p><p className="muted">Each exact quantity × price is rounded once to paise; a positive half-paise rounds up. This is not tax accounting or amount paid.</p><label className="field">Order notes (optional)<textarea maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label>{save.isError&&<LoadError error={save.error} retry={()=>save.mutate()}/>}<button className="action-link" disabled={!valid||save.isPending}>{save.isPending?'Saving draft…':'Save draft'}</button>
 </form>;
}
export function ReceiveEditor({order,done}:{order:Order;done:()=>Promise<void>}){
 const [quantities,setQuantities]=useState<Record<string,string>>({}),[notes,setNotes]=useState(''),[command,setCommand]=useState<{expectedVersion:number;idempotencyKey:string;notes:string|null;lines:{orderLineId:string;quantity:string}[]}|null>(null);
 const available=order.lines?.filter(l=>validReceiptQuantity(l.remaining_quantity,l.remaining_quantity))??[];
 const entered=available.filter(l=>Boolean(quantities[l.id]?.trim())),valid=entered.length>0&&entered.every(l=>validReceiptQuantity(quantities[l.id].trim(),l.remaining_quantity));
 const save=useMutation({mutationFn:()=>client.post('/purchasing/orders/'+order.id+'/receive',command),onSuccess:done});
 const uncertain=save.isError;
 return <form className="page-stack" onSubmit={e=>{e.preventDefault();if(!command&&valid)setCommand({expectedVersion:order.version,idempotencyKey:crypto.randomUUID(),notes:notes||null,lines:entered.map(l=>({orderLineId:l.id,quantity:quantities[l.id].trim()}))});else if(command&&!save.isPending)save.mutate();}}>
  <h2 className="break-all">{order.human_reference}</h2><p>Enter only quantities actually received. Blank lines are excluded; quantities never default to the full order. Receiving increases canonical stock in the selected branch.</p>
  {!command?<>{available.map(l=><article className="panel page-stack" key={l.id}><h3 className="break-words">{l.item_name_snapshot} · {l.unit_code_snapshot}</h3><p>Ordered {l.ordered_quantity} · Received {l.received_quantity} · Remaining {l.remaining_quantity}</p><Input id={'actual-receipt-'+l.id} label={'Quantity actually received — '+l.item_name_snapshot} inputMode="decimal" maxLength={32} value={quantities[l.id]??''} onChange={e=>setQuantities(old=>({...old,[l.id]:e.target.value}))}/>{quantities[l.id]&&!validReceiptQuantity(quantities[l.id].trim(),l.remaining_quantity)&&<p role="alert">Use a positive quantity up to {l.remaining_quantity}, with at most 3 decimal places.</p>}</article>)}<label className="field">Receiving notes (optional)<textarea maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="action-link" disabled={!valid}>Review receipt</button></>:<><section className="panel page-stack" aria-label="Receipt confirmation"><h3>Confirm actual goods received</h3>{command.lines.map(l=><p key={l.orderLineId}>{available.find(a=>a.id===l.orderLineId)?.item_name_snapshot} · {l.quantity} {available.find(a=>a.id===l.orderLineId)?.unit_code_snapshot}</p>)}<p>{command.notes||'No receiving notes'}</p><p>All listed lines commit together. This does not record a payment or alter item prices. Independent Inventory reversal is blocked; returns/corrections are deferred.</p></section>{!uncertain&&<button type="button" className="quiet-button" disabled={save.isPending} onClick={()=>setCommand(null)}>Change quantities</button>}{uncertain&&<p className="muted">The result may be uncertain. Retry this exact confirmed receipt with the same key; do not submit a new receipt until the order is reloaded and its history checked.</p>}{save.isError&&<LoadError error={save.error} retry={()=>save.mutate()}/>}<button className="action-link" disabled={save.isPending}>{save.isPending?'Receiving…':uncertain?'Retry identical receipt':'Confirm Receive Goods'}</button></>}
 </form>;
}
