import { useState } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { client } from '../../api/client';
import { useAppStore } from '../../store/useAppStore';
import { Input } from '../../components/ui/Input';
import { PhoneInput } from '../../components/ui/PhoneInput';
import { AdvancedModal } from '../../components/ui/AdvancedModal';
import { normalizePhone } from '../../utils/phone';
import { exactRupees } from '../../components/analytics/contracts';
import { businessDate,get,label,time,usePurchasingAccess,type Page,type Supplier } from './contracts';
import { History,LoadError,Pager } from './shared';
export default function SuppliersPage(){const {activeTenantId,activeBranchId}=useAppStore();return <Workspace key={activeTenantId+':'+activeBranchId}/>;}
function Workspace(){
 const {scope,manage,inventoryRead}=usePurchasingAccess(),cache=useQueryClient();
 const [search,setSearch]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[editing,setEditing]=useState<Supplier|null|undefined>(undefined),[detail,setDetail]=useState<string|null>(null);
 const list=useQuery({queryKey:['purchasing',...scope,'suppliers',search,status,page],queryFn:()=>get<Page<Supplier>>('/suppliers',{search,page,limit:20,...(status?{status}:{})})});
 const selected=useQuery({queryKey:['purchasing',...scope,'supplier',detail],enabled:Boolean(detail),queryFn:()=>get<Supplier>('/suppliers/'+detail)});
 const refresh=async()=>{await cache.invalidateQueries({queryKey:['purchasing']});};
 const done=async()=>{await refresh();setEditing(undefined);};
 return <div className="page-stack">
  <header className="page-heading"><div><h1>Suppliers</h1><p>Organization directory. Purchase history is limited to your selected branch.</p></div>{manage&&<button className="action-link" onClick={()=>setEditing(null)}>Add Supplier</button>}</header>
  <Link className="quiet-button" to="/purchasing">Purchasing overview</Link>
  <section className="panel catalogue-grid" aria-label="Supplier filters"><Input label="Search suppliers" type="search" maxLength={200} value={search} onChange={e=>{setPage(1);setSearch(e.target.value);}}/><label className="field">Supplier status<select value={status} onChange={e=>{setPage(1);setStatus(e.target.value);}}><option value="">All statuses</option><option value="active">Active</option><option value="archived">Archived</option></select></label><button className="quiet-button" onClick={()=>{setSearch('');setStatus('');setPage(1);}}>Clear supplier filters</button></section>
  {list.isPending?<p role="status">Loading suppliers…</p>:list.isError?<LoadError error={list.error} retry={()=>void list.refetch()}/>:list.data&&<>{!list.data.data.length&&<section className="panel"><h2>{search||status?'No matching suppliers':'No suppliers yet'}</h2><p>A supplier only needs a name. Contacts are optional; shared phone numbers never merge records.</p></section>}<section className="catalogue-grid">{list.data.data.map(s=><article className="panel record-card" key={s.id}><h2 className="break-words">{s.name}</h2><p className="capitalize">{s.status}</p><p className="break-words">{[s.contact_name,s.phone,s.email].filter(Boolean).join(' · ')||'No contact details'}</p><div className="record-actions"><button className="quiet-button" onClick={()=>setDetail(s.id)}>View {s.name}</button>{manage&&<button className="quiet-button" onClick={()=>setEditing(s)}>Edit {s.name}</button>}</div></article>)}</section><Pager page={page} total={list.data.total} onChange={setPage}/></>}
  <AdvancedModal isOpen={editing!==undefined} onClose={()=>setEditing(undefined)} title={editing?'Edit Supplier':'Add Supplier'} size="lg">{editing!==undefined&&<SupplierEditor supplier={editing} done={done}/>}</AdvancedModal>
  <AdvancedModal isOpen={Boolean(detail)} onClose={()=>setDetail(null)} title="Supplier details" size="lg">{selected.isPending?<p>Loading supplier…</p>:selected.isError?<LoadError error={selected.error} retry={()=>void selected.refetch()}/>:selected.data&&<div className="page-stack"><h2 className="break-words">{selected.data.name}</h2><p className="capitalize">{selected.data.status} · Version {selected.data.version}</p><dl className="page-stack">{[['Contact',selected.data.contact_name],['Phone',selected.data.phone],['Email',selected.data.email],['GSTIN',selected.data.gstin],['Address',[selected.data.address_line_1,selected.data.address_line_2,selected.data.city,selected.data.state,selected.data.country,selected.data.postal_code].filter(Boolean).join(', ')],['Notes',selected.data.notes]].map(([title,value])=><div key={title} className="break-words"><dt className="font-semibold">{title}</dt><dd>{value||'Not provided'}</dd></div>)}</dl>{manage&&<button className="quiet-button" onClick={()=>{setDetail(null);setEditing(selected.data!);}}>Edit Supplier</button>}<section><h3>Selected-branch purchase history</h3><p>{selected.data.summary?.orders??'0'} orders · Last ordered: {selected.data.summary?.last_ordered_at?time(selected.data.summary.last_ordered_at):'Never'}</p><p className="muted">Ordered purchase value is not an amount paid. No accounts-payable or payment ledger exists here.</p>{selected.data.orders?.map(o=><article className="panel mt-3" key={o.id}><p className="break-all">{o.human_reference}</p><p>{label(o.status)} · {businessDate(o.order_date)} · {exactRupees(o.total_minor)}</p>{inventoryRead&&<Link className="quiet-button" to={'/purchasing?order='+o.id}>View Purchase Order</Link>}</article>)}</section><History events={selected.data.activity??[]}/><p className="muted">Showing the latest 10 orders and 25 events. Use Purchasing filters for older branch documents and receiving activity.</p></div>}</AdvancedModal>
 </div>;
}
export function SupplierEditor({supplier,done}:{supplier:Supplier|null;done:()=>Promise<void>}){
 const [form,setForm]=useState({name:supplier?.name??'',contactName:supplier?.contact_name??'',phone:supplier?.phone??'',email:supplier?.email??'',gstin:supplier?.gstin??'',addressLine1:supplier?.address_line_1??'',addressLine2:supplier?.address_line_2??'',city:supplier?.city??'',state:supplier?.state??'',country:supplier?.country??'',postalCode:supplier?.postal_code??'',notes:supplier?.notes??'',status:supplier?.status??'active'});
 const set=(key:keyof typeof form,value:string)=>setForm(old=>({...old,[key]:value}));
 const phoneError=form.phone&&!normalizePhone(form.phone)?'Enter a valid phone or leave it blank.':undefined;
 const save=useMutation({mutationFn:()=>client[supplier?'patch':'post']('/suppliers'+(supplier?'/'+supplier.id:''),{...form,phone:form.phone||null,email:form.email||null,gstin:form.gstin||null,...(supplier?{expectedVersion:supplier.version}:{})}),onSuccess:done});
 return <form className="page-stack" onSubmit={e=>{e.preventDefault();if(!phoneError&&!save.isPending)save.mutate();}}><Input label="Supplier name" required maxLength={200} value={form.name} onChange={e=>set('name',e.target.value)}/><Input label="Contact name (optional)" maxLength={200} value={form.contactName} onChange={e=>set('contactName',e.target.value)}/><PhoneInput label="Phone (optional)" value={form.phone} onChange={v=>set('phone',v)} error={phoneError}/><Input label="Email (optional)" type="email" maxLength={254} value={form.email} onChange={e=>set('email',e.target.value)}/><Input label="GSTIN (optional)" maxLength={15} value={form.gstin} onChange={e=>set('gstin',e.target.value.toUpperCase())}/>{([['addressLine1','Address line 1',300],['addressLine2','Address line 2',300],['city','City',100],['state','State',100],['country','Country',100],['postalCode','Postal code',20]] as const).map(([key,title,max])=><Input key={key} label={title+' (optional)'} maxLength={max} value={form[key]} onChange={e=>set(key,e.target.value)}/>)}<label className="field">Supplier notes (optional)<textarea maxLength={2000} value={form.notes} onChange={e=>set('notes',e.target.value)}/></label><label className="field">Supplier lifecycle<select value={form.status} onChange={e=>set('status',e.target.value)}><option value="active">Active — available for new orders</option><option value="archived">Archived — history retained</option></select></label><p className="muted">Archiving does not delete history or change stock. Choose Active to reactivate.</p>{save.isError&&<LoadError error={save.error} retry={()=>save.mutate()}/>}<button className="action-link" disabled={save.isPending||Boolean(phoneError)}>{save.isPending?'Saving…':'Save Supplier'}</button></form>;
}
