import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation,useQueryClient } from '@tanstack/react-query';
import { client } from '../../api/client';
import { useNotifications } from '../../hooks/useNotifications';
import { notificationPath } from '../../components/analytics/contracts';
export default function NotificationsPage(){
 const [page,setPage]=useState(1),[unread,setUnread]=useState(false),[category,setCategory]=useState(''),query=useNotifications(page,unread,category),cache=useQueryClient();
 const save=useMutation({mutationFn:async({id,read}:{id?:string;read:boolean})=>{if(id)await client.patch('/notifications/'+id,{read});else await client.post('/notifications/read-all',{});},onSuccess:()=>cache.invalidateQueries({queryKey:['notifications']})});
 return <div className="page-stack"><header className="page-heading"><div><h1>Notifications</h1><p>{query.data?.unread??'—'} unread · Updates for your workspace access</p></div><Link className="quiet-button" to="/settings?section=notifications">Preferences</Link></header><div className="record-actions"><label className="quiet-button gap-2"><input type="checkbox" checked={unread} onChange={e=>{setUnread(e.target.checked);setPage(1);}}/>Unread only</label><label>Category<select value={category} onChange={e=>{setCategory(e.target.value);setPage(1);}}><option value="">All categories</option><option value="organization">Organization changes</option><option value="crm">CRM assignments</option><option value="hr">HR Plus updates</option></select></label><button className="quiet-button" disabled={save.isPending||!query.data?.unread} onClick={()=>save.mutate({read:true})}>Mark all read</button></div>
 {query.isPending&&<p role="status">Loading notifications…</p>}{(query.isError||save.isError)&&<p role="alert">Notifications could not be loaded or updated. <button className="quiet-button" onClick={()=>void query.refetch()}>Retry</button></p>}{query.data?.rows.length===0&&<section className="panel">You're all caught up.</section>}{query.data?.rows.map(n=><article className="panel page-stack" key={n.id}><h2 className="font-semibold">{n.title}</h2><p>{n.readAt?'Read':'Unread'} · {new Date(n.createdAt).toLocaleString()}</p><p>{n.message}</p><div className="record-actions">{notificationPath(n.action)&&<Link className="action-link" to={notificationPath(n.action)!}>{n.action==='hr'?'Open HR Plus':n.action==='crm'?'Review CRM':'Review access'}</Link>}<button className="quiet-button" disabled={save.isPending} onClick={()=>save.mutate({id:n.id,read:!n.readAt})}>{n.readAt?'Mark unread':'Mark read'}</button></div></article>)}<div className="record-actions"><button className="quiet-button" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page}</span><button className="quiet-button" disabled={query.data?.rows.length!==25} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>;
}
