import {test,expect,type Page,type APIRequestContext} from '@playwright/test';
const api='http://127.0.0.1:5011';
interface Fixture {phone:string;password:string;organizationId:string;branchId:string}
let fixture:Fixture,errors:string[];
test.beforeEach(async({page,request})=>{fixture=await(await request.post(api+'/__test/fixture',{data:{modules:['queue','inventory']}})).json();errors=[];page.on('pageerror',e=>errors.push(e.name));page.on('dialog',d=>d.accept());});
test.afterEach(()=>expect(errors).toEqual([]));
async function login(page:Page,f=fixture){await page.goto('/login');await page.getByLabel('Phone or email').fill(f.phone);await page.getByLabel('Password',{exact:true}).fill(f.password);await page.getByRole('button',{name:'Sign In to Ekavio'}).click();await expect(page).toHaveURL(/dashboard/);}
async function headers(request:APIRequestContext,f=fixture){const r=await request.post(api+'/api/auth/login',{data:{phone:f.phone,password:f.password}});expect(r.status()).toBe(200);const data=await r.json();return {authorization:'Bearer '+data.accessToken,'x-tenant-id':f.organizationId,'x-branch-id':f.branchId};}
const definition=(key:string,type='text')=>({key,label:'QA '+key,help:'Disposable local test field',fieldType:type,status:'active',required:true,searchable:true,filterable:true,reportable:true,defaultValue:null,options:[]});
test('required select, sections, previews, customer create/edit/detail and archived history',async({page})=>{
 await login(page);await page.goto('/custom-fields');await page.getByRole('button',{name:'Add field',exact:true}).click();await page.getByLabel('Field key').fill('category');await page.getByLabel('Field label').fill('QA customer category');await page.getByLabel('Field type').selectOption('select');await page.getByRole('checkbox',{name:'required',exact:true}).check();await page.getByRole('checkbox',{name:'filterable',exact:true}).check();await page.getByRole('button',{name:'Add option',exact:true}).click();await page.getByLabel('Option 1 key').fill('regular');await page.getByLabel('Option 1 label').fill('Regular');await page.getByRole('button',{name:'Add option',exact:true}).click();await page.getByLabel('Option 2 key').fill('guest');await page.getByLabel('Option 2 label').fill('Guest');await page.getByRole('button',{name:'Save field',exact:true}).click();await expect(page.getByRole('heading',{name:'QA customer category',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Add section',exact:true}).click();await page.getByLabel('Section 2 title').fill('Customer details');await page.getByLabel('Section for QA customer category').selectOption({label:'Customer details'});await page.getByRole('button',{name:'Save layout',exact:true}).click();await page.reload();await expect(page.getByLabel('Section 2 title')).toHaveValue('Customer details');await page.getByRole('button',{name:'Mobile preview'}).click();await expect(page.getByRole('dialog').getByLabel('QA customer category *')).toBeVisible();await page.getByRole('dialog').getByRole('button',{name:'Close modal'}).click();
 await page.goto('/customers');await page.getByRole('button',{name:'Create customer',exact:true}).click();await page.getByLabel('Customer name',{exact:true}).fill('QA dynamic customer');await expect(page.getByLabel('QA customer category *')).toBeVisible();await page.getByLabel('QA customer category *').selectOption({label:'Regular'});await page.getByRole('button',{name:'Save customer',exact:true}).click();await expect(page.getByRole('heading',{name:'QA dynamic customer'})).toBeVisible();await page.getByRole('button',{name:'View QA dynamic customer'}).click();await expect(page.getByRole('dialog').getByText('Regular',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Edit customer',exact:true}).click();await page.getByLabel('QA customer category *').selectOption({label:'Guest'});await page.getByRole('button',{name:'Save customer',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.reload();await page.getByLabel('Custom field filter').selectOption({label:'QA customer category'});await page.getByLabel('Filter value').selectOption({label:'Regular'});await expect(page.getByText('No matching customers')).toBeVisible();await page.getByLabel('Filter value').selectOption({label:'Guest'});await page.getByRole('button',{name:'View QA dynamic customer'}).click();await expect(page.getByRole('dialog').getByText('Guest',{exact:true})).toBeVisible();await page.getByRole('dialog').getByRole('button',{name:'Close modal'}).click();
 await page.goto('/custom-fields');await page.getByRole('button',{name:'Edit QA customer category'}).click();await page.getByLabel('Field status').selectOption('archived');await page.getByRole('button',{name:'Save field',exact:true}).click();await expect(page.getByText('category · select · archived')).toBeVisible();await page.goto('/customers');await page.getByRole('button',{name:'View QA dynamic customer'}).click();await expect(page.getByText('QA customer category (archived)')).toBeVisible();await expect(page.getByRole('dialog').getByText('Guest',{exact:true})).toBeVisible();await page.getByRole('dialog').getByRole('button',{name:'Close modal'}).click();await page.getByRole('button',{name:'Create customer',exact:true}).click();await expect(page.getByLabel('QA customer category *')).toHaveCount(0);await page.getByLabel('Customer name',{exact:true}).fill('QA after archive');await page.getByRole('button',{name:'Save customer',exact:true}).click();await expect(page.getByRole('heading',{name:'QA after archive'})).toBeVisible();
});
test('Service, Inventory and membership operational forms preserve values',async({page,request})=>{
 const h=await headers(request);for(const e of ['service','inventory_item','membership']){const r=await request.post(`${api}/api/forms/${e}/definitions`,{headers:h,data:definition('reference')});expect(r.status()).toBe(200);}await login(page);
 await page.goto('/services');await page.getByRole('button',{name:'Create service',exact:true}).click();await page.getByLabel('Service name').fill('QA dynamic service');await page.getByLabel('QA reference *').fill('Service reference');await page.getByRole('button',{name:'Save service',exact:true}).click();await expect(page.getByRole('heading',{name:'QA dynamic service'})).toBeVisible();await page.getByRole('button',{name:'Edit QA dynamic service'}).click();await expect(page.getByLabel('QA reference *')).toHaveValue('Service reference');await page.getByLabel('QA reference *').fill('Updated service reference');await page.getByRole('button',{name:'Save service',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('button',{name:'Edit QA dynamic service'}).click();await expect(page.getByLabel('QA reference *')).toHaveValue('Updated service reference');await page.getByRole('dialog').getByRole('button',{name:'Close modal'}).click();
 await page.goto('/inventory');await page.getByRole('button',{name:'Create item',exact:true}).click();await page.getByLabel('Item name').fill('QA dynamic item');await page.getByLabel('QA reference *').fill('Rack A');await page.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByText('QA dynamic item',{exact:true})).toBeVisible();await page.getByRole('button',{name:/Edit QA dynamic item/}).click();await expect(page.getByLabel('QA reference *')).toHaveValue('Rack A');const before=await(await request.get(api+'/api/inventory',{headers:h})).json();await page.getByLabel('QA reference *').fill('Rack B');await page.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('button',{name:/Edit QA dynamic item/}).click();await expect(page.getByLabel('QA reference *')).toHaveValue('Rack B');const after=await(await request.get(api+'/api/inventory',{headers:h})).json();expect(after.data[0].quantity).toEqual(before.data[0].quantity);const movements=await(await request.get(`${api}/api/inventory/${after.data[0].id}/movements`,{headers:h})).json();expect(movements.data).toHaveLength(0);await page.getByRole('dialog').getByRole('button',{name:'Close modal'}).click();
 await page.goto('/staff');await page.getByRole('button',{name:'My branch assignments'}).click();await page.getByLabel('QA reference *').fill('Staff badge');await page.getByRole('button',{name:'Save staff access'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.reload();await page.getByRole('button',{name:'My branch assignments'}).click();await expect(page.getByLabel('QA reference *')).toHaveValue('Staff badge');
});
test('Appointment fields retain versioned metadata and branch-time contract',async({page,request})=>{
 const h=await headers(request);expect((await request.post(api+'/api/forms/appointment/definitions',{headers:h,data:definition('visit_reason')})).status()).toBe(200);
 const customer=await(await request.post(api+'/api/customers',{headers:h,data:{name:'QA visit customer'}})).json();const service=await(await request.post(api+'/api/services',{headers:h,data:{name:'QA visit service',durationMinutes:30}})).json();expect(customer.data.id).toBeTruthy();expect(service.data.id).toBeTruthy();await login(page);await page.goto('/appointments');await page.getByRole('button',{name:'Add New',exact:true}).click();await expect(page.getByRole('dialog',{name:'Create appointment'})).toBeVisible();await page.getByLabel('Customer',{exact:true}).selectOption({label:'QA visit customer'});await page.getByLabel('Branch-available service').selectOption({label:'QA visit service'});await page.getByLabel('QA visit_reason *').fill('Routine visit');await page.getByRole('dialog').getByRole('button',{name:'Create appointment'}).click();await page.getByRole('button',{name:'Details',exact:true}).click();await expect(page.getByLabel('QA visit_reason *')).toHaveValue('Routine visit');await page.getByLabel('QA visit_reason *').fill('Updated reason');await page.getByRole('button',{name:'Save appointment fields'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('button',{name:'Details',exact:true}).click();await expect(page.getByLabel('QA visit_reason *')).toHaveValue('Updated reason');const date=await page.getByLabel('Appointment date').inputValue();const listed=await(await request.get(api+'/api/appointments?date='+date,{headers:h})).json();const current=listed.data[0];expect(current.version).toBe(2);expect((await request.patch(`${api}/api/forms/appointment/values/${current.id}`,{headers:h,data:{expectedVersion:1,customFields:{visit_reason:'Stale write'}}})).status()).toBe(409);const values=await(await request.get(`${api}/api/forms/appointment/values/${current.id}`,{headers:h})).json();expect(values.data.visit_reason).toBe('Updated reason');
});
test('read-only/config-only/foreign-tenant and entitlement boundaries',async({page,request})=>{
 const owner=await headers(request);const target:Fixture=await(await request.post(api+'/__test/fixture',{data:{permissions:['customers.read']}})).json();const read=await headers(request,target);
 expect((await request.post(api+'/api/forms/customer/definitions',{headers:read,data:definition('rejected')})).status()).toBe(403);
 expect((await request.get(api+'/api/forms/customer/schema',{headers:{...owner,'x-tenant-id':target.organizationId}})).status()).toBe(403);
 expect((await request.get(api+'/api/forms/customer/schema',{headers:{...owner,'x-branch-id':target.branchId}})).status()).toBe(403);
 await login(page,target);await page.goto('/custom-fields');await expect(page).toHaveURL(/dashboard/);await page.goto('/customers');await expect(page.getByRole('button',{name:'Create customer',exact:true})).toHaveCount(0);
 const configOnly:Fixture=await(await request.post(api+'/__test/fixture',{data:{permissions:['fields.read','fields.manage']}})).json();const config=await headers(request,configOnly);expect((await request.get(api+'/api/forms/inventory_item/schema',{headers:config})).status()).toBe(200);expect((await request.get(api+'/api/inventory',{headers:config})).status()).toBe(403);expect((await request.get(api+'/api/customers',{headers:config})).status()).toBe(403);const memberList=await(await request.get(api+'/api/members',{headers:owner})).json();expect((await request.get(`${api}/api/forms/membership/values/${memberList.data[0].membershipId}`,{headers:config})).status()).toBe(403);const noModule:Fixture=await(await request.post(api+'/__test/fixture',{data:{permissions:['inventory.read','queue.read','staff.read']}})).json();const limited=await headers(request,noModule);expect((await request.get(api+'/api/forms/inventory_item/schema',{headers:limited})).status()).toBe(403);expect((await request.get(api+'/api/forms/appointment/schema',{headers:limited})).status()).toBe(403);expect((await request.get(`${api}/api/forms/membership/values/${memberList.data[0].membershipId}`,{headers:limited})).status()).toBe(404);
});
test('ordinary entity manager uses required fields without configuration authority',async({page,request})=>{
 const ordinary:Fixture=await(await request.post(api+'/__test/fixture',{data:{seedCustomerField:true,permissions:['customers.read','customers.manage']}})).json();await login(page,ordinary);await page.goto('/customers');await page.getByRole('button',{name:'Create customer',exact:true}).click();await page.getByLabel('Customer name',{exact:true}).fill('QA ordinary record');await page.getByLabel('QA ordinary note *').fill('Ordinary data access');await page.getByRole('button',{name:'Save customer',exact:true}).click();await expect(page.getByRole('heading',{name:'QA ordinary record'})).toBeVisible();const h=await headers(request,ordinary);expect((await request.post(api+'/api/forms/customer/definitions',{headers:h,data:definition('denied')})).status()).toBe(403);
});
for(const width of [390,768,1440])for(const theme of ['light','dark','system'])test(`dynamic fields fit ${width}px ${theme}`,async({page,request})=>{const h=await headers(request);for(const type of ['text','textarea','number','currency','date','datetime','email','phone','checkbox','select','multiselect','radio','url']){const choice=['select','multiselect','radio'].includes(type);const response=await request.post(api+'/api/forms/customer/definitions',{headers:h,data:{...definition('preview_'+type,type),label:type+' '+('L'.repeat(70)),help:'H'.repeat(400),searchable:false,filterable:false,options:choice?[{key:'one',label:'O'.repeat(90),status:'active'},{key:'two',label:'Other option',status:'active'}]:[]}});expect(response.status()).toBe(200);}await page.setViewportSize({width,height:900});const fits=async()=>{const result=await page.evaluate(()=>({fits:document.documentElement.scrollWidth<=innerWidth,overflow:[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,12).map(e=>({tag:e.tagName,class:e.getAttribute('class'),width:Math.round(e.getBoundingClientRect().width)}))}));expect(result.fits,JSON.stringify(result.overflow)).toBeTruthy();};await login(page);await page.goto('/settings?section=appearance');await page.getByRole('radio',{name:new RegExp(theme,'i')}).click();await page.goto('/custom-fields');await expect(page.getByRole('heading',{name:'Data & Forms',exact:true})).toBeVisible();await fits();await page.getByRole('button',{name:'Desktop preview'}).click();await fits();if(width===1440&&theme==='light')await page.screenshot({path:'test-results/dynamic-fields/safe-form-preview.png'});});
