import { Router,type RequestHandler } from 'express';
import { z } from 'zod';
import { authenticate,requirePermission,type AuthenticatedRequest } from '../middlewares/authMiddleware.js';
import { requireEntitlement } from '../middlewares/tenantMiddleware.js';
import { runtimePostgresDatabase,runtimePersistence } from '../persistence/runtimePersistence.js';
import { CrmService,crmIdentifier } from '../domains/crm/service.js';
import { mapOperationalError } from '../services/operationalRuntimeService.js';
import { AppError } from '../utils/AppError.js';
export const crmService=new CrmService(runtimePostgresDatabase,async org=>new Set((await runtimePersistence.commercial.getEffective(org)).modules.filter(m=>m.enabled).map(m=>m.key)));
const router=Router();router.use(authenticate,requireEntitlement('crm'));
const handle=(operation:(r:AuthenticatedRequest)=>Promise<unknown>,status=200):RequestHandler=>async(r,res,next)=>{try{res.setHeader('Cache-Control','no-store');res.status(status).json({data:await operation(r)});}catch(e){next(e instanceof z.ZodError?new AppError('Invalid CRM input',400):mapOperationalError(e));}};
const read=requirePermission('crm.read'),manage=requirePermission('crm.manage');
router.get('/overview',read,handle(r=>crmService.overview(r.auth!)));
router.get('/stages',read,handle(r=>crmService.stages(r.auth!)));
router.post('/stages',manage,handle(r=>crmService.saveStage(r.auth!,r.body),201));
router.patch('/stages/:id',manage,handle(r=>crmService.saveStage(r.auth!,r.body,crmIdentifier(r.params.id))));
router.post('/stages/recommended',manage,handle(r=>crmService.recommend(r.auth!),201));
router.get('/assignees',read,handle(r=>crmService.choices(r.auth!)));
router.get('/leads',read,handle(r=>crmService.list(r.auth!,r.query)));
router.post('/leads',manage,handle(r=>crmService.createLead(r.auth!,r.body),201));
router.get('/leads/:id',read,handle(r=>crmService.detail(r.auth!,crmIdentifier(r.params.id))));
router.patch('/leads/:id',manage,handle(r=>crmService.updateLead(r.auth!,crmIdentifier(r.params.id),r.body)));
router.post('/leads/:id/status',manage,handle(r=>crmService.changeState(r.auth!,crmIdentifier(r.params.id),r.body)));
router.post('/leads/:id/notes',manage,handle(r=>crmService.note(r.auth!,crmIdentifier(r.params.id),r.body),201));
router.post('/leads/:id/convert',manage,handle(r=>crmService.convert(r.auth!,crmIdentifier(r.params.id),r.body)));
router.get('/leads/:id/activity',read,handle(r=>crmService.history(r.auth!,crmIdentifier(r.params.id),z.coerce.number().int().min(1).max(200).parse(r.query.page??1))));
router.get('/customers/:id/leads',read,requirePermission('customers.read'),handle(r=>crmService.customerContext(r.auth!,crmIdentifier(r.params.id))));
router.get('/followups',read,handle(r=>crmService.followups(r.auth!,r.query)));
router.post('/followups',manage,handle(r=>crmService.createFollowup(r.auth!,r.body),201));
router.patch('/followups/:id',manage,handle(r=>crmService.updateFollowup(r.auth!,crmIdentifier(r.params.id),r.body)));
router.post('/followups/:id/status',manage,handle(r=>crmService.updateFollowup(r.auth!,crmIdentifier(r.params.id),r.body,true)));
export default router;
