import { Router,type RequestHandler } from 'express';
import { z } from 'zod';
import { authenticate,requirePermission,type AuthenticatedRequest } from '../middlewares/authMiddleware.js';
import { requireEntitlement } from '../middlewares/tenantMiddleware.js';
import { runtimePostgresDatabase,runtimePersistence } from '../persistence/runtimePersistence.js';
import { HrService } from '../domains/hr/service.js';
import { AppError } from '../utils/AppError.js';
import { mapOperationalError } from '../services/operationalRuntimeService.js';
export const hrService=new HrService(runtimePostgresDatabase,async org=>new Set((await runtimePersistence.commercial.getEffective(org)).modules.filter(m=>m.enabled).map(m=>m.key)));
const id=(v:unknown)=>z.uuid().parse(v);
const handle=(op:(r:AuthenticatedRequest)=>Promise<unknown>,status=200):RequestHandler=>async(r,res,next)=>{try{res.setHeader('Cache-Control','no-store');res.status(status).json({data:await op(r)});}catch(e){if(e instanceof z.ZodError)return next(new AppError('Invalid HR input',400));const code=e&&typeof e==='object'&&'code' in e?String(e.code):'';next(['23P01','23505','23514','40001','55P03','40P01'].includes(code)?new AppError('HR command conflicts with current history, schedule, leave or version; reload and resolve the conflict',409):mapOperationalError(e));}};
const router=Router();router.use(authenticate,requireEntitlement('hr_plus'));
router.get('/context',handle(r=>hrService.context(r.auth!,r.query)));
router.get('/me/leave',handle(r=>hrService.leaves(r.auth!,r.query,true)));
router.post('/me/leave',handle(r=>hrService.submit(r.auth!,r.body),201));
router.post('/me/leave/:id/cancel',handle(r=>hrService.cancelOwn(r.auth!,id(r.params.id),r.body)));
router.get('/me/leave/:id/history',handle(r=>hrService.history(r.auth!,id(r.params.id),true)));
router.get('/me/schedule',handle(r=>hrService.shifts(r.auth!,r.query,true)));
router.get('/leave',requirePermission('hr_plus.read'),handle(r=>hrService.leaves(r.auth!,r.query)));
router.post('/leave/:id/review',requirePermission('hr_plus.approve'),handle(r=>hrService.review(r.auth!,id(r.params.id),r.body)));
router.get('/history/:id',requirePermission('hr_plus.read'),handle(r=>hrService.history(r.auth!,id(r.params.id))));
router.post('/types',requirePermission('hr_plus.manage'),handle(r=>hrService.saveType(r.auth!,r.body),201));
router.patch('/types/:id',requirePermission('hr_plus.manage'),handle(r=>hrService.saveType(r.auth!,r.body,id(r.params.id))));
router.put('/calendar',requirePermission('hr_plus.manage'),handle(r=>hrService.saveCalendar(r.auth!,r.body)));
router.post('/holidays',requirePermission('hr_plus.manage'),handle(r=>hrService.saveHoliday(r.auth!,r.body),201));
router.patch('/holidays/:id',requirePermission('hr_plus.manage'),handle(r=>hrService.saveHoliday(r.auth!,r.body,id(r.params.id))));
router.post('/templates',requirePermission('hr_plus.manage'),handle(r=>hrService.saveTemplate(r.auth!,r.body),201));
router.patch('/templates/:id',requirePermission('hr_plus.manage'),handle(r=>hrService.saveTemplate(r.auth!,r.body,id(r.params.id))));
router.get('/shifts',requirePermission('hr_plus.read'),handle(r=>hrService.shifts(r.auth!,r.query)));
router.post('/shifts',requirePermission('hr_plus.manage'),handle(r=>hrService.generate(r.auth!,r.body),201));
router.patch('/shifts/:id',requirePermission('hr_plus.manage'),handle(r=>hrService.editShift(r.auth!,id(r.params.id),r.body)));
router.post('/shifts/:id/status',requirePermission('hr_plus.manage'),handle(r=>hrService.transitionShift(r.auth!,id(r.params.id),r.body)));
router.get('/availability',requirePermission('hr_plus.read'),handle(r=>hrService.availability(r.auth!,r.query)));
export default router;
