import { Router, type RequestHandler } from 'express';
import { z } from 'zod';
import { authenticate, requirePermission, requirePlatformOperator, type AuthenticatedRequest } from '../middlewares/authMiddleware.js';
import { validateRequest } from '../middlewares/validateRequest.js';
import { runtimePostgresDatabase } from '../persistence/runtimePersistence.js';
import { OrganizationAdministrationService } from '../services/organizationAdministrationService.js';
import { permissions, permissionCatalogue, type Permission } from '../services/authorizationPolicy.js';
import { customValuesSchema } from '../domains/dynamicFields/policy.js';
import { DynamicFieldsService } from '../domains/dynamicFields/service.js';
import { disconnectOrganizationSockets } from '../config/socket.js';
const service=new OrganizationAdministrationService(runtimePostgresDatabase);
const router=Router(); router.use(['/organization','/branches','/roles','/members','/audit','/platform'],authenticate);
router.get('/organization/context',handleContext);
function handleContext(request:AuthenticatedRequest,response:import('express').Response) {response.setHeader('Cache-Control','no-store');response.json({data:{permissions:request.auth!.permissions,role:request.auth!.role}});}
const handle=(fn:(r:AuthenticatedRequest)=>Promise<unknown>):RequestHandler=>async(r,res,next)=>{try{res.setHeader('Cache-Control','no-store');res.json({data:await fn(r)});}catch(error){next(error);}};
const text=(size:number)=>z.string().trim().max(size);
const version=z.number().int().positive();
const branches=z.array(z.uuid()).min(1).max(50).refine(v=>new Set(v).size===v.length);
const profile=z.object({name:text(200).min(1),type:text(100).min(1),businessCategory:text(100),description:text(1000),contactEmail:z.union([z.email().max(254),z.literal('')]),contactPhone:text(32),address:text(500),website:z.union([z.url().max(254).refine(v=>/^https?:\/\//.test(v)),z.literal('')])}).strict();
const branch=z.object({name:text(200).min(1),code:text(64).min(1).regex(/^[a-z0-9_-]+$/),timezone:text(100).min(1),status:z.enum(['active','inactive']),version:version.optional()}).strict();
const custom=z.object({name:text(100).min(1),description:text(500),permissions:z.array(z.enum(Object.values(permissions) as [Permission,...Permission[]])).max(100).refine(v=>new Set(v).size===v.length),version:version.optional(),status:z.enum(['active','archived']).optional()}).strict();
const search=(r:AuthenticatedRequest)=>z.string().max(200).parse(r.query.search??'');
const id=(r:AuthenticatedRequest)=>z.uuid().parse(r.params.id);
router.get('/organization',requirePermission('organization.read'),handle(r=>service.overview(r.auth!)));
router.put('/organization',requirePermission('organization.manage'),validateRequest(profile),handle(r=>service.saveProfile(r.auth!,r.body)));
router.get('/branches',requirePermission('branches.read'),handle(r=>service.branches(r.auth!,search(r))));
router.post('/branches',requirePermission('branches.manage'),validateRequest(branch),handle(r=>service.saveBranch(r.auth!,r.body)));
router.patch('/branches/:id',requirePermission('branches.manage'),validateRequest(branch),handle(r=>service.saveBranch(r.auth!,r.body,id(r))));
router.get('/roles',requirePermission('roles.read'),handle(r=>service.roles(r.auth!)));
router.get('/roles/catalogue',handle(async()=>permissionCatalogue));
router.post('/roles',requirePermission('roles.manage'),validateRequest(custom),handle(r=>service.saveRole(r.auth!,r.body)));
router.patch('/roles/:id',requirePermission('roles.manage'),validateRequest(custom),handle(r=>service.saveRole(r.auth!,r.body,id(r))));
router.get('/members',requirePermission('staff.read'),handle(r=>service.staff(r.auth!,search(r))));
router.patch('/members/:id',requirePermission('staff.manage'),validateRequest(z.object({customFields:customValuesSchema.optional(),role:z.enum(['owner','admin','manager','hr','staff']),customRoleId:z.uuid().nullable(),status:z.enum(['active','inactive','revoked']),branchIds:branches,version}).strict()),handle(async r=>{
 const result=await new DynamicFieldsService(runtimePostgresDatabase).mutate(r.auth!,'membership',r.body.customFields,false,async()=>{await service.saveMember(r.auth!,id(r),r.body,false);return {id:id(r)};});
 disconnectOrganizationSockets(r.auth!.organizationId);return result;
}));
router.get('/audit',requirePermission('audit.read'),handle(r=>service.audit(r.auth!,z.object({from:z.iso.datetime().optional(),to:z.iso.datetime().optional(),actor:z.uuid().optional(),action:text(128).optional(),category:text(64).optional(),page:z.coerce.number().int().min(1).max(10000).default(1)}).strict().parse(r.query))));
router.get('/audit/actors',requirePermission('audit.read'),handle(r=>service.auditActors(r.auth!)));
router.get('/platform/organizations',requirePlatformOperator,handle(r=>service.directory(search(r),z.coerce.number().int().min(1).max(10000).parse(r.query.page??1))));
router.get('/platform/overview',requirePlatformOperator,handle(()=>service.platformOverview()));
export default router;
