import { Router,type RequestHandler } from 'express';
import { z } from 'zod';
import { authenticate,requirePermission,type AuthenticatedRequest } from '../middlewares/authMiddleware.js';
import { requireEntitlement } from '../middlewares/tenantMiddleware.js';
import { runtimePostgresDatabase,runtimePersistence } from '../persistence/runtimePersistence.js';
import { PurchasingService,purchasingIdentifier } from '../domains/purchasing/service.js';
import { mapOperationalError } from '../services/operationalRuntimeService.js';
import { AppError } from '../utils/AppError.js';
export const purchasingService=new PurchasingService(runtimePostgresDatabase,async org=>new Set((await runtimePersistence.commercial.getEffective(org)).modules.filter(m=>m.enabled).map(m=>m.key)));
const handle=(op:(r:AuthenticatedRequest)=>Promise<unknown>,status=200):RequestHandler=>async(r,res,next)=>{try{res.setHeader('Cache-Control','no-store');res.status(status).json({data:await op(r)});}catch(e){next(e instanceof z.ZodError?new AppError('Invalid purchasing input',400):mapOperationalError(e));}};
const read=requirePermission('purchasing.read'),manage=requirePermission('purchasing.manage');
export const supplierRoutes=Router();supplierRoutes.use(authenticate,requireEntitlement('purchasing'));
supplierRoutes.get('/',read,handle(r=>purchasingService.suppliers(r.auth!,r.query)));
supplierRoutes.post('/',manage,handle(r=>purchasingService.saveSupplier(r.auth!,r.body),201));
supplierRoutes.get('/:id',read,handle(r=>purchasingService.supplierDetail(r.auth!,purchasingIdentifier(r.params.id))));
supplierRoutes.patch('/:id',manage,handle(r=>purchasingService.saveSupplier(r.auth!,r.body,purchasingIdentifier(r.params.id))));
const router=Router();router.use(authenticate,requireEntitlement('purchasing'));
router.get('/overview',read,handle(r=>purchasingService.overview(r.auth!)));
router.get('/orders',read,handle(r=>purchasingService.orders(r.auth!,r.query)));
router.post('/orders',manage,handle(r=>purchasingService.saveOrder(r.auth!,r.body),201));
router.get('/orders/:id',read,handle(r=>purchasingService.detail(r.auth!,purchasingIdentifier(r.params.id))));
router.patch('/orders/:id',manage,handle(r=>purchasingService.saveOrder(r.auth!,r.body,purchasingIdentifier(r.params.id))));
router.post('/orders/:id/status',manage,handle(r=>purchasingService.transition(r.auth!,purchasingIdentifier(r.params.id),r.body)));
router.post('/orders/:id/receive',manage,handle(r=>purchasingService.receive(r.auth!,purchasingIdentifier(r.params.id),r.body),201));
router.get('/receipts',read,handle(r=>purchasingService.receipts(r.auth!,r.query)));
export default router;
