import { useState } from 'react';
import { useQuery,useMutation } from '@tanstack/react-query';
import { client } from '../../api/client';
import { getErrorMessage } from '../../api/errors';
import { useAppStore } from '../../store/useAppStore';
import { Input } from '../../components/ui/Input';
import { AdvancedModal } from '../../components/ui/AdvancedModal';
import { exactRupees,saveCsv,type ReportData,type ReportDescriptor } from '../../components/analytics/contracts';
import { CustomerReportFilter } from '../../components/analytics/CustomerReportFilter';
export default function ReportsPage(){
 const {user,activeTenantId,activeBranchId,entitlements}=useAppStore(),[key,setKey]=useState(''),[filters,setFilters]=useState<Record<string,string>>({}),[selected,setSelected]=useState<string[]|null>(null),[page,setPage]=useState(1),[drawer,setDrawer]=useState(false);
 const scope=[user?.id,activeTenantId,activeBranchId,user?.permissions,entitlements];
 const catalogue=useQuery({queryKey:['report-catalogue',...scope],staleTime:30_000,queryFn:async()=>(await client.get<{data:ReportDescriptor[]}>('/reports')).data.data});
 const current=catalogue.data?.find(r=>r.key===key)??catalogue.data?.[0];
 const params={...filters,...(selected?{columns:selected.join(',')}:{})};
 const report=useQuery({queryKey:['report',...scope,current?.key,params,page],enabled:Boolean(current),staleTime:30_000,placeholderData:(previous,query)=>JSON.stringify(query?.queryKey.slice(0,7))===JSON.stringify(['report',...scope,current?.key])?previous:undefined,queryFn:async()=>(await client.get<{data:ReportData}>('/reports/'+current!.key,{params:{...params,page}})).data.data});
 const download=useMutation({mutationFn:async()=>{const response=await client.get<Blob>('/reports/'+current!.key+'/export',{params,responseType:'blob'});saveCsv(response.data,current!.key);}});
 const change=(name:string,value:string)=>{setPage(1);setFilters(old=>{const next={...old};if(value)next[name]=value;else delete next[name];return next;});};
 const clear=()=>{setFilters({});setSelected(null);setPage(1);};
 const controls=<div className="page-stack">{current?.dateRange&&<><Input label="From business date" type="date" value={filters.from??''} onChange={e=>change('from',e.target.value)}/><Input label="To business date" type="date" value={filters.to??''} onChange={e=>change('to',e.target.value)}/></>}{current?.filters.includes('search')&&<Input label="Search names" maxLength={200} value={filters.search??''} onChange={e=>change('search',e.target.value)}/>} {Boolean(current?.statuses.length)&&<label>Status<select className="w-full" value={filters.status??''} onChange={e=>change('status',e.target.value)}><option value="">All statuses</option>{current?.statuses.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label>}{current?.filters.includes('stockStatus')&&<label>Stock status<select className="w-full" value={filters.stockStatus??''} onChange={e=>change('stockStatus',e.target.value)}><option value="">All stock</option><option value="low">Low stock</option><option value="out">Out of stock</option><option value="normal">Above threshold</option></select></label>}{current?.filters.includes('entryType')&&<label>Entry type<select className="w-full" value={filters.entryType??''} onChange={e=>change('entryType',e.target.value)}><option value="">All types</option>{(current.key==='stock-movements'?['opening','receive','consume','adjustment_increase','adjustment_decrease','reversal']:['charge','payment','adjustment_increase','adjustment_decrease','reversal']).map(t=><option key={t} value={t}>{t.replaceAll('_',' ')}</option>)}</select></label>}<button className="quiet-button" onClick={clear}>Clear filters</button></div>;
 const customControl=(current?.key==='customers'||current?.key==='crm-leads')?<CustomerReportFilter entity={current.key==='crm-leads'?'lead':'customer'} onApply={(key,value,operator)=>{setPage(1);setFilters(old=>{const next={...old};delete next.customKey;delete next.customValue;delete next.customOperator;return key?{...next,customKey:key,customValue:value,customOperator:operator}:next;});}}/>:null;
 const relationshipControls=<div className="page-stack">{Object.entries(report.data?.choices??{}).map(([key,choices])=><label key={key}>{({customerId:'Customer',serviceId:'Service',staffId:'Staff'} as Record<string,string>)[key]} filter<select className="w-full" value={filters[key]??''} onChange={e=>change(key,e.target.value)}><option value="">All matching records</option>{choices.map(choice=><option key={choice.id} value={choice.id}>{choice.label}</option>)}</select><small className="muted">Up to 100 choices from authorized branch records.</small></label>)}</div>;
 const data=report.data,columns=data?.columns.filter(c=>c.selected)??[],chosen=selected??columns.map(c=>c.key);
 const cell=(row:Record<string,string|null>,col:typeof columns[number])=>row[col.key]===null?'—':col.format==='money'?exactRupees(row[col.key]!):String(row[col.key]);
 return <div className="page-stack reports-page"><header className="page-heading"><div><h1>Reports</h1><p>Factual records from your current access. Customer Dues are not revenue; stock movements are not sales.</p></div><button className="action-link" disabled={!data||download.isPending} onClick={()=>download.mutate()}>Export CSV</button></header>
 {catalogue.isPending&&<p role="status">Loading reports…</p>}{catalogue.isError&&<p role="alert">Reports unavailable. <button onClick={()=>void catalogue.refetch()}>Retry catalogue</button></p>}{catalogue.data?.length===0&&<section className="panel">No reports are available for your current permissions and subscription.</section>}{current&&<><label>Report<select className="w-full" value={current.key} onChange={e=>{setKey(e.target.value);clear();}}>{catalogue.data?.map(r=><option key={r.key} value={r.key}>{r.label}</option>)}</select></label><p className="muted">{current.scope==='organization'?'Organization-owned directory':'Selected branch only'} · Exports: up to 2,000 rows / 5 MiB; wide columns reduce the row budget</p><button className="quiet-button report-mobile-filter" onClick={()=>setDrawer(true)}>Filters</button><section className="panel report-desktop-filter"><h2 className="font-semibold mb-3">Filters</h2>{!drawer&&<>{controls}{relationshipControls}{customControl}</>}</section><AdvancedModal isOpen={drawer} onClose={()=>setDrawer(false)} title="Report filters" actions={<button className="action-link" onClick={()=>setDrawer(false)}>Done</button>}>{controls}{relationshipControls}{customControl}</AdvancedModal></>}
 {report.isFetching&&<p role="status">Loading matching records…</p>}{report.isError&&<section className="panel" role="alert">{getErrorMessage(report.error,'Report unavailable.')} <button className="quiet-button" onClick={()=>void report.refetch()}>Retry report</button></section>}{download.isError&&<p role="alert">Export failed. Narrow your filters or retry. No partial export was downloaded.</p>}
 {data&&<><p className="muted">{data.timezone} · Generated {new Date(data.generatedAt).toLocaleString()}{data.filters.from?` · ${data.filters.from} to ${data.filters.to}`:''}</p><section className="catalogue-grid">{Object.entries(data.summary).map(([label,value])=><article className="panel" key={label}><h2>{({records:'Matching records',outstanding_minor:'Positive branch balances',customers_owing:'Customers owing',net_effect_minor:'Signed period balance effect'} as Record<string,string>)[label]??label.replaceAll('_',' ')}</h2><strong>{label.endsWith('_minor')?exactRupees(value):value}</strong></article>)}</section><details className="panel"><summary>Choose columns</summary><fieldset className="report-columns"><legend className="sr-only">Report columns</legend>{data.columns.map(c=><label className="flex items-center gap-2" key={c.key}><input type="checkbox" checked={chosen.includes(c.key)} disabled={chosen.includes(c.key)&&chosen.length===1} onChange={e=>{setPage(1);setSelected(e.target.checked?[...chosen,c.key]:chosen.filter(key=>key!==c.key));}}/>{c.label}</label>)}</fieldset></details>
 {data.rows.length===0?<section className="panel"><p>No records matched these filters.</p><button className="quiet-button" onClick={clear}>Clear filters</button></section>:<><div className="report-table"><table><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{data.rows.map((row,i)=><tr key={i}>{columns.map(c=><td key={c.key}>{cell(row,c)}</td>)}</tr>)}</tbody></table></div><div className="report-mobile-rows">{data.rows.map((row,i)=><article className="panel" key={i}><dl>{columns.map(c=><div key={c.key}><dt className="muted">{c.label}</dt><dd>{cell(row,c)}</dd></div>)}</dl></article>)}</div></>}<div className="record-actions"><button className="quiet-button" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page}</span><button className="quiet-button" disabled={page*data.limit>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div></>}
 </div>;
}
