import { test, expect, type Page, type APIRequestContext } from '@playwright/test';
import { randomUUID } from 'node:crypto';
const api = 'http://127.0.0.1:5011', site = 'http://127.0.0.1:4175';
interface Fixture { phone: string; password: string; organizationId: string; branchId: string }
let operator: Fixture, headers: Record<string, string>, errors: string[];
test.beforeEach(async ({ page, request }) => {
  operator = await (await request.post(api + '/__test/fixture', { data: { operator: true, modules: [] } })).json();
  const auth = await (await request.post(api + '/api/auth/login', { data: { phone: operator.phone, password: operator.password } })).json();
  headers = { authorization: 'Bearer ' + auth.accessToken, 'x-tenant-id': operator.organizationId, 'x-branch-id': operator.branchId };
  errors = []; page.on('pageerror', (error) => errors.push(error.name));
  const all = await (await request.get(api + '/api/billing/operator/public-pricing', { headers })).json();
  for (const offer of all.data) if (offer.available && offer.status === 'active') await price(request, offer.offerType, offer.key, false);
  await price(request, 'plan', 'pilot-core', true); await price(request, 'add_on', 'module-inventory', true); await price(request, 'add_on', 'module-queue', true);
});
test.afterEach(() => expect(errors).toEqual([]));
async function price(request: APIRequestContext, type: string, key: string, published: boolean, contact = false, monthly = '10000') {
  expect((await request.put(api + `/api/billing/operator/public-pricing/${type}/${key}`, { headers, data: { pricingMode: contact ? 'contact' : 'fixed', currency: 'INR', monthlyPriceMinor: contact ? null : monthly, yearlyPriceMinor: contact ? null : '100000', published, displayOrder: 0, marketingLabel: null } })).status()).toBe(200);
}
async function login(page: Page, fixture = operator) { await page.goto(site + '/login'); await page.getByLabel('Phone or email').fill(fixture.phone); await page.getByLabel('Password', { exact: true }).fill(fixture.password); await page.getByRole('button', { name: 'Sign In to Ekavio' }).click(); await expect(page).toHaveURL(/dashboard/); }
async function details(page: Page, name = 'STAGING F disposable business', phone = '+9197' + String(Math.floor(10000000 + Math.random() * 89999999))) {
  await page.getByRole('button', { name: 'Continue to business details' }).click(); await page.getByLabel('Business name').fill(name); await page.getByLabel('Contact name').fill('STAGING F owner'); await page.getByLabel('Phone number', { exact: true }).fill(phone.slice(3)); await page.getByRole('button', { name: 'Review request' }).click(); await expect(page.getByText(phone, { exact: true })).toBeVisible(); return phone;
}
test('fixed package, included-module removal and addon preserve plan; yearly savings and human receipt', async ({ page }) => {
  await page.goto('/'); await page.getByRole('button', { name: 'Select Queue Module' }).click(); await page.getByRole('button', { name: 'Select Pilot Core' }).click(); await expect(page.getByRole('button', { name: 'Included in Pilot Core' })).toBeDisabled(); await expect(page.getByText(/Included modules removed/)).toBeVisible(); await page.getByRole('button', { name: 'Select Inventory Module' }).click(); await expect(page.locator('.public-offer').filter({ has: page.getByRole('heading', { name: 'Pilot Core', exact: true }) }).getByRole('button')).toHaveAttribute('aria-pressed', 'true'); await page.getByRole('button', { name: 'Yearly', exact: true }).click(); await expect(page.getByText('Save ₹200.00 yearly vs 12 monthly payments').first()).toBeVisible(); await details(page);
  const response = page.waitForResponse((r) => r.url().endsWith('/public/access-requests')); await page.getByRole('button', { name: 'Submit access request' }).click(); const body = (await (await response).json()).data; await expect(page.getByText(body.publicReference, { exact: true })).toBeVisible(); expect(body.publicReference).toMatch(/^EV-REQ-[A-F0-9]{32}$/); await expect(page.getByText(body.receiptId, { exact: true })).toHaveCount(0); await expect(page.getByText(/not activated by this request/)).toBeVisible(); await page.getByRole('button', { name: 'Send another request' }).click(); await expect(page.getByRole('button', { name: 'Continue to business details' })).toBeDisabled();
});
test('mixed contact estimate never shows a partial total and produces contact receipt', async ({ page, request }) => {
  await price(request, 'add_on', 'module-inventory', true, true); await page.goto('/'); await page.getByRole('button', { name: 'Select Pilot Core' }).click(); await page.getByRole('button', { name: 'Select Inventory Module' }).click(); await expect(page.getByText('Discussion required · monthly')).toBeVisible(); const summary = page.locator('.public-quote'); await expect(summary.getByText('Contact for pricing', { exact: true })).toHaveCount(2); await details(page); await page.getByRole('button', { name: 'Submit access request' }).click(); await expect(page.getByRole('heading', { name: 'Request received' })).toBeVisible(); await expect(page.getByText('Contact for pricing — final terms need a discussion.')).toBeVisible();
});
test('price change requires a fresh review and unpublishing prevents submission', async ({ page, request }) => {
  await page.goto('/'); await page.getByRole('button', { name: 'Select Pilot Core' }).click(); await details(page); await price(request, 'plan', 'pilot-core', true, false, '20000'); await page.getByRole('button', { name: 'Submit access request' }).click(); await expect(page.getByText(/setup or pricing changed/)).toBeVisible(); await expect(page.getByRole('heading', { name: /Step 1 of 3/ })).toBeVisible(); await expect(page.locator('.public-quote').getByText('₹200.00', { exact: true }).first()).toBeVisible(); await price(request, 'plan', 'pilot-core', false); await page.getByRole('button', { name: 'Continue to business details' }).click(); await page.getByRole('button', { name: 'Review request' }).click(); await page.getByRole('button', { name: 'Submit access request' }).click(); await expect(page.getByRole('heading', { name: /Step 1 of 3/ })).toBeVisible(); await expect(page.getByRole('button', { name: 'Continue to business details' })).toBeDisabled();
});
test('API unavailable, rate limit and invalid phone are honest recoverable errors', async ({ page }) => {
  await page.route('**/public/commercial/catalogue', (route) => route.fulfill({ status: 503, json: { error: { message: 'Temporarily unavailable' } } })); await page.goto('/'); await expect(page.getByText('Pricing is unavailable right now. Your workspace has not been activated.')).toBeVisible(); await page.unroute('**/public/commercial/catalogue'); await page.getByRole('button', { name: 'Retry pricing' }).click(); await page.getByRole('button', { name: 'Select Pilot Core' }).click(); await page.getByRole('button', { name: 'Continue to business details' }).click(); await page.getByLabel('Business name').fill('STAGING F invalid phone'); await page.getByLabel('Contact name').fill('QA owner'); await page.getByLabel('Phone number', { exact: true }).fill('12'); await page.getByRole('button', { name: 'Review request' }).click(); await expect(page.getByText('Enter a valid phone number')).toBeVisible(); await page.getByLabel('Phone number', { exact: true }).fill('9876543210'); await page.getByRole('button', { name: 'Review request' }).click(); await page.route('**/public/access-requests', (route) => route.fulfill({ status: 429, json: { message: 'Too many access requests; try again later' } })); await page.getByRole('button', { name: 'Submit access request' }).click(); await expect(page.getByText('Too many access requests; try again later')).toBeVisible(); await expect(page.getByRole('heading', { name: 'Request received' })).toHaveCount(0);
});
test('real browser request → operator approval/agreement/test settlement → one-time onboarding → Billing → renewal applied once', async ({ page, browser, request }) => {
  const name = 'STAGING F full lifecycle ' + randomUUID().slice(0, 8);
  await page.goto('/'); await page.getByRole('button', { name: 'Select Pilot Core' }).click(); await page.getByRole('button', { name: 'Select Inventory Module' }).click(); const phone = await details(page, name);
  const receiptResponse = page.waitForResponse((r) => r.url().endsWith('/public/access-requests')); await page.getByRole('button', { name: 'Submit access request' }).click(); const receipt = (await (await receiptResponse).json()).data;
  await login(page); await page.goto('/commercial/requests'); await page.getByLabel('Search reference, business or contact').fill(receipt.publicReference); await page.getByRole('button', { name: new RegExp(name) }).click(); await page.getByRole('button', { name: 'Mark approved' }).click(); await expect(page.getByRole('heading', { name: 'Finalize commercial agreement' })).toBeVisible();
  const start = new Date(); start.setHours(0, 0, 0, 0); const end = new Date(start); end.setDate(end.getDate() + 30); const local = (date: Date) => new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
  await page.getByLabel('Agreed total ₹', { exact: true }).fill('150'); await page.getByLabel('Adjustment / complimentary reason').fill('STAGING TEST DATA negotiated terms'); await page.getByLabel('Subscription starts').fill(local(start)); await page.getByLabel('Subscription ends').fill(local(end)); await page.getByRole('button', { name: 'Finalize agreement', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Record manual payment' })).toBeVisible(); await page.getByLabel('Amount ₹', { exact: true }).fill('150'); await page.getByLabel('Safe reference (optional)').fill('STAGING TEST DATA NO REAL FUNDS'); await page.getByLabel('Paid at').fill(local(new Date())); await page.getByRole('button', { name: 'Record payment', exact: true }).click(); await expect(page.getByRole('button', { name: 'Generate onboarding link' })).toBeVisible();
  const invitation = page.waitForResponse((r) => r.url().endsWith('/onboarding-invitations')); await page.getByRole('button', { name: 'Generate onboarding link' }).click(); const path = (await (await invitation).json()).data.onboardingPath;
  const customerContext = await browser.newContext(), customerPage = await customerContext.newPage(); const password = randomUUID();
  try {
    await customerPage.goto(site + path); await expect(customerPage).toHaveURL(/onboarding$/); await expect(customerPage.getByText(name, { exact: true })).toBeVisible(); await customerPage.getByLabel('Password', { exact: true }).fill(password); await customerPage.getByLabel('Confirm password', { exact: true }).fill(password); await customerPage.getByRole('button', { name: 'Create my workspace' }).click(); await expect(customerPage).toHaveURL(/login$/); await login(customerPage, { phone, password, organizationId: '', branchId: '' }); await customerPage.goto(site + '/billing'); await expect(customerPage.getByText('₹150.00').first()).toBeVisible(); await expect(customerPage.getByText('Inventory Module').first()).toBeVisible(); await expect(customerPage.getByRole('link', { name: 'Commercial Intake', exact: true })).toHaveCount(0);
    const reused = customerPage.waitForResponse((response) => response.url().endsWith('/onboarding/inspect')); await customerPage.goto(site + path); expect((await reused).status()).toBe(410); await expect(customerPage.getByText(/This onboarding invitation cannot be used|invalid, expired, used, or revoked/)).toBeVisible();
    await page.goto('/commercial/renewals'); await page.getByLabel('Renewal queue view').selectOption('all'); await page.getByRole('button', { name: new RegExp(name) }).click(); await page.getByLabel('Agreed renewal total ₹').fill('200'); await page.getByLabel('Negotiated / complimentary reason').fill('STAGING TEST DATA renewal'); const renewedEnd = new Date(end); renewedEnd.setDate(renewedEnd.getDate() + 30); await page.getByLabel('Renewal starts').fill(local(end)); await page.getByLabel('Renewal ends').fill(local(renewedEnd)); await page.getByRole('button', { name: 'Finalize renewal', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Record manual renewal payment' })).toBeVisible(); await page.getByLabel('Amount ₹', { exact: true }).fill('200'); await page.getByLabel('Paid at').fill(local(new Date())); await page.getByRole('button', { name: 'Record payment', exact: true }).click(); await expect(page.getByText('Exact settlement confirmed')).toBeVisible(); page.once('dialog', (dialog) => dialog.accept()); const applied = page.waitForResponse((r) => r.url().endsWith('/apply')); await page.getByRole('button', { name: 'Apply renewal', exact: true }).click(); const applyResponse = await applied; expect(applyResponse.status()).toBe(200); const renewal = (await applyResponse.json()).data.renewal;
    await expect(page.getByText(/Renewal applied once on/)).toBeVisible(); const repeated = await request.post(api + '/api/billing/operator/renewals/' + renewal.id + '/apply', { headers, data: {} }); expect(repeated.status()).toBe(200); const repeatedRenewal = (await repeated.json()).data.renewal; expect(repeatedRenewal.appliedAt).toBe(renewal.appliedAt); expect(repeatedRenewal.renewalEndsAt).toBe(renewal.renewalEndsAt); await customerPage.goto(site + '/billing'); await expect(customerPage.getByText('Continuous renewal', { exact: true })).toBeVisible(); await expect(customerPage.getByText('₹200.00').first()).toBeVisible(); await expect(customerPage.getByText('₹150.00').first()).toBeVisible();
  } finally { await customerContext.close(); }
});
for (const width of [360, 390, 768, 1024, 1440, 1920]) for (const theme of ['light', 'dark', 'system']) test(`public navigation, wizard, branding and account pages fit ${width}px ${theme}`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 }); await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' }); await page.goto('/'); await page.getByLabel('Appearance', { exact: true }).selectOption(theme); await expect(page.locator('html')).toHaveAttribute('data-theme', theme === 'light' ? 'light' : 'dark'); await expect(page.getByRole('heading', { name: /Run your daily business/ })).toBeVisible();
  if (width < 1024) { const menu = page.getByRole('button', { name: 'Open public navigation' }); await menu.click(); await expect(page.getByRole('dialog', { name: 'Public navigation' })).toBeVisible(); await page.keyboard.press('Escape'); await expect(menu).toBeFocused(); }
  else await expect(page.getByRole('button', { name: 'Open public navigation' })).toBeHidden();
  const skip = page.getByRole('link', { name: 'Skip to content' }); await skip.focus(); await expect(skip).toBeInViewport(); await skip.click(); await expect(page.locator('#public-main')).toBeFocused();
  await page.getByRole('button', { name: 'Select Pilot Core' }).click(); await details(page); await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy(); await page.getByRole('button', { name: 'Edit business details' }).click(); await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  if ([390, 1440].includes(width) && theme !== 'system') { await page.goto('/'); await page.screenshot({ path: `test-results/commercial/public-${width}-${theme}.png`, fullPage: true }); }
  for (const path of ['/login', '/forgot-password', '/reset-password', '/verify-email', '/accept-invitation', '/onboarding', '/privacy']) { await page.goto(path); await expect(page.getByRole('heading', { level: 1 })).toBeVisible(); await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy(); expect(await page.title()).toContain('EkaVio'); if (path !== '/privacy') await expect(page.locator('meta[name="robots"]')).toHaveAttribute('content', 'noindex,nofollow'); }
});
