import { useState } from 'react';
import { useQuery,useMutation,useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { client } from '../../api/client';
import { getErrorMessage } from '../../api/errors';
import { useAppStore } from '../../store/useAppStore';
import { AdvancedModal } from '../../components/ui/AdvancedModal';
import { Input } from '../../components/ui/Input';
import { PhoneInput } from '../../components/ui/PhoneInput';
import { normalizePhone } from '../../utils/phone';
import { DynamicForm } from '../../components/forms/DynamicForm';
import { EntityFields } from '../../components/forms/EntityFields';
import { useDynamicForm } from '../../hooks/useDynamicForm';
import { CustomerReportFilter } from '../../components/analytics/CustomerReportFilter';
import { activityLabels,displayTime,localDateTime,type Lead,type Stage,type Followup,type Page,type Activity } from './contracts';
const get=async<T,>(path:string,params?:Record<string,unknown>,signal?:AbortSignal)=>(await client.get<{data:T}>('/crm/'+path,{params,signal})).data.data;
import { RelationshipRecords } from '../../components/ui/RelationshipRecords';
import { uncertainWrite, optionalEmailValid } from '../../utils/mutationOutcome';
import { OperationForm } from '../../components/ui/OperationForm';
import { StatusBadge, DetailSection } from '../../components/ui/WorkspacePrimitives';
import { useRecordLink } from '../../hooks/useRecordLink';
import { useOperationalScope } from '../../hooks/useOperationalContext';
interface Choice {id:string;name:string}
function Pager({page,total,limit,onChange}:{page:number;total:number;limit:number;onChange:(n:number)=>void}){return <div className="pagination"><button className="quiet-button" disabled={page===1} onClick={()=>onChange(page-1)}>Previous</button><span>Page {page} of {Math.max(1,Math.ceil(total/limit))}</span><button className="quiet-button" disabled={page*limit>=total} onClick={()=>onChange(page+1)}>Next</button></div>;}
function LoadError({error,retry}:{error:unknown;retry:()=>void}){return <p role="alert" className="error-text">{getErrorMessage(error,'CRM could not be loaded or saved.')} <button className="quiet-button" onClick={retry}>Retry</button></p>;}
export default function CrmPage(){const {activeTenantId,activeBranchId}=useAppStore();return <Workspace key={activeTenantId+':'+activeBranchId}/>;}
function Workspace(){
 const {user}=useAppStore(),cache=useQueryClient(),scope=useOperationalScope();
 const manage=user?.permissions?.includes('crm.manage')??false;
 const [tab,setTab]=useState('leads'),[filters,setFilters]=useState<Record<string,string>>({}),[page,setPage]=useState(1),[view,setView]=useState('today'),[followPage,setFollowPage]=useState(1);
 const [detail,setDetail]=useRecordLink('lead');
 const [returnLead,setReturnLead]=useState<string|null>(null);
 const [editing,setEditing]=useState<Lead|null|undefined>(undefined),[follow,setFollow]=useState<{lead:Lead;record?:Followup}|null>(null),[conversion,setConversion]=useState<Lead|null>(null);
 const overview=useQuery({queryKey:['crm',...scope,'overview'],queryFn:({signal})=>get<{active:number;unassigned:number;today:number;overdue:number;timezone:string;businessDate:string;stages:(Stage&{leads:number})[]}>('overview',undefined,signal)});
 const stages=useQuery({queryKey:['crm',...scope,'stages'],queryFn:({signal})=>get<Stage[]>('stages',undefined,signal)});
 const choices=useQuery({queryKey:['crm',...scope,'assignees'],queryFn:({signal})=>get<Choice[]>('assignees',undefined,signal)});
 const leads=useQuery({queryKey:['crm',...scope,'leads',filters,page],queryFn:({signal})=>get<Page<Lead>>('leads',{...filters,page,limit:20},signal)});
 const actions=useQuery({queryKey:['crm',...scope,'followups',view,followPage],enabled:tab==='followups',queryFn:({signal})=>get<Page<Followup>>('followups',{view,page:followPage,limit:20},signal)});
 const selected=useQuery({queryKey:['crm',...scope,'detail',detail],enabled:Boolean(detail),queryFn:({signal})=>get<Lead>('leads/'+detail,undefined,signal)});
 const refresh=async()=>{await cache.invalidateQueries({queryKey:['crm']});await cache.invalidateQueries({queryKey:['form-values']});await cache.invalidateQueries({queryKey:['dashboard']});await cache.invalidateQueries({queryKey:['notification']});};
 const mutation=useMutation({mutationFn:async({path,body,method='post'}:{path:string;body:unknown;method?:'post'|'patch'})=>client[method]('/crm/'+path,body),onSuccess:refresh});
 const filter=(key:string,value:string)=>{setPage(1);setFilters(old=>{const next={...old};if(value)next[key]=value;else delete next[key];return next;});};
 const timezone=overview.data?.timezone??leads.data?.timezone;
 const closeForms=()=>{setEditing(undefined);setFollow(null);setConversion(null);if(returnLead)setDetail(returnLead);setReturnLead(null);};
 const done=async()=>{await refresh();closeForms();};
 return <div className="page-stack crm-workspace operations-workspace">
  <header className="page-heading"><div><h1>CRM & Follow-ups</h1><p>Turn enquiries into Customers. Conversion is not a sale.</p>{timezone&&<p className="muted">Selected branch · {timezone} · {overview.data?.businessDate}</p>}</div>{manage&&<button className="action-link" onClick={()=>setEditing(null)}>Create lead</button>}</header>
  {overview.isPending?<p role="status">Loading CRM summary…</p>:overview.isError?<LoadError error={overview.error} retry={()=>void overview.refetch()}/>:overview.data&&<section className="operations-summary relationship-attention" aria-label="CRM attention">{([['Active leads','active',''],['Due today','today','today'],['Overdue follow-ups','overdue','overdue'],['Unassigned leads','unassigned','unassigned']] as const).map(([label,key,attention])=><article className="panel" key={key}><h2>{label}</h2><strong className="stat-value">{overview.data[key]}</strong><p className="muted attention-description">{key==='active'||key==='unassigned'?'Active leads in this branch':'Pending actions for active leads; branch business date'}</p><button className="quiet-button" onClick={()=>{setTab('leads');setPage(1);setFilters(attention==='unassigned'?{status:'active',assignee:'unassigned'}:attention?{status:'active',attention}:{status:'active'});}}>View {label.toLowerCase()}</button></article>)}</section>}
  <nav className="record-actions" aria-label="CRM sections">{['leads','pipeline','followups','configuration'].filter(t=>t!=='configuration'||manage).map(t=><button className="quiet-button capitalize" aria-pressed={tab===t} key={t} onClick={()=>setTab(t)}>{t==='followups'?'Follow-ups':t==='configuration'?'Pipeline settings':t}</button>)}</nav>
  <details className="panel"><summary>How CRM works</summary><p>Leads represent potential Customers, not separate contacts or revenue. Stages describe progress. Follow-ups are manual next actions; Today and Overdue use your branch’s timezone. Choose “Convert” only when ready to create a Customer or explicitly link an existing one. Matching phone numbers never merge records. There are no scheduled reminders, campaigns or automatic charges.</p>{user?.permissions?.includes('fields.read')&&<Link className="action-link" to="/custom-fields">Lead Data & Forms</Link>}{user?.permissions?.includes('reports.read')&&<Link className="quiet-button" to="/reports">CRM reports</Link>}</details>
  {!manage&&<p className="muted">Read-only CRM access. Ask an organization administrator to review management permissions.</p>}
  {stages.isError&&<LoadError error={stages.error} retry={()=>void stages.refetch()}/>}
  {choices.isError&&<LoadError error={choices.error} retry={()=>void choices.refetch()}/>}
  {mutation.isError&&<LoadError error={mutation.error} retry={()=>{mutation.reset();void refresh();}}/>}
  {(tab==='leads'||tab==='pipeline')&&<>
   {tab==='pipeline'&&<label className="field table-mobile">Pipeline stage for this branch<select value={filters.stageId??''} onChange={e=>filter('stageId',e.target.value)}><option value="">All stages</option>{overview.data?.stages.map(s=><option key={s.id} value={s.id}>{s.name} · {s.leads} active leads{s.status==='archived'?' (archived)':''}</option>)}</select></label>}
   {tab==='pipeline'&&<section className="pipeline-stages table-desktop" aria-label="Pipeline stages">{overview.data?.stages.map(s=><article className="panel" key={s.id}><h2 className="break-words">{s.name}{s.status==='archived'?' (archived)':''}</h2><p>{s.leads} active leads</p><button className="quiet-button" aria-pressed={filters.stageId===s.id} onClick={()=>filter('stageId',s.id)}>View stage {s.name}</button></article>)}</section>}
   <details className="panel" open><summary>Lead filters</summary><div className="catalogue-grid mt-3">
    <Input label="Search leads" type="search" maxLength={200} value={filters.search??''} onChange={e=>filter('search',e.target.value)}/>
    <label className="field">Stage<select value={filters.stageId??''} onChange={e=>filter('stageId',e.target.value)}><option value="">All stages</option>{stages.data?.map(s=><option value={s.id} key={s.id}>{s.name}{s.status==='archived'?' (archived)':''}</option>)}</select></label>
    <label className="field">Lead status<select value={filters.status??''} onChange={e=>filter('status',e.target.value)}><option value="">All statuses</option>{['active','converted','lost','archived'].map(s=><option key={s}>{s}</option>)}</select></label>
    <label className="field">Assigned staff filter<select value={filters.assignee??''} onChange={e=>filter('assignee',e.target.value)}><option value="">All staff</option><option value="unassigned">Unassigned</option>{choices.data?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
    <Input label="Lead source filter" maxLength={100} value={filters.source??''} onChange={e=>filter('source',e.target.value)}/>
    <label className="field">Attention<select value={filters.attention??''} onChange={e=>filter('attention',e.target.value)}><option value="">All attention</option><option value="today">Due today</option><option value="overdue">Overdue</option><option value="upcoming">Upcoming</option></select></label>
    <label className="field">Sort leads<select value={filters.sort??'newest'} onChange={e=>filter('sort',e.target.value)}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="name">Name</option></select></label>
    <Input label="Created from (branch date)" type="date" value={filters.from??''} onChange={e=>filter('from',e.target.value)}/><Input label="Created through (branch date)" type="date" value={filters.to??''} onChange={e=>filter('to',e.target.value)}/>
   </div><CustomerReportFilter entity="lead" onApply={(field,value,operator)=>{setPage(1);setFilters(old=>{const next={...old};delete next.field;delete next.value;delete next.operator;return field?{...next,field,value,operator}:next;});}}/><button className="quiet-button mt-3" onClick={()=>{setFilters({});setPage(1);}}>Clear lead filters</button></details>
   <RelationshipRecords<Lead> title={tab==='pipeline'?'Selected-stage leads':'Lead directory'} data={leads.data?.data??[]} total={leads.data?.total??0} page={page} onPage={setPage} pending={leads.isPending} error={leads.error} retry={()=>void leads.refetch()}
    emptyTitle={Object.keys(filters).length?'No matching leads':'No leads yet'} emptyDescription={stages.data?.length?'Create an enquiry to start your pipeline.':'Set up pipeline stages explicitly before creating leads.'}
    columns={[{header:'Lead / company',accessor:'name',cell:({row:l})=><><h2 className="record-title">{l.name}</h2><p className="muted">{l.company??'No company'}</p></>},{header:'Stage',accessor:'stage_name'},{header:'Status',accessor:'status',cell:({row:l})=><StatusBadge>{l.status}</StatusBadge>},{header:'Assigned staff',accessor:'assignee_name',cell:({row:l})=><span>{l.assignee_name??'Unassigned'}{l.assignee_status&&l.assignee_status!=='active'?' (inactive assignment)':''}</span>},{header:'Actions',accessor:'id',cell:({row:l})=><LeadActions lead={l} manage={manage} view={()=>setDetail(l.id)} edit={()=>setEditing(l)}/>}]}
    card={l=><article className="panel mobile-record-card"><div className="operations-record-heading"><h2>{l.name}</h2><StatusBadge>{l.status}</StatusBadge></div><p>{l.stage_name}</p><p className="muted">{l.company??'No company'} · {l.assignee_name??'Unassigned'}{l.assignee_status&&l.assignee_status!=='active'?' (inactive assignment)':''}</p><LeadActions lead={l} manage={manage} view={()=>setDetail(l.id)} edit={()=>setEditing(l)}/></article>}/>

  </>}
  {tab==='configuration'&&manage&&<PipelineSettings stages={stages.data??[]} refresh={refresh}/>}
  {tab==='followups'&&<><label className="field">Follow-up view<select value={view} onChange={e=>{setView(e.target.value);setFollowPage(1);}}>{['today','overdue','upcoming','completed','all'].map(v=><option key={v}>{v}</option>)}</select></label><p className="muted">Today/Overdue/Upcoming include only pending actions on active leads. All preserves lost, archived and converted history.</p>{actions.isPending?<p role="status">Loading follow-ups…</p>:actions.isError?<LoadError error={actions.error} retry={()=>void actions.refetch()}/>:actions.data&&<>{!actions.data.data.length&&<p className="panel">No matching follow-ups.</p>}{actions.data.data.map(f=><FollowupCard key={f.id} record={f} timezone={actions.data.timezone} manage={manage} open={()=>setDetail(f.lead_id)} edit={async()=>setFollow({lead:await get<Lead>('leads/'+f.lead_id),record:f})} transition={status=>mutation.mutate({path:'followups/'+f.id+'/status',body:{status,expectedVersion:f.version}})} pending={mutation.isPending}/>)}<Pager page={followPage} total={actions.data.total} limit={20} onChange={setFollowPage}/></>}</>}
  {editing!==undefined&&<LeadEditor key={editing?.id??'new'} lead={editing} stages={stages.data??[]} choices={choices.data??[]} done={done} close={closeForms}/>}
  <AdvancedModal isOpen={Boolean(detail)} closeOnEscape={!follow&&!conversion} onClose={()=>setDetail(null)} title="Lead details" presentation="drawer" size="xl">{selected.isPending?<p>Loading lead…</p>:selected.isError?<LoadError error={selected.error} retry={()=>void selected.refetch()}/>:selected.data&&timezone&&<LeadDetails key={selected.data.id} lead={selected.data} timezone={timezone} stages={stages.data??[]} choices={choices.data??[]} manage={manage} refresh={refresh} edit={()=>{setDetail(null);setEditing(selected.data!);}} follow={()=>{setReturnLead(selected.data!.id);setDetail(null);setFollow({lead:selected.data!});}} convert={()=>{setReturnLead(selected.data!.id);setDetail(null);setConversion(selected.data!);}}/>}</AdvancedModal>
  {follow&&timezone&&<FollowupEditor key={follow.record?.id??follow.lead.id} lead={follow.lead} record={follow.record} timezone={timezone} choices={choices.data??[]} done={done} close={closeForms}/>}
  {conversion&&<Conversion key={conversion.id} lead={conversion} done={done} close={closeForms}/>}
 </div>;
}
function LeadEditor({lead,stages,choices,done,close}:{lead:Lead|null;stages:Stage[];choices:Choice[];done:()=>Promise<void>;close:()=>void}){
 const fields=useDynamicForm('lead',lead?.id),[form,setForm]=useState({name:lead?.name??'',company:lead?.company??'',phone:lead?.phone??'',email:lead?.email??'',source:lead?.source??'',pipelineStageId:lead?.pipeline_stage_id??stages.find(s=>s.status==='active')?.id??'',assignedMembershipId:lead?.assigned_membership_id??'',notes:lead?.notes??''});
 const [initial]=useState(()=>JSON.stringify(form));
 const set=(key:keyof typeof form,value:string)=>setForm(old=>({...old,[key]:value}));
 const save=useMutation({mutationFn:()=>client[lead?'patch':'post']('/crm/leads'+(lead?'/'+lead.id:''),{...form,phone:form.phone||null,email:form.email||null,assignedMembershipId:form.assignedMembershipId||null,customFields:fields.patch,...(lead?{expectedVersion:lead.version}:{})}),onSuccess:done});
 const phoneError=form.phone&&!normalizePhone(form.phone)?'Enter a valid phone or leave it blank.':undefined;
 const activeStages=stages.filter(s=>s.status==='active'||s.id===lead?.pipeline_stage_id);
 return <OperationForm open title={lead?'Edit lead':'Create lead'} onClose={close} dirty={JSON.stringify(form)!==initial||Object.keys(fields.patch).length>0} valid={fields.ready&&fields.valid&&!fields.error&&Boolean(form.name.trim()&&form.pipelineStageId)&&!phoneError&&optionalEmailValid(form.email)&&!uncertainWrite(save.error)} busy={save.isPending} error={save.error} confirmLabel="Save lead" onConfirm={()=>save.mutate()} retryAdvice="No automatic retry is safe after an uncertain creation. Check the Lead directory before starting again." review={<><h3>{form.name}</h3><p>{form.company||'No company'} · {form.phone||'No phone'} · {form.email||'No email'}</p><p>Stage: {stages.find(s=>s.id===form.pipelineStageId)?.name}</p><p>Assigned: {choices.find(c=>c.id===form.assignedMembershipId)?.name??'Unassigned'}</p><p>{form.source||'No source'} · {form.notes||'No notes'}</p><p>Custom fields are included using the current Lead layout.</p>{fields.schema&&<DynamicForm schema={fields.schema} values={fields.values} readOnly/>}</>}><div className="page-stack">
  {fields.error&&<LoadError error={fields.error} retry={fields.retry}/>}
  {fields.schema&&<DynamicForm schema={fields.schema} values={fields.values} onChange={fields.change} builtins={{
   name:<Input label="Lead name" required maxLength={200} value={form.name} onChange={e=>set('name',e.target.value)}/>,
   pipelineStageId:<label className="field">Pipeline stage<select required value={form.pipelineStageId} onChange={e=>set('pipelineStageId',e.target.value)}><option value="">Choose stage</option>{activeStages.map(s=><option key={s.id} value={s.id} disabled={s.status==='archived'&&s.id!==lead?.pipeline_stage_id}>{s.name}{s.status==='archived'?' (archived)':''}</option>)}</select></label>,
   company:<Input label="Company (optional)" maxLength={200} value={form.company} onChange={e=>set('company',e.target.value)}/>,
   phone:<PhoneInput label="Lead phone (optional)" value={form.phone} error={phoneError} onChange={v=>set('phone',v)}/>,
   email:<Input label="Lead email (optional)" type="email" maxLength={254} value={form.email} onChange={e=>set('email',e.target.value)}/>,
   source:<Input label="Lead source (optional)" maxLength={100} value={form.source} onChange={e=>set('source',e.target.value)}/>,
   assignedMembershipId:<Assignee label="Assigned staff" value={form.assignedMembershipId} choices={choices} historical={lead?.assignee_name} onChange={v=>set('assignedMembershipId',v)}/>,
   notes:<label className="field">Lead notes<textarea maxLength={2000} value={form.notes} onChange={e=>set('notes',e.target.value)}/></label>
  }}/>}
  {save.isError&&<LoadError error={save.error} retry={()=>save.reset()}/>}
 </div></OperationForm>;
}
function LeadActions({lead,manage,view,edit}:{lead:Lead;manage:boolean;view:()=>void;edit:()=>void}){return <div className="record-actions"><button className="quiet-button" onClick={view}>View {lead.name}</button>{manage&&lead.status==='active'&&<button className="quiet-button" onClick={edit}>Edit {lead.name}</button>}</div>;}
function Assignee({label,value,choices,historical,onChange}:{label:string;value:string;choices:Choice[];historical?:string|null;onChange:(v:string)=>void}){return <label className="field">{label}<select value={value} onChange={e=>onChange(e.target.value)}><option value="">Unassigned</option>{value&&!choices.some(c=>c.id===value)&&<option value={value}>{historical??'Previous staff'} (inactive)</option>}{choices.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>;}
function LeadDetails({lead,timezone,stages,choices,manage,refresh,edit,follow,convert}:{lead:Lead;timezone:string;stages:Stage[];choices:Choice[];manage:boolean;refresh:()=>Promise<void>;edit:()=>void;follow:()=>void;convert:()=>void}){
 const [terminal,setTerminal]=useState<string|null>(null);
 const [historyPage,setHistoryPage]=useState(1),[followPage,setFollowPage]=useState(1),[note,setNote]=useState(''),[reason,setReason]=useState(''),{user}=useAppStore();
 const scope=useOperationalScope(),history=useQuery({queryKey:['crm',...scope,'activity',lead.id,historyPage],queryFn:({signal})=>get<Activity[]>('leads/'+lead.id+'/activity',{page:historyPage},signal)});
 const actions=useQuery({queryKey:['crm',...scope,'lead-followups',lead.id,followPage],queryFn:({signal})=>get<Page<Followup>>('followups',{leadId:lead.id,page:followPage,limit:20},signal)});
 const save=useMutation({mutationFn:({path,body,method='post'}:{path:string;body:unknown;method?:'post'|'patch'})=>client[method]('/crm/'+path,body),onSuccess:async(_data,variables)=>{await refresh();if(variables.path.endsWith('/notes'))setNote('');}});
 const status=(status:string)=>save.mutate({path:'leads/'+lead.id+'/status',body:{expectedVersion:lead.version,status,...(reason?{reason}:{})}});
 return <div className="page-stack"><h2 className="font-semibold break-words">{lead.name}</h2><div className="record-actions"><StatusBadge>{lead.status}</StatusBadge><StatusBadge tone="info">{lead.stage_name}</StatusBadge><span>{lead.branch_name}</span></div><p className="break-words">{lead.company??'No company'} · {lead.phone??'No phone'} · {lead.email??'No email'}</p><p>{lead.source??'No source'} · {lead.assignee_name??'Unassigned'}{lead.assignee_status&&lead.assignee_status!=='active'?' (inactive; choose active staff to reassign)':''}</p><p className="whitespace-pre-wrap break-words">{lead.notes??'No lead notes'}</p>{lead.lost_reason&&<p className="break-words">Lost reason: {lead.lost_reason}</p>}
  <DetailSection title="Lead information"><p>Contact: {lead.phone??'No phone'} · {lead.email??'No email'}</p><p>Source: {lead.source??'Not provided'} · Company: {lead.company??'Not provided'}</p><p>Assigned: {lead.assignee_name??'Unassigned'}</p></DetailSection><DetailSection title="Custom fields"><EntityFields entity="lead" id={lead.id}/></DetailSection>
  {lead.converted_customer_id&&<p>Converted to {lead.customer_name??'Customer'}{user?.permissions?.includes('customers.read')&&<Link className="quiet-button" to={'/customers?customer='+encodeURIComponent(lead.converted_customer_id)}>Open Customer</Link>}. This did not record a sale.</p>}
  {manage&&lead.status==='active'&&<><div className="record-actions"><button className="quiet-button" onClick={edit}>Edit lead</button><button className="action-link" onClick={follow}>Add follow-up</button>{(user?.permissions?.includes('customers.read')||user?.permissions?.includes('customers.manage'))&&<button className="quiet-button" onClick={convert}>Convert to Customer</button>}</div>
   <label className="field">Move stage<select disabled={save.isPending} value={lead.pipeline_stage_id} onChange={e=>save.mutate({path:'leads/'+lead.id,method:'patch',body:{expectedVersion:lead.version,pipelineStageId:e.target.value}})}>{stages.filter(s=>s.status==='active'||s.id===lead.pipeline_stage_id).map(s=><option value={s.id} key={s.id}>{s.name}{s.status==='archived'?' (archived)':''}</option>)}</select></label>
   <Assignee label="Reassign lead" value={lead.assigned_membership_id??''} choices={choices} historical={lead.assignee_name} onChange={assigned=>{if(!save.isPending)save.mutate({path:'leads/'+lead.id,method:'patch',body:{expectedVersion:lead.version,assignedMembershipId:assigned||null}});}}/>
   <label className="field">Add activity note<textarea value={note} maxLength={2000} onChange={e=>setNote(e.target.value)}/></label><button className="quiet-button" disabled={!note.trim()||save.isPending} onClick={()=>save.mutate({path:'leads/'+lead.id+'/notes',body:{expectedVersion:lead.version,note}})}>Add note</button>
   <Input label="Lost reason" maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/><button className="quiet-button" disabled={!reason.trim()||save.isPending} onClick={()=>setTerminal('lost')}>Mark lost</button><button className="quiet-button" disabled={save.isPending} onClick={()=>setTerminal('archived')}>Archive lead</button>
  </>}
  {manage&&['lost','archived'].includes(lead.status)&&<button className="action-link" disabled={save.isPending} onClick={()=>setTerminal('active')}>Reactivate lead</button>}
  {terminal&&<section className="panel page-stack" aria-label="Lead lifecycle confirmation"><h3>Review Lead lifecycle change</h3><p>{lead.name} → {terminal}. All history remains. {terminal==='lost'?'Reason: '+reason:''}</p><div className="record-actions"><button className="quiet-button" disabled={save.isPending} onClick={()=>setTerminal(null)}>Keep current status</button><button className="action-link" disabled={save.isPending||Boolean(save.error)} onClick={()=>{status(terminal);setTerminal(null);}}>Confirm Lead status</button></div></section>}
  {save.isError&&<LoadError error={save.error} retry={()=>{save.reset();void refresh();}}/>}
  <h3 className="font-semibold">Follow-ups</h3>{actions.isError?<LoadError error={actions.error} retry={()=>void actions.refetch()}/>:actions.isPending?<p>Loading follow-ups…</p>:<>{!actions.data.data.length&&<p>No follow-ups yet.</p>}{actions.data.data.map(f=><FollowupCard key={f.id} record={f} timezone={timezone} manage={manage} pending={save.isPending} transition={status=>save.mutate({path:'followups/'+f.id+'/status',body:{status,expectedVersion:f.version}})}/>)}<Pager page={followPage} total={actions.data.total} limit={20} onChange={setFollowPage}/></>}
  <h3 className="font-semibold">Activity history</h3>{history.isError?<LoadError error={history.error} retry={()=>void history.refetch()}/>:history.isPending?<p>Loading activity…</p>:<><ol className="page-stack">{history.data.map(e=><li className="panel break-words" key={e.id}><p>{activityLabels[e.action]??'CRM activity'} · {e.actor_name}</p><time>{displayTime(e.occurred_at,timezone)} {timezone}</time>{e.stage_name&&<p>Stage: {e.stage_name}</p>}{e.assignee_name&&<p>Assigned staff: {e.assignee_name}</p>}{e.customer_name&&<p>Customer: {e.customer_name}</p>}{e.note&&<p className="whitespace-pre-wrap">{e.note}</p>}</li>)}</ol><div className="pagination"><button className="quiet-button" disabled={historyPage===1} onClick={()=>setHistoryPage(p=>p-1)}>Earlier page</button><span>Activity page {historyPage}</span><button className="quiet-button" disabled={history.data.length<25} onClick={()=>setHistoryPage(p=>p+1)}>Older activity</button></div></>}
 </div>;
}
function FollowupCard({record:f,timezone,manage,pending=false,transition,open,edit}:{record:Followup;timezone:string;manage:boolean;pending?:boolean;transition:(status:string)=>void;open?:()=>void;edit?:()=>void}){const [confirm,setConfirm]=useState<string|null>(null);return <article className="panel record-card"><h3 className="font-semibold break-words">{f.subject}</h3><p className="break-words">{f.lead_name} · {f.type} · {f.status}</p><p>Due: {displayTime(f.due_at,timezone)} {timezone}</p><p>{f.assignee_name??'Unassigned'}{f.assignee_status&&f.assignee_status!=='active'?' (inactive assignment)':''}</p>{f.note&&<p className="whitespace-pre-wrap break-words">{f.note}</p>}{f.completed_at&&<p>Completed: {displayTime(f.completed_at,timezone)}</p>}<div className="record-actions">{open&&<button className="quiet-button" onClick={open}>Open lead</button>}{manage&&f.status==='pending'&&<>{edit&&<button className="quiet-button" onClick={edit}>Edit follow-up</button>}<button className="action-link" disabled={pending} onClick={()=>setConfirm('completed')}>Complete follow-up</button><button className="quiet-button" disabled={pending} onClick={()=>setConfirm('cancelled')}>Cancel follow-up</button></>}</div>{confirm&&f.status==='pending'&&<section className="page-stack" aria-label="Follow-up confirmation"><p>Mark {f.subject} as {confirm}? This terminal action retains history and cannot be reopened.</p><div className="record-actions"><button className="quiet-button" disabled={pending} onClick={()=>setConfirm(null)}>Keep pending</button><button className="action-link" disabled={pending} onClick={()=>{transition(confirm);setConfirm(null);}}>Confirm follow-up status</button></div></section>}</article>;}
function FollowupEditor({lead,record,timezone,choices,done,close}:{lead:Lead;record?:Followup;timezone:string;choices:Choice[];done:()=>Promise<void>;close:()=>void}){
 const [form,setForm]=useState({type:record?.type??'call',subject:record?.subject??'',note:record?.note??'',localDue:record?localDateTime(record.due_at,timezone):'',assignedMembershipId:record?.assigned_membership_id??lead.assigned_membership_id??''});
 const [initial]=useState(()=>JSON.stringify(form));
 const save=useMutation({mutationFn:()=>client[record?'patch':'post']('/crm/followups'+(record?'/'+record.id:''),{...form,assignedMembershipId:form.assignedMembershipId||null,...(record?{expectedVersion:record.version}:{leadId:lead.id})}),onSuccess:done});
 return <OperationForm open title={record?'Edit follow-up':'Add follow-up'} onClose={close} dirty={JSON.stringify(form)!==initial} valid={Boolean(form.subject.trim()&&form.localDue)&&!uncertainWrite(save.error)} busy={save.isPending} error={save.error} confirmLabel="Save follow-up" onConfirm={()=>save.mutate()} retryAdvice="Check the Lead follow-ups before starting another action if the result is uncertain." review={<><h3>{form.subject}</h3><p>{lead.name} · {form.type}</p><p>Due: {form.localDue.replace('T',' ')} {timezone}</p><p>Assigned: {choices.find(c=>c.id===form.assignedMembershipId)?.name??'Unassigned'}</p><p>{form.note||'No note'}</p><p>Manual action only; no automatic message or reminder is sent.</p></>}><div className="page-stack"><p className="break-words">{lead.name} · Due time is {timezone}, not your computer’s timezone.</p><label className="field">Follow-up type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{['call','meeting','task','note','other'].map(t=><option key={t}>{t}</option>)}</select></label><Input label="Follow-up subject" required maxLength={200} value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/><Input label="Due date and time" type="datetime-local" required value={form.localDue} onChange={e=>setForm({...form,localDue:e.target.value})}/><Assignee label="Follow-up assigned staff" value={form.assignedMembershipId} choices={choices} historical={record?.assignee_name??lead.assignee_name} onChange={v=>setForm({...form,assignedMembershipId:v})}/><label className="field">Follow-up note<textarea maxLength={2000} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label>{save.isError&&<LoadError error={save.error} retry={()=>save.reset()}/>}</div></OperationForm>;
}
function Conversion({lead,done,close}:{lead:Lead;done:()=>Promise<void>;close:()=>void}){
 const permissions=useAppStore(s=>s.user?.permissions??[]),canNew=permissions.includes('customers.manage'),canExisting=permissions.includes('customers.read');
 const [mode,setMode]=useState(canNew?'new':'existing'),[search,setSearch]=useState(''),[customerId,setCustomerId]=useState(''),[name,setName]=useState(lead.name),[phone,setPhone]=useState(lead.phone??''),[notes,setNotes]=useState(lead.notes??'');
 const fields=useDynamicForm('customer',null,canNew),scope=useOperationalScope();
 const customers=useQuery({queryKey:['crm-conversion-customers',...scope,search],enabled:mode==='existing'&&canExisting,queryFn:async({signal})=>(await client.get<{data:{id:string;name:string;phone:string|null;status:string}[]}>('/customers',{signal,params:{search,limit:100}})).data.data});
 const save=useMutation({mutationFn:()=>client.post('/crm/leads/'+lead.id+'/convert',mode==='new'?{mode,expectedVersion:lead.version,customer:{name,phone:phone||null,notes:notes||null,customFields:fields.patch}}:{mode,expectedVersion:lead.version,customerId}),onSuccess:async()=>{await done();}});
 return <OperationForm open title="Convert lead to Customer" onClose={close} dirty valid={!uncertainWrite(save.error)&&(mode==='new'?(fields.ready&&fields.valid&&!fields.error&&Boolean(name.trim())&&!(phone&&!normalizePhone(phone))):Boolean(customerId))} busy={save.isPending} error={save.error} confirmLabel="Confirm conversion" onConfirm={()=>save.mutate()} retryAdvice="Reload the Lead to check its permanent Customer link before another conversion attempt." review={<><h3>Confirm permanent Customer link</h3><p>Lead: {lead.name}</p><p>{mode==='new'?'Create a new canonical Customer':'Link the explicitly selected existing Customer'}: {mode==='new'?name:customers.data?.find(c=>c.id===customerId)?.name}</p>{mode==='new'&&<p>{phone||'No phone'} · {notes||'No notes'} · Required Customer fields included.</p>}{mode==='new'&&fields.schema&&<DynamicForm schema={fields.schema} values={fields.values} readOnly/>}<p>No matching or merging by contact data. This creates no Sale, invoice or payment. The link is permanent.</p></>}><div className="page-stack">
  <p>No automatic matching or merging by phone/email. Conversion is atomic and permanent.</p><label className="field">Conversion mode<select value={mode} onChange={e=>setMode(e.target.value)}>{canNew&&<option value="new">Create new Customer</option>}{canExisting&&<option value="existing">Link explicitly selected Customer</option>}</select></label>
  {mode==='new'?<>{fields.error&&<LoadError error={fields.error} retry={fields.retry}/>}<p>Collect all currently required Customer information.</p>{fields.schema&&<DynamicForm schema={fields.schema} values={fields.values} onChange={fields.change} builtins={{name:<Input label="Customer name" required maxLength={200} value={name} onChange={e=>setName(e.target.value)}/>,phone:<PhoneInput label="Customer phone (optional)" value={phone} onChange={setPhone}/>,notes:<label className="field">Customer notes<textarea maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label>}}/>}</>:<><Input label="Search existing Customers" value={search} maxLength={200} onChange={e=>{setSearch(e.target.value);setCustomerId('');}}/>{customers.isPending?<p>Loading Customers…</p>:customers.isError?<LoadError error={customers.error} retry={()=>void customers.refetch()}/>:<label className="field">Existing Customer<select required value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Choose Customer explicitly</option>{customers.data.filter(c=>c.status==='active').map(c=><option key={c.id} value={c.id}>{c.name} · {c.phone??'No phone'}</option>)}</select></label>}<p className="muted">Search is bounded to 100 matches; narrow your search if needed.</p></>}
 </div></OperationForm>;
}
function PipelineSettings({stages,refresh}:{stages:Stage[];refresh:()=>Promise<void>}){
 const [editing,setEditing]=useState<Stage|null|undefined>(undefined),[initial,setInitial]=useState(''),[form,setForm]=useState({name:'',description:'',position:0,status:'active'});
 const save=useMutation({mutationFn:()=>client[editing?'patch':'post']('/crm/stages'+(editing?'/'+editing.id:''),{...form,...(editing?{expectedVersion:editing.version}:{})}),onSuccess:async()=>{await refresh();setEditing(undefined);}});
 const setup=useMutation({mutationFn:()=>client.post('/crm/stages/recommended',{}),onSuccess:refresh});
 const open=(stage:Stage|null)=>{save.reset();setEditing(stage);setInitial(JSON.stringify(stage?{name:stage.name,description:stage.description,position:stage.position,status:stage.status}:{name:'',description:'',position:Math.min(stages.length,49),status:'active'}));setForm(stage?{name:stage.name,description:stage.description,position:stage.position,status:stage.status}:{name:'',description:'',position:Math.min(stages.length,49),status:'active'});};
 return <section className="page-stack"><h2 className="font-semibold">Pipeline settings</h2><p>Organization-wide stage names and order. Archiving preserves lead history; new assignments cannot use archived stages. Stage order is explicit; no probabilities or revenue forecasts.</p>{!stages.length&&<button className="action-link" disabled={setup.isPending} onClick={()=>setup.mutate()}>Create recommended stages</button>}<button className="quiet-button" disabled={stages.length>=50} onClick={()=>open(null)}>Add stage</button>{setup.isError&&<LoadError error={setup.error} retry={()=>setup.reset()}/>}<div className="catalogue-grid">{stages.map(s=><article className="panel record-card" key={s.id}><h3 className="font-semibold break-words">{s.name}</h3><p>Position {s.position+1} · {s.status}</p><p className="break-words">{s.description}</p><button className="quiet-button" onClick={()=>open(s)}>Edit stage {s.name}</button></article>)}</div>
  <OperationForm open={editing!==undefined} title={editing?'Edit pipeline stage':'Add pipeline stage'} onClose={()=>setEditing(undefined)} dirty={JSON.stringify(form)!==initial} valid={Boolean(form.name.trim())&&Number.isInteger(form.position)&&form.position>=0&&form.position<=49&&!uncertainWrite(save.error)} busy={save.isPending} error={save.error} confirmLabel="Save stage" onConfirm={()=>save.mutate()} retryAdvice="Check current stage history and version before another attempt." review={<><h3>{form.name}</h3><p>{form.description||'No description'} · Position {form.position+1} · {form.status}</p><p>Organization-wide configuration. Archiving retains all historical Lead meanings.</p></>}><div className="page-stack"><Input label="Stage name" required maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Input label="Stage description" maxLength={500} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><Input label="Stage order (0–49)" required type="number" min={0} max={49} value={form.position} onChange={e=>setForm({...form,position:Number(e.target.value)})}/><label className="field">Stage status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="archived">Archived</option></select></label>{save.isError&&<LoadError error={save.error} retry={()=>save.reset()}/>}</div></OperationForm>
 </section>;
}
