import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import { type RoleData, type Branch } from '../Settings/OrganizationPage';
import { useOrganizationData } from '../../hooks/useOrganizationData';
import { useAppStore } from '../../store/useAppStore';
import { client, restoreSession } from '../../api/client';
import { getErrorMessage } from '../../api/errors';
import { Input } from '../../components/ui/Input';
import { AdvancedModal } from '../../components/ui/AdvancedModal';
import { useDynamicForm } from '../../hooks/useDynamicForm';
import { DynamicForm } from '../../components/forms/DynamicForm';
import { EntityFields } from '../../components/forms/EntityFields';
interface Member {id:string;name:string;phone:string;email:string|null;role:string;roleName:string|null;customRoleId:string|null;membershipId:string;status:string;branchIds:string[];branchNames:string[];version:number;updated_at:string}
export default function StaffAccessCards() {
  const user=useAppStore(s=>s.user); const grants=user?.permissions??[]; const manage=grants.includes('staff.manage');
  const [search,setSearch]=useState('');const [editing,setEditing]=useState<Member|null>(null);
  const [detail,setDetail]=useState<Member|null>(null);
  const fields=useDynamicForm('membership',editing?.membershipId,Boolean(editing));
  const members=useOrganizationData<Member[]>('/members?search='+encodeURIComponent(search));
  const branches=useOrganizationData<Branch[]>('/branches',manage&&grants.includes('branches.read'));
  const roles=useOrganizationData<RoleData>('/roles',manage&&grants.includes('roles.read'));
  const cache=useQueryClient(); const save=useMutation({mutationFn:async()=>{
    if(editing) await client.patch('/members/'+editing.membershipId,{customFields:fields.patch,role:editing.role,customRoleId:editing.customRoleId,status:editing.status,branchIds:editing.branchIds,version:editing.version});
  },onSuccess:async()=>{if(editing?.id===user?.id){const tenant=useAppStore.getState().activeTenantId;if(tenant)useAppStore.getState().establishSession(await restoreSession({organizationId:tenant}));}setEditing(null);void cache.invalidateQueries({queryKey:['form-values']});void cache.invalidateQueries({queryKey:['organization-admin']});toast.success('Staff access saved');}});
  return <><Input label="Search staff" value={search} maxLength={200} onChange={e=>setSearch(e.target.value)}/>{members.isPending&&<p role="status">Loading memberships…</p>}{members.isError&&<p role="alert">Memberships unavailable. <button onClick={()=>void members.refetch()}>Retry</button></p>}<div className="catalogue-grid">{members.data?.length===0&&<p>No matching staff.</p>}{members.data?.map(m=><article className="panel record-card" key={m.membershipId}><h2>{m.name}</h2><p>{m.phone}</p><p>{m.email??'No verified email'}</p><p className="muted">{m.roleName??m.role} · {m.status}</p><p>{m.branchNames.join(', ')||'No assigned branches'}</p><p className="muted">Updated {new Date(m.updated_at).toLocaleString()}</p>{manage&&<button className="quiet-button" onClick={()=>{fields.reset();save.reset();setEditing({...m,branchIds:m.branchIds.filter(id=>branches.data?.some(b=>b.id===id&&b.status==='active'))});}}>{m.id===user?.id?'My branch assignments':`Edit ${m.name}`}</button>}<button className="quiet-button" onClick={()=>setDetail(m)}>Details</button></article>)}</div>
    <AdvancedModal isOpen={Boolean(editing)} onClose={()=>setEditing(null)} title="Staff access" actions={<button className="action-link" disabled={save.isPending||!fields.ready||!fields.valid||Boolean(fields.error)||!editing?.branchIds.length} onClick={()=>{if(window.confirm('Save organization-local staff access? Other memberships and identity are preserved.'))save.mutate();}}>Save staff access</button>}>{editing&&<div className="page-stack"><p>{editing.name}</p>{fields.schema&&<DynamicForm schema={fields.schema} values={fields.values} onChange={fields.change} builtins={{role:(<label>Role<select aria-label="Staff role" disabled={editing.role==='owner'||editing.id===user?.id} className="w-full rounded-lg border p-3" value={editing.customRoleId?'custom:'+editing.customRoleId:editing.role} onChange={e=>setEditing({...editing,role:e.target.value.startsWith('custom:')?'staff':e.target.value,customRoleId:e.target.value.startsWith('custom:')?e.target.value.slice(7):null})}>{(roles.data?.system??[]).filter(r=>(r.name!=='owner'||editing.role==='owner')&&r.permissions.every(p=>grants.includes(p))).map(r=><option key={r.name} value={r.name}>{r.name}</option>)}{roles.data?.custom.filter(r=>r.status==='active'&&r.permissions.every(p=>grants.includes(p))).map(r=><option key={r.id} value={'custom:'+r.id}>{r.name}</option>)}</select></label>),status:(<label>Status<select aria-label="Membership status" disabled={editing.role==='owner'||editing.id===user?.id} className="w-full rounded-lg border p-3" value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}><option value="active">Active</option><option value="inactive">Suspended</option><option value="revoked">Revoked</option></select></label>),branchIds:(<fieldset className="page-stack"><legend>Assigned branches</legend>{branches.data?.filter(b=>b.status==='active').map(b=><label className="flex gap-2" key={b.id}><input type="checkbox" checked={editing.branchIds.includes(b.id)} onChange={e=>setEditing({...editing,branchIds:e.target.checked?[...editing.branchIds,b.id]:editing.branchIds.filter(id=>id!==b.id)})}/>{b.name}</label>)}</fieldset>)}}/>}{fields.error&&<p role="alert">Fields unavailable. <button onClick={fields.retry}>Retry fields</button></p>}{save.isError&&<p role="alert">{getErrorMessage(save.error,'Could not save access.')}</p>}</div>}</AdvancedModal><AdvancedModal isOpen={Boolean(detail)} onClose={()=>setDetail(null)} title="Staff details">{detail&&<EntityFields entity="membership" id={detail.membershipId}/>}</AdvancedModal></>;
}
