import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { client } from '../../api/client';
import { getErrorMessage } from '../../api/errors';
import { useAppStore } from '../../store/useAppStore';
import { useDynamicForm } from '../../hooks/useDynamicForm';
import { AdvancedModal } from '../../components/ui/AdvancedModal';
import { Input } from '../../components/ui/Input';
import { DynamicForm } from '../../components/forms/DynamicForm';
import { entities, types, formSections, type Definition, type FieldEntity, type Section } from '../../components/forms/formSchema';

const blank=():Definition=>({id:'',key:'',label:'',help:'',field_type:'text',status:'active',required:false,searchable:false,filterable:false,reportable:false,default_value:null,version:1,options:[]});
const move=<T,>(list:T[],index:number,delta:number)=>{const copy=[...list];if(index+delta>=0&&index+delta<copy.length)[copy[index],copy[index+delta]]=[copy[index+delta],copy[index]];return copy;};
export default function CustomFieldsPage() {
 const [entity,setEntity]=useState<FieldEntity>('customer'),[editing,setEditing]=useState<Definition|null>(null),[layout,setLayout]=useState<Section[]|null>(null),[preview,setPreview]=useState<'desktop'|'mobile'|null>(null);
 const form=useDynamicForm(entity,null),cache=useQueryClient(),manage=useAppStore(s=>s.user?.permissions?.includes('fields.manage'));
 const schema=form.schema;
 const refresh=async()=>{await cache.invalidateQueries({queryKey:['form-schema']});await cache.invalidateQueries({queryKey:['form-values']});};
 const save=useMutation({mutationFn:async()=>{
  if(!editing) return;
  const body={key:editing.key,label:editing.label,help:editing.help,fieldType:editing.field_type,status:editing.status,required:editing.required,searchable:editing.searchable,filterable:editing.filterable,reportable:editing.reportable,defaultValue:editing.default_value,options:editing.options.map(o=>({...(o.id?{id:o.id}:{}),key:o.key,label:o.label,status:o.status})),...(editing.id?{version:editing.version}:{})};
  return editing.id?client.put(`/forms/${entity}/definitions/${editing.id}`,body):client.post(`/forms/${entity}/definitions`,body);
 },onSuccess:async()=>{await refresh();setEditing(null);setLayout(null);}});
 const saveLayout=useMutation({mutationFn:async(reset:boolean)=>{
  const sections=(reset?[{id:crypto.randomUUID(),title:'',fields:[...schema!.builtins,...schema!.definitions.filter(f=>f.status==='active')].map(f=>({key:f.key,visible:true}))}]:layout??formSections(schema!)).map(s=>({...s,id:s.id==='unplaced'?crypto.randomUUID():s.id,title:s.title||'General'}));
  return client[reset?'post':'put'](`/forms/${entity}/layout${reset?'/reset':''}`,{version:schema!.version,sections});
 },onSuccess:async()=>{await refresh();setLayout(null);}});
 const sections=layout??(schema?formSections(schema):[]);
 const editLayout=(operation:(s:Section[])=>Section[])=>setLayout(operation(sections.map(s=>({...s,fields:s.fields.map(f=>({...f}))}))));
 const error=save.error??saveLayout.error??form.error;
 const names=new Map([...(schema?.builtins??[]),...(schema?.definitions??[])].map(f=>[f.key,f.label]));
 return <div className="page-stack dynamic-fields-admin"><header className="page-heading"><div><h1>Data & Forms</h1><p>Organization fields inherit the record’s permissions. Do not store credentials or differently restricted sensitive information here.</p></div></header>
  <label className="field">Record type<select value={entity} onChange={e=>{setEntity(e.target.value as FieldEntity);setLayout(null);setEditing(null);setPreview(null);save.reset();saveLayout.reset();}}>{entities.map(e=><option key={e} value={e}>{e.replace('_',' ')}</option>)}</select></label>
  {error&&<p role="alert" className="error-text">{getErrorMessage(error,'Form configuration unavailable.')} <button onClick={form.retry}>Reload configuration</button></p>}
  {!schema?<p role="status">Loading form schema…</p>:<><div className="record-actions">{manage&&<button className="action-link" onClick={()=>{save.reset();setEditing(blank());}}>Add field</button>}<button className="quiet-button" onClick={()=>setPreview('desktop')}>Desktop preview</button><button className="quiet-button" onClick={()=>setPreview('mobile')}>Mobile preview</button></div>
   <div className="catalogue-grid">{schema.definitions.map(field=><article className="panel record-card" key={field.id}><h2>{field.label}</h2><p>{field.key} · {field.field_type} · {field.status}</p><p>{[field.required?'Required':'Optional',field.searchable?'Searchable':null,field.filterable?'Filterable':null,field.reportable?'Reportable':null].filter(Boolean).join(' · ')}</p>{manage&&<button className="quiet-button" onClick={()=>{save.reset();setEditing({...field,options:field.options.map(o=>({...o}))});}}>Edit {field.label}</button>}</article>)}</div>
   <h2 className="font-semibold">Form layout</h2><p className="muted">One shared create/edit/view ordering. Required built-ins and active required custom fields stay visible. New fields appear in Additional information until placed.</p>
   {sections.map((section,index)=><section className="panel page-stack" key={section.id}><Input label={`Section ${index+1} title`} disabled={!manage} maxLength={100} value={section.title} onChange={e=>editLayout(s=>s.map((x,i)=>i===index?{...x,title:e.target.value}:x))}/><label className="field">Section {index+1} status<select disabled={!manage||section.fields.length>0} value={section.status??'active'} onChange={e=>editLayout(s=>s.map((x,i)=>i===index?{...x,status:e.target.value as 'active'|'archived'}:x))}><option value="active">Active</option><option value="archived">Archived (move all fields first)</option></select></label>{manage&&<div className="record-actions"><button className="quiet-button" disabled={index===0} onClick={()=>editLayout(s=>move(s,index,-1))}>Move section {index+1} up</button><button className="quiet-button" disabled={index===sections.length-1} onClick={()=>editLayout(s=>move(s,index,1))}>Move section {index+1} down</button></div>}
    {section.fields.map((placement,position)=>{const required=schema.builtins.some(b=>b.key===placement.key&&b.required)||schema.definitions.some(f=>f.key===placement.key&&f.required&&f.status==='active');return <div className="page-stack border-t pt-3" key={placement.key}><p>{names.get(placement.key)??placement.key}</p><div className="flex flex-wrap gap-2">{manage&&<><button className="quiet-button" disabled={!position} onClick={()=>editLayout(s=>s.map((x,i)=>i===index?{...x,fields:move(x.fields,position,-1)}:x))}>Move {names.get(placement.key)} up</button><button className="quiet-button" disabled={position===section.fields.length-1} onClick={()=>editLayout(s=>s.map((x,i)=>i===index?{...x,fields:move(x.fields,position,1)}:x))}>Move {names.get(placement.key)} down</button><label>Section for {names.get(placement.key)}<select value={section.id} onChange={e=>editLayout(s=>s.map(x=>({...x,fields:x.id===e.target.value?[...x.fields,placement]:x.fields.filter(f=>f.key!==placement.key)})))}>{sections.filter(s=>s.status!=='archived').map((s,i)=><option key={s.id} value={s.id}>{s.title||`Section ${i+1}`}</option>)}</select></label></>}<label className="flex items-center gap-2"><input type="checkbox" checked={placement.visible||required} disabled={!manage||required} onChange={e=>editLayout(s=>s.map(x=>({...x,fields:x.fields.map(f=>f.key===placement.key?{...f,visible:e.target.checked}:f)})))}/>Visible{required?' (required)':''}</label></div></div>;})}
   </section>)}
   {manage&&<div className="record-actions"><button className="quiet-button" disabled={sections.length>=20} onClick={()=>editLayout(s=>[...s,{id:crypto.randomUUID(),title:'New section',fields:[]}])}>Add section</button><button className="action-link" disabled={saveLayout.isPending} onClick={()=>saveLayout.mutate(false)}>Save layout</button><button className="quiet-button" disabled={saveLayout.isPending} onClick={()=>{if(window.confirm('Reset to the default layout? Field definitions and values are preserved.'))saveLayout.mutate(true);}}>Reset default layout</button></div>}
  </>}
  <AdvancedModal isOpen={Boolean(editing)} onClose={()=>setEditing(null)} title={editing?.id?'Edit field':'Add field'}>{editing&&<form className="page-stack" onSubmit={e=>{e.preventDefault();if(manage)save.mutate();}}><Input label="Field key" required maxLength={64} disabled={Boolean(editing.id)} value={editing.key} onChange={e=>setEditing({...editing,key:e.target.value})}/><Input label="Field label" required maxLength={100} value={editing.label} onChange={e=>setEditing({...editing,label:e.target.value})}/><label className="field">Field type<select disabled={Boolean(editing.id)} value={editing.field_type} onChange={e=>setEditing({...editing,field_type:e.target.value as Definition['field_type'],options:[],default_value:null,searchable:false,filterable:false})}>{types.map(t=><option key={t}>{t}</option>)}</select></label><Input label="Help text" maxLength={500} value={editing.help} onChange={e=>setEditing({...editing,help:e.target.value})}/><label className="field">Field status<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as Definition['status']})}><option value="active">Active</option><option value="archived">Archived (history retained)</option></select></label>{(['required','searchable','filterable','reportable'] as const).map(flag=><label key={flag} className="flex items-center gap-2"><input type="checkbox" disabled={(flag==='searchable'&&!['text','textarea','email','phone'].includes(editing.field_type))||(flag==='filterable'&&editing.field_type==='multiselect')} checked={editing[flag]} onChange={e=>setEditing({...editing,[flag]:e.target.checked})}/>{flag}</label>)}
   {['select','radio','multiselect'].includes(editing.field_type)&&<fieldset className="page-stack"><legend>Stable options</legend>{editing.options.map((o,i)=><div className="panel page-stack" key={o.id||i}><Input label={`Option ${i+1} key`} required disabled={Boolean(o.id)} maxLength={64} value={o.key} onChange={e=>setEditing({...editing,options:editing.options.map((x,n)=>n===i?{...x,key:e.target.value}:x)})}/><Input label={`Option ${i+1} label`} required maxLength={100} value={o.label} onChange={e=>setEditing({...editing,options:editing.options.map((x,n)=>n===i?{...x,label:e.target.value}:x)})}/><label><input type="checkbox" checked={o.status==='active'} onChange={e=>setEditing({...editing,options:editing.options.map((x,n)=>n===i?{...x,status:e.target.checked?'active':'archived'}:x)})}/>Active option</label><div className="record-actions"><button type="button" className="quiet-button" disabled={!i} onClick={()=>setEditing({...editing,options:move(editing.options,i,-1)})}>Move option {i+1} up</button><button type="button" className="quiet-button" disabled={i===editing.options.length-1} onClick={()=>setEditing({...editing,options:move(editing.options,i,1)})}>Move option {i+1} down</button></div></div>)}<button type="button" className="quiet-button" disabled={editing.options.length>=100} onClick={()=>setEditing({...editing,options:[...editing.options,{id:'',key:'',label:'',status:'active'}]})}>Add option</button></fieldset>}
   {editing.id&&['select','radio','multiselect'].includes(editing.field_type)&&<DynamicForm schema={{entity,version:0,sections:[],builtins:[],definitions:[{...editing,status:'active',label:'Default choice (new records only)',help:'',required:false}]}} values={{[editing.key]:editing.default_value}} onChange={(_key,value)=>setEditing({...editing,default_value:value})}/>} {!['select','radio','multiselect','checkbox'].includes(editing.field_type)&&<Input label="Default value (new records only)" value={typeof editing.default_value==='string'?editing.default_value:''} maxLength={editing.field_type==='textarea'?10000:1000} onChange={e=>setEditing({...editing,default_value:e.target.value||null})}/>}{editing.field_type==='checkbox'&&<label>Default checkbox<select value={editing.default_value===null?'none':String(editing.default_value)} onChange={e=>setEditing({...editing,default_value:e.target.value==='none'?null:e.target.value==='true'})}><option value="none">No default</option><option value="true">Yes</option><option value="false">No</option></select></label>}
   {save.isError&&<p role="alert">{getErrorMessage(save.error,'Field could not be saved.')}</p>}<button className="action-link" disabled={!manage||save.isPending} type="submit">Save field</button></form>}</AdvancedModal>
  <AdvancedModal isOpen={Boolean(preview)} onClose={()=>setPreview(null)} title={`${preview==='mobile'?'Mobile':'Desktop'} form preview`}>{schema&&<div className="mx-auto max-w-full" style={{width:preview==='mobile'?390:undefined}}><p className="muted">Preview only; nothing is saved.</p><DynamicForm schema={{...schema,sections}} values={form.values} onChange={form.change} builtins={Object.fromEntries(schema.builtins.map(b=>[b.key,<Input key={b.key} label={b.label} required={b.required} disabled placeholder="Built-in field"/>]))}/></div>}</AdvancedModal>
 </div>;
}
