import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import { useOrganizationData } from '../../hooks/useOrganizationData';
import { client } from '../../api/client';
import { getErrorMessage } from '../../api/errors';
import { useAppStore } from '../../store/useAppStore';
import { Input } from '../../components/ui/Input';
import { AdvancedModal } from '../../components/ui/AdvancedModal';
interface Profile {name:string;type:string;business_category:string;description:string;contact_email:string;contact_phone:string;address:string;website:string;legal_name:string;active_staff:number;active_branches:number;custom_roles:number;pending_invitations:number}
export interface Branch {id:string;name:string;code:string;timezone:string;status:'active'|'inactive';version:number;updated_at:string}
export interface Role {id:string;name:string;description:string;status:'active'|'archived';version:number;permissions:string[]}
interface Catalogue {key:string;label:string;description:string;category:string}
export interface RoleData {catalogue:Catalogue[];system:{name:string;permissions:string[]}[];custom:Role[]}

export default function OrganizationPage({section='overview'}:{section?:'overview'|'branches'|'roles'|'audit'|'platform'}) {
  const {user,isPlatformOperator,entitlements}=useAppStore(); const grants=user?.permissions??[];
  const [search,setSearch]=useState(''); const [page,setPage]=useState(1); const [category,setCategory]=useState(''); const [action,setAction]=useState(''); const [actor,setActor]=useState(''); const [from,setFrom]=useState(''); const [to,setTo]=useState('');
  const profile=useOrganizationData<Profile>('/organization',section==='overview');
  const branches=useOrganizationData<Branch[]>(`/branches?search=${encodeURIComponent(search)}`,section==='branches');
  const roles=useOrganizationData<RoleData>('/roles',section==='roles');
  const actors=useOrganizationData<{id:string;name:string}[]>('/audit/actors',section==='audit');
  const params=new URLSearchParams({page:String(page),...(category?{category}:{}),...(action?{action}:{}),...(actor?{actor}:{}),...(from?{from:new Date(from).toISOString()}:{}),...(to?{to:new Date(to).toISOString()}:{} )});
  const events=useOrganizationData<{id:string;actor:string;action:string;occurred_at:string}[]>(`/audit?${params}`,section==='audit');
  const directory=useOrganizationData<{id:string;name:string;type:string;plan:string;subscription_status:string;modules:string[];current_period_ends_at:string|null;active_staff:number;active_branches:number}[]>(`/platform/organizations?search=${encodeURIComponent(search)}&page=${page}`,section==='platform'&&isPlatformOperator);
  const [branch,setBranch]=useState<Partial<Branch>|null>(null); const [role,setRole]=useState<Partial<Role>|null>(null); const [editing,setEditing]=useState<Profile|null>(null);
  const cache=useQueryClient();
  const save=useMutation({mutationFn:async()=>{
    if(branch) {const body={name:branch.name,code:branch.code,timezone:branch.timezone,status:branch.status,...(branch.id?{version:branch.version}:{})};return branch.id?client.patch('/branches/'+branch.id,body):client.post('/branches',body);}
    if(role) {const body={name:role.name,description:role.description,permissions:role.permissions,...(role.id?{version:role.version,status:role.status}:{})};return role.id?client.patch('/roles/'+role.id,body):client.post('/roles',body);}
    if(editing) return client.put('/organization',{name:editing.name,type:editing.type,businessCategory:editing.business_category??'',description:editing.description??'',contactEmail:editing.contact_email??'',contactPhone:editing.contact_phone??'',address:editing.address??'',website:editing.website??''});
  },onSuccess:()=>{setBranch(null);setRole(null);setEditing(null);void cache.invalidateQueries({queryKey:['organization-admin']});toast.success('Changes saved');}});
  const query=section==='overview'?profile:section==='branches'?branches:section==='roles'?roles:section==='audit'?events:directory;
  const title={overview:'Organization administration',branches:'Branches',roles:'Roles & permissions',audit:'Audit history',platform:'Platform Operations'}[section];
  return <div className="page-stack"><header className="page-heading"><div><h1>{title}</h1><p>{section==='platform'?'Operator-only oversight. No impersonation or credential access.':'Organization authority is separate from your personal identity and commercial subscription.'}</p></div>
    {section==='branches'&&grants.includes('branches.manage')&&<button className="action-link" onClick={()=>{save.reset();setBranch({name:'',code:'',timezone:'Asia/Kolkata',status:'active'});}}>Create branch</button>}
    {section==='roles'&&grants.includes('roles.manage')&&<button className="action-link" onClick={()=>{save.reset();setRole({name:'',description:'',permissions:[],status:'active'});}}>Create role</button>}</header>
    {section!=='platform'&&<nav className="settings-tabs" aria-label="Organization sections">{[['/admin','General','organization.read'],['/branches','Branches','branches.read'],['/staff','Staff','staff.read'],['/roles','Roles','roles.read'],['/billing','Billing','billing.read'],['/audit','Audit','audit.read']].filter(([, ,p])=>grants.includes(p!)).map(([path,label])=><Link className="quiet-button" key={path} to={path!}>{label}</Link>)}</nav>}
    {(section==='branches'||section==='platform')&&<Input label={section==='branches'?'Search branches':'Search organizations'} value={search} maxLength={200} onChange={e=>{setSearch(e.target.value);setPage(1);}}/>}
    {query.isPending&&<p role="status">Loading…</p>}{query.isError&&<section className="panel" role="alert">{getErrorMessage(query.error,'Could not load this section.')} <button className="quiet-button" onClick={()=>void query.refetch()}>Retry</button></section>}
    {section==='overview'&&profile.data&&<><div className="catalogue-grid">{[['Active staff',profile.data.active_staff],['Active branches',profile.data.active_branches],['Custom roles',profile.data.custom_roles],['Pending invitations',profile.data.pending_invitations]].map(([label,count])=><article className="panel record-card" key={label}><h2>{label}</h2><strong className="text-3xl">{count}</strong></article>)}</div>
      <section className="panel page-stack"><h2 className="font-semibold">Business profile</h2><h3>{profile.data.name}</h3><p>{profile.data.type} · {profile.data.business_category||'Category not supplied'}</p>{(['description','address','contact_email','contact_phone','website'] as const).map(key=><p key={key}>{profile.data![key]||`${key.replaceAll('_',' ')} not supplied`}</p>)}{profile.data.legal_name&&<p>Billing legal name: {profile.data.legal_name} (commercial agreement, read-only here)</p>}{grants.includes('organization.manage')&&<button className="quiet-button" onClick={()=>{save.reset();setEditing(profile.data!);}}>Edit business profile</button>}</section>
      <section className="panel page-stack"><h2 className="font-semibold">Modules & access</h2><p>Customers and Services are CORE. Permission does not purchase or activate a module.</p>{['queue','attendance','ledger','inventory'].map(module=><div key={module}><strong className="capitalize">{module==='ledger'?'Customer dues':module}</strong><p className="muted">Subscription: {entitlements?.modules.some(m=>m.key===module&&m.enabled)?'Enabled':'Not enabled'} · Role view: {grants.includes(module+'.read')?'Allowed':'Denied'} · Role manage: {grants.includes(module+'.manage')?'Allowed':'Denied'}</p></div>)}</section></>}
    {section==='branches'&&<div className="catalogue-grid">{branches.data?.length===0&&<p>No matching branches.</p>}{branches.data?.map(b=><article className="panel record-card" key={b.id}><h2>{b.name}</h2><p className="muted">{b.code} · {b.status}</p><p>{b.timezone??'Timezone requires review'}</p><p className="muted">Updated {new Date(b.updated_at).toLocaleString()}</p>{grants.includes('branches.manage')&&<button className="quiet-button" onClick={()=>{save.reset();setBranch(b);}}>Edit {b.name}</button>}</article>)}</div>}
    {section==='roles'&&<><section className="panel page-stack"><h2 className="font-semibold">System roles · read-only</h2>{roles.data?.system.map(r=><details key={r.name}><summary className="capitalize">{r.name}</summary><ul>{r.permissions.map(p=><li key={p}>{roles.data?.catalogue.find(c=>c.key===p)?.label??p}</li>)}</ul></details>)}</section><div className="catalogue-grid">{roles.data?.custom.length===0&&<p>No custom roles yet.</p>}{roles.data?.custom.map(r=><article className="panel record-card" key={r.id}><h2>{r.name}</h2><p>{r.description}</p><p className="muted">{r.status} · {r.permissions.length} permissions</p>{grants.includes('roles.manage')&&<button className="quiet-button" onClick={()=>{save.reset();setRole({...r});}}>Edit {r.name}</button>}</article>)}</div></>}
    {section==='audit'&&<><section className="panel catalogue-grid"><Input label="From" type="datetime-local" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}}/><Input label="To" type="datetime-local" value={to} onChange={e=>{setTo(e.target.value);setPage(1);}}/><Input label="Action" value={action} onChange={e=>{setAction(e.target.value);setPage(1);}}/><Input label="Category" value={category} onChange={e=>{setCategory(e.target.value);setPage(1);}}/>{actors.data&&<label>Actor<select className="w-full rounded-lg border p-3" value={actor} onChange={e=>{setActor(e.target.value);setPage(1);}}><option value="">All actors</option>{actors.data.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}</section><section className="panel page-stack">{events.data?.length===0&&<p>No matching audit events.</p>}{events.data?.map(e=><article key={e.id}><strong>{e.action.replaceAll('.',' · ')}</strong><p className="muted">{e.actor} · {new Date(e.occurred_at).toLocaleString()}</p></article>)}</section></>}
    {section==='platform'&&<><div className="record-actions"><Link className="quiet-button" to="/commercial/requests">Commercial Intake</Link><Link className="quiet-button" to="/commercial/renewals">Renewals</Link><Link className="quiet-button" to="/corporate">Corporate HQ</Link></div><div className="catalogue-grid">{directory.data?.length===0&&<p>No matching organizations.</p>}{directory.data?.map(o=><article className="panel record-card" key={o.id}><h2>{o.name}</h2><p>{o.type} · {o.plan??'No plan'}</p><p>{o.subscription_status??'No subscription'}</p><p>Enabled modules: {o.modules?.join(', ')||'None'}</p><p className="muted">Period ends: {o.current_period_ends_at?new Date(o.current_period_ends_at).toLocaleString():'Not specified'}</p><p className="muted">{o.active_staff} active members · {o.active_branches} active branches</p></article>)}</div></>}
    {(section==='audit'||section==='platform')&&<div className="record-actions"><button className="quiet-button" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page}</span><button className="quiet-button" disabled={(section==='audit'?events.data:directory.data)?.length!==50} onClick={()=>setPage(p=>p+1)}>Next</button></div>}
    <AdvancedModal isOpen={Boolean(branch||role||editing)} onClose={()=>{setBranch(null);setRole(null);setEditing(null);}} title={branch?'Branch details':role?'Role editor':'Business profile'} actions={<button className="action-link" disabled={save.isPending} onClick={()=>{if(role?.status==='archived'&&!window.confirm('Archive this role? Assigned roles must first be reassigned.'))return;if(branch?.status==='inactive'&&!window.confirm('Deactivate this branch? History remains available.'))return;save.mutate();}}>Save changes</button>}><div className="page-stack">
      {branch&&<><Input label="Branch name" value={branch.name??''} onChange={e=>setBranch({...branch,name:e.target.value})}/><Input label="Branch code" value={branch.code??''} onChange={e=>setBranch({...branch,code:e.target.value})}/><Input label="IANA timezone" value={branch.timezone??''} onChange={e=>setBranch({...branch,timezone:e.target.value})}/><label className="flex gap-2"><input type="checkbox" checked={branch.status==='active'} onChange={e=>setBranch({...branch,status:e.target.checked?'active':'inactive'})}/>Active branch</label></>}
      {role&&<><Input label="Role name" value={role.name??''} onChange={e=>setRole({...role,name:e.target.value})}/><Input label="Role description" value={role.description??''} onChange={e=>setRole({...role,description:e.target.value})}/>{role.id&&<label className="flex gap-2"><input type="checkbox" checked={role.status==='archived'} onChange={e=>setRole({...role,status:e.target.checked?'archived':'active'})}/>Archive role</label>}<p className="muted">Custom roles replace system permissions. Only authority you hold can be granted.</p>{Array.from(new Set(roles.data?.catalogue.map(c=>c.category))).map(category=><fieldset key={category} className="page-stack"><legend className="font-semibold">{category}</legend>{roles.data?.catalogue.filter(c=>c.category===category).map(c=><label key={c.key} className="flex items-start gap-2"><input type="checkbox" disabled={!grants.includes(c.key)} checked={role.permissions?.includes(c.key)??false} onChange={e=>setRole({...role,permissions:e.target.checked?[...(role.permissions??[]),c.key]:(role.permissions??[]).filter(p=>p!==c.key)})}/><span>{c.label}<small className="block muted">{c.description}</small></span></label>)}</fieldset>)}</>}
      {editing&&([['name','Organization name'],['type','Business type'],['business_category','Business category'],['description','Description'],['contact_email','Contact email'],['contact_phone','Contact phone'],['address','Business address'],['website','Website']] as const).map(([key,label])=><Input key={key} label={label} value={editing[key]??''} onChange={e=>setEditing({...editing,[key]:e.target.value})}/>)}
      {save.isError&&<p role="alert">{getErrorMessage(save.error,'Changes could not be saved.')}</p>}
    </div></AdvancedModal></div>;
}
