import {test,expect,type Page} from '@playwright/test';
import {randomUUID} from 'node:crypto';
const api='http://127.0.0.1:5011';
interface Fixture {phone:string;password:string;email:string;userId:string;organizationId:string;branchId:string}
let fixture:Fixture;let errors:string[];
test.beforeEach(async({page,request})=>{fixture=await(await request.post(api+'/__test/fixture')).json();errors=[];page.on('pageerror',e=>errors.push(e.name));page.on('dialog',dialog=>dialog.accept());});
test.afterEach(()=>expect(errors).toEqual([]));
async function login(page:Page,f=fixture){await page.goto('/login');await page.getByLabel('Phone or email').fill(f.phone);await page.getByLabel('Password',{exact:true}).fill(f.password);await page.getByRole('button',{name:'Sign In to Ekavio'}).click();await expect(page).toHaveURL(/dashboard/);}
async function createRole(page:Page,name='Customer reader'){await page.goto('/roles');await page.getByRole('button',{name:'Create role',exact:true}).click();await page.getByLabel('Role name').fill(name);await page.getByLabel('Role description').fill('Disposable least-privilege role');await page.getByRole('checkbox',{name:/View customers/}).check();await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();}
test('profile save persists and dashboard counts are factual',async({page})=>{await login(page);await page.goto('/admin');await expect(page.getByText('Active staff',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Edit business profile'}).click();await page.getByLabel('Organization name').fill('Disposable updated workspace');await page.getByLabel('Business category').fill('Retail');await page.getByLabel('Contact email').fill('QA@example.invalid');await page.getByLabel('Contact phone').fill('9876540001');await page.getByLabel('Business address').fill('Disposable fixture address');await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByRole('heading',{name:'Disposable updated workspace'})).toBeVisible();await page.reload();await expect(page.getByText('Disposable fixture address',{exact:true})).toBeVisible();await expect(page.getByText('qa@example.invalid',{exact:true})).toBeVisible();await expect(page.getByText('+919876540001',{exact:true})).toBeVisible();});
test('branch create search deactivate/reactivate preserves history',async({page})=>{await login(page);await page.goto('/branches');await page.getByRole('button',{name:'Create branch'}).click();await page.getByLabel('Branch name').fill('QA second');await page.getByLabel('Branch code').fill('qa-second');await page.getByLabel('IANA timezone').fill('Asia/Kolkata');await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByRole('heading',{name:'QA second',exact:true})).toBeVisible();await page.getByLabel('Search branches').fill('QA second');await page.getByRole('button',{name:'Edit QA second'}).click();await page.getByRole('checkbox',{name:'Active branch'}).uncheck();await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByText('qa-second · inactive',{exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'Edit QA second'}).click();await page.getByRole('checkbox',{name:'Active branch'}).check();await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByText('qa-second · active',{exact:true})).toBeVisible();});
test('last active branch deactivation rejects visibly',async({page})=>{await login(page);await page.goto('/branches');await page.getByRole('button',{name:'Edit Main'}).click();await page.getByRole('checkbox',{name:'Active branch'}).uncheck();await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByRole('alert')).toContainText('last active branch');});
test('custom role catalogue editor and archive retain history',async({page})=>{await login(page);await createRole(page);await page.getByRole('button',{name:'Edit Customer reader'}).click();await page.getByRole('checkbox',{name:/View services/}).check();await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByText('active · 2 permissions')).toBeVisible();await page.getByRole('button',{name:'Edit Customer reader'}).click();await page.getByRole('checkbox',{name:'Archive role'}).check();await page.getByRole('button',{name:'Save changes'}).click();await expect(page.getByText('archived · 2 permissions')).toBeVisible();});
test('existing account explicitly joins with custom role; suspend/reactivate/revoke preserve other org',async({page,browser,request})=>{
  const target:Fixture=await(await request.post(api+'/__test/fixture')).json();await login(page);await createRole(page);await page.goto('/staff');await page.getByRole('button',{name:'Invite staff',exact:true}).click();await page.getByLabel('Full name').fill('Existing disposable member');await page.getByLabel('Phone number',{exact:true}).fill(target.phone);await page.getByLabel('Custom role').selectOption({label:'Customer reader'});await page.getByRole('button',{name:'Send invitation'}).click();const input=page.getByLabel('One-time handoff link');await expect(input).toBeVisible();const link=await input.inputValue();await page.getByRole('button',{name:'I have handed off the link'}).click();
  const context=await browser.newContext();const recipient=await context.newPage();recipient.on('pageerror',e=>errors.push(e.name));await login(recipient,target);await recipient.goto(link);await expect(recipient.getByLabel('New password',{exact:true})).toHaveCount(0);await recipient.getByRole('button',{name:'Accept invitation'}).click();await expect(recipient.getByRole('status')).toContainText('Organization joined');await page.reload();
  for(const status of ['inactive','active','revoked']){await page.getByRole('button',{name:'Edit QA owner',exact:true}).click();await page.getByLabel('Membership status').selectOption(status);await page.getByRole('button',{name:'Save staff access'}).click();await expect(page.getByText('Customer reader · '+status,{exact:true})).toBeVisible();}
  await recipient.goto('/settings');await expect(recipient.getByRole('heading',{name:'Settings',exact:true})).toBeVisible();await recipient.goto(link);await expect(recipient.getByRole('alert')).toContainText('already used');await context.close();
});
test('audit has human actor and category filtering',async({page})=>{await login(page);await createRole(page);await page.goto('/audit');await expect(page.getByText('role · created',{exact:true})).toBeVisible();await expect(page.getByText(/QA owner ·/)).toBeVisible();await page.getByLabel('Category').fill('branch');await expect(page.getByText('No matching audit events.')).toBeVisible();});
test('Customers/Services CORE without Queue entitlement; Queue still denied',async({page})=>{await login(page);await page.goto('/customers');await expect(page.getByRole('button',{name:'Create customer',exact:true})).toBeVisible();await page.goto('/services');await expect(page.getByRole('button',{name:'Create service',exact:true})).toBeVisible();await page.goto('/queue');await expect(page.getByRole('heading',{name:'Upgrade Required'})).toBeVisible();});
test('limited custom member direct admin routes denied and role cannot enable Queue',async({page,request})=>{const restricted=await(await request.post(api+'/__test/fixture',{data:{permissions:['customers.read','services.read','queue.read','queue.manage']}})).json();await login(page,restricted);await page.goto('/customers');await expect(page.getByRole('heading',{name:'Customers',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Create customer',exact:true})).toHaveCount(0);for(const route of ['/admin','/roles','/audit','/platform']){await page.goto(route);await expect(page).toHaveURL(/dashboard/);}await page.goto('/queue');await expect(page.getByRole('heading',{name:'Upgrade Required'})).toBeVisible();});
test('operator directory remains separate from ordinary admin',async({page,request})=>{await login(page);await page.goto('/platform');await expect(page).toHaveURL(/dashboard/);await page.getByRole('button',{name:'Sign out',exact:true}).click();const operator=await(await request.post(api+'/__test/fixture',{data:{operator:true}})).json();await login(page,operator);await page.goto('/platform');await expect(page.getByRole('heading',{name:'Platform Operations',exact:true})).toBeVisible();await page.getByLabel('Search organizations').fill(randomUUID());await expect(page.getByText('No matching organizations.')).toBeVisible();});
for(const width of [390,768,1440])for(const theme of ['light','dark','system'])test(`admin fits ${width}px in ${theme}`,async({page})=>{await page.setViewportSize({width,height:900});await login(page);await page.goto('/settings?section=appearance');await page.getByRole('radio',{name:new RegExp(theme,'i')}).click();for(const route of ['/admin','/branches','/roles','/staff','/audit']){await page.goto(route);await expect(page.getByRole('heading',{level:1}).last()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();}if(width===1440&&theme==='light'){await page.goto('/admin');await expect(page.getByRole('heading',{name:'Business profile'})).toBeVisible();await page.screenshot({path:'test-results/organization-admin/safe-admin-overview.png'});}});
