import { it,expect,vi } from 'vitest';
import { render,screen,fireEvent } from '@testing-library/react';
import { DynamicForm } from '../components/forms/DynamicForm';
import { types,formSections,fieldError,type Definition,type FormSchema } from '../components/forms/formSchema';
const field=(type:Definition['field_type']):Definition=>({id:'fixture',key:'fixture',label:'Fixture field',help:'Plain helpful text',field_type:type,status:'active',required:true,searchable:false,filterable:false,reportable:false,default_value:null,version:1,options:[{id:'one',key:'stable',label:'Option one',status:'active'},{id:'old',key:'old',label:'Historical option',status:'archived'}]});
const schema=(f:Definition):FormSchema=>({entity:'customer',version:0,builtins:[],definitions:[f],sections:[]});
for(const type of types) it(`renders accessible ${type} with typed change`,()=>{
 const change=vi.fn(),f=field(type);render(<DynamicForm schema={schema(f)} values={{}} onChange={change}/>);expect(screen.getByText('Plain helpful text')).toBeTruthy();
 if(type==='phone'){fireEvent.change(screen.getByLabelText('Fixture field'),{target:{value:'9876543210'}});expect(change).toHaveBeenCalled();}
 else if(type==='multiselect'||type==='radio'){fireEvent.click(screen.getByLabelText('Option one'));expect(change).toHaveBeenCalledWith('fixture',type==='radio'?'one':['one']);}
 else if(type==='checkbox'){fireEvent.click(screen.getByRole('checkbox'));expect(change).toHaveBeenCalledWith('fixture',true);}
 else {const input=screen.getByLabelText(/Fixture field/);expect(input.getAttribute('required')).not.toBeNull();}
});
it('archived options retain labels in detail, never become selectable new options',()=>{const f=field('select');const {rerender}=render(<DynamicForm schema={schema(f)} values={{fixture:'old'}} readOnly/>);expect(screen.getByText('Historical option')).toBeTruthy();rerender(<DynamicForm schema={schema(f)} values={{}}/>);expect(screen.queryByText('Historical option')).toBeNull();});
it('native datetime minute precision becomes explicit UTC seconds',()=>{const change=vi.fn();render(<DynamicForm schema={schema(field('datetime'))} values={{}} onChange={change}/>);fireEvent.change(screen.getByLabelText(/Fixture field/),{target:{value:'2028-01-01T10:30'}});expect(change).toHaveBeenCalledWith('fixture','2028-01-01T10:30:00Z');});
it('archive removes fields from new forms and preserves historical display',()=>{const f={...field('text'),status:'archived' as const};const {rerender}=render(<DynamicForm schema={schema(f)} values={{fixture:'Historical value'}}/>);expect(screen.queryByText('Fixture field *')).toBeNull();rerender(<DynamicForm schema={schema(f)} values={{fixture:'Historical value'}} readOnly/>);expect(screen.getByText('Historical value')).toBeTruthy();});
it('layout order and missing required fallback keep builtins canonical',()=>{const f=field('text'),s={...schema(f),builtins:[{key:'name',label:'Name',required:true}],sections:[{id:'main',title:'Details',fields:[{key:f.key,visible:true}]}]};const sections=formSections(s);expect(sections[1].fields[0].key).toBe('name');render(<DynamicForm schema={s} values={{}} builtins={{name:<input aria-label="Canonical name" required/>}}/>);expect(screen.getByLabelText('Canonical name')).toBeTruthy();});
it('boolean false and exact numbers display without number coercion',()=>{render(<DynamicForm schema={{...schema(field('checkbox')),definitions:[field('checkbox'),{...field('number'),key:'decimal',id:'decimal',label:'Exact number'}]}} values={{fixture:false,decimal:'123456789012345678.123456'}} readOnly/>);expect(screen.getByText('No')).toBeTruthy();expect(screen.getByText('123456789012345678.123456')).toBeTruthy();});
it('required and invalid values are inline and associated with the control',()=>{render(<DynamicForm schema={schema(field('number'))} values={{fixture:'1e6'}}/>);const input=screen.getByLabelText(/Fixture field/);expect(input.getAttribute('aria-invalid')).toBe('true');expect(input.getAttribute('aria-describedby')).toContain('error');expect(screen.getByRole('alert').textContent).toContain('decimal');expect(fieldError(field('checkbox'),false)).toBeUndefined();expect(fieldError(field('date'),'2026-02-30')).toBeTruthy();expect(fieldError(field('url'),'javascript:bad')).toBeTruthy();});
