import { describe,it,expect,vi,afterEach } from 'vitest';
import { render,screen,cleanup,fireEvent,waitFor } from '@testing-library/react';
import { QueryClient,QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter } from 'react-router-dom';
import PurchasingPage from '../pages/Purchasing/PurchasingPage';
import SuppliersPage,{SupplierEditor} from '../pages/Purchasing/SuppliersPage';
import { OrderEditor,ReceiveEditor } from '../pages/Purchasing/forms';
import { previewLine,validReceiptQuantity,type Order } from '../pages/Purchasing/contracts';
import { visibleDestinations } from '../components/layout/navigation';
import { useAppStore } from '../store/useAppStore';
import { client } from '../api/client';
vi.mock('../api/client',()=>({client:{get:vi.fn(),post:vi.fn(),patch:vi.fn()}}));
afterEach(()=>{cleanup();vi.clearAllMocks();});
const entitlements={modules:[{key:'purchasing',enabled:true},{key:'inventory',enabled:true}]} as never;
const empty={data:[],total:0,page:1,limit:20};
function setup(element:React.ReactNode,permissions=['purchasing.read','purchasing.manage','inventory.read','inventory.manage'],inventory=true){
 useAppStore.setState({user:{id:'qa',permissions} as never,activeTenantId:'org',activeBranchId:'branch',entitlements:inventory?entitlements:{modules:[{key:'purchasing',enabled:true}]} as never});
 vi.mocked(client.get).mockImplementation(async path=>({data:path==='/inventory'?empty:{data:path==='/purchasing/overview'?{open:'0',partial:'0',awaiting:'0',recent:'0'}:empty}}) as never);
 render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryRouter>{element}</MemoryRouter></QueryClientProvider>);
}
const order={id:'order',human_reference:'EV-PO-QA',version:2,lines:[{id:'line',inventory_item_id:'item',item_name_snapshot:'QA flour',unit_code_snapshot:'kg',ordered_quantity:'10.000',received_quantity:'4.000',remaining_quantity:'6.000',unit_price_minor:'125',line_amount_minor:'1250'}]} as Order;
describe('Purchasing presentation and exact commands',()=>{
 it('navigation independently checks purchasing permission and commercial access',()=>{expect(visibleDestinations(['purchasing.read'],null,false).some(d=>d.path==='/suppliers')).toBe(false);expect(visibleDestinations([],entitlements,false).some(d=>d.path==='/purchasing')).toBe(false);expect(visibleDestinations(['purchasing.read'],entitlements,false).filter(d=>['/suppliers','/purchasing'].includes(d.path))).toHaveLength(2);});
 it.each([['0.500','0.01',1n],['1.250','10.01',1251n],['0.001','5.00',1n],['10','1.25',1250n]])('exact line %s × %s', (q,p,n)=>expect(previewLine(q,p)).toBe(n));
 it('invalid precision and overflow never become floating-point previews',()=>{for(const [q,p] of [['0','1'],['1.0001','1'],['1','0.001'],['1e3','1'],['999999999999999','99999999999999999']])expect(previewLine(q,p)).toBeNull();});
 it('receiving requires positive bounded milli quantities',()=>{expect(validReceiptQuantity('6','6.000')).toBe(true);for(const q of ['0','6.001','1.0001','-1','1e2'])expect(validReceiptQuantity(q,'6.000')).toBe(false);});
 it('supplier-only access explains Inventory dependency without querying orders',async()=>{setup(<PurchasingPage/>,['purchasing.read','purchasing.manage'],false);await screen.findByRole('heading',{name:'Inventory access required for Purchase Orders'});expect(screen.queryByRole('button',{name:'Create Purchase Order'})).toBeNull();expect(vi.mocked(client.get).mock.calls.some(([path])=>path==='/purchasing/orders')).toBe(false);});
 it('read-only role has no mutation controls',async()=>{setup(<PurchasingPage/>,['purchasing.read','inventory.read']);await screen.findByRole('heading',{name:'No Purchase Orders yet'});expect(screen.queryByRole('button',{name:'Create Purchase Order'})).toBeNull();});
 it('supplier search is bounded and server-paginated',async()=>{setup(<SuppliersPage/>);await screen.findByRole('heading',{name:'No suppliers yet'});const search=screen.getByRole('searchbox',{name:'Search suppliers'});expect(search.getAttribute('maxlength')).toBe('200');fireEvent.change(search,{target:{value:'QA'}});await waitFor(()=>expect(client.get).toHaveBeenCalledWith('/suppliers',expect.objectContaining({params:expect.objectContaining({search:'QA',limit:20,page:1})})));});
 it('name-only supplier creation remains valid and contacts are optional',async()=>{vi.mocked(client.post).mockResolvedValue({data:{data:{id:'supplier'}}});setup(<SupplierEditor supplier={null} done={async()=>{}} close={()=>{}}/>);fireEvent.change(screen.getByLabelText('Supplier name'),{target:{value:'Local Supplier'}});fireEvent.click(screen.getByRole('button',{name:'Review'}));fireEvent.click(screen.getByRole('button',{name:'Save Supplier'}));await waitFor(()=>expect(client.post).toHaveBeenCalledWith('/suppliers',expect.objectContaining({name:'Local Supplier',phone:null,email:null,gstin:null})));});
 it('supplier validation rejects malformed optional email in the native form',()=>{setup(<SupplierEditor supplier={null} done={async()=>{}} close={()=>{}}/>);const email=screen.getByLabelText('Email (optional)') as HTMLInputElement;fireEvent.change(email,{target:{value:'not-an-email'}});expect(email.checkValidity()).toBe(false);expect(screen.getByLabelText('GSTIN (optional)').getAttribute('maxlength')).toBe('15');});
 it('PO draft editor preserves exact snapshots and invalid amounts disable saving',async()=>{setup(<OrderEditor order={{...order,supplier_id:'supplier',supplier_name:'QA Supplier',order_date:'2026-10-08',expected_delivery_date:null,notes:null,lines:order.lines?.map(l=>({...l,sku_snapshot:'FLOUR'}))}} done={async()=>{}} close={()=>{}}/>);await screen.findByText('SKU: FLOUR',{exact:true});expect(screen.getByText('Ordered purchase value: ₹12.50',{exact:true})).toBeTruthy();fireEvent.change(screen.getByLabelText('Ordered quantity — QA flour'),{target:{value:'1.0001'}});expect((screen.getByRole('button',{name:'Review'}) as HTMLButtonElement).disabled).toBe(true);expect(screen.getByText('Ordered purchase value: Check line amounts',{exact:true})).toBeTruthy();});
 it('blank receiving quantities require review; altered retries keep the original command',async()=>{vi.mocked(client.post).mockRejectedValue(new Error('Temporary failure'));setup(<ReceiveEditor order={order} done={async()=>{}} close={()=>{}}/>);const q=screen.getByLabelText('Quantity actually received — QA flour');expect((q as HTMLInputElement).value).toBe('');expect((screen.getByRole('button',{name:'Review receipt'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.change(q,{target:{value:'2.000'}});fireEvent.click(screen.getByRole('button',{name:'Review receipt'}));expect(client.post).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirm Receive Goods'}));await screen.findByRole('button',{name:'Retry identical receipt'});const first=vi.mocked(client.post).mock.calls[0];fireEvent.click(screen.getByRole('button',{name:'Retry identical receipt'}));await waitFor(()=>expect(client.post).toHaveBeenCalledTimes(2));expect(vi.mocked(client.post).mock.calls[1]).toEqual(first);expect(first[1]).toEqual(expect.objectContaining({expectedVersion:2,lines:[{orderLineId:'line',quantity:'2.000'}]}));expect(screen.queryByRole('button',{name:'Change quantities'})).toBeNull();});
});
