import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import { client } from '../../api/client';
import { getErrorMessage } from '../../api/errors';
import { useAppStore } from '../../store/useAppStore';
import { useOperationalContext, useOperationalScope } from '../../hooks/useOperationalContext';
import { exactRupees } from '../../components/analytics/contracts';
import { branchTime, decimalUnits } from '../../utils/operations';
import { exportToCSV } from '../../utils/exportUtils';
import { AdvancedTable, type Column } from '../../components/ui/AdvancedTable';
import { AdvancedModal } from '../../components/ui/AdvancedModal';
import { OperationForm } from '../../components/ui/OperationForm';
import { Input } from '../../components/ui/Input';
import { EmptyState } from '../../components/ui/EmptyState';
import { AppPage, PageHeader, SearchField, StatusBadge, DetailSection, ErrorState, FilterPanel, FilterChip } from '../../components/ui/WorkspacePrimitives';
type Type = 'charge' | 'payment' | 'adjustment_increase' | 'adjustment_decrease' | 'reversal';
type CreateType = Exclude<Type, 'reversal'>;
interface Entry { id: string; customerId: string; customerName: string; entryType: Type; amountMinor: string; signedEffectMinor: string; currency: 'INR'; dueDate: string | null; description: string | null; reversesEntryId: string | null; reversedByEntryId: string | null; occurredAt: string }
interface Paginated<T> { data: T[]; page: number; limit: number; total: number; totalPages: number }
interface Balance { organizationBalanceMinor: string; branchBalanceMinor: string }
const labels: Record<Type, string> = { charge: 'Charge', payment: 'Payment', adjustment_increase: 'Increase adjustment', adjustment_decrease: 'Decrease adjustment', reversal: 'Reversal' };
const effect = (type: CreateType) => ['charge', 'adjustment_increase'].includes(type) ? 'Increases the amount owed' : 'Reduces the amount owed';
export function LedgerPage() {
  const permissions = useAppStore(s => s.user?.permissions ?? []), manage = permissions.includes('ledger.manage'), scope = useOperationalScope(), context = useOperationalContext(), cache = useQueryClient();
  const [search, setSearch] = useState(''), [customerId, setCustomer] = useState(''), [page, setPage] = useState(1), [type, setType] = useState(''), [from, setFrom] = useState(''), [to, setTo] = useState(''), [filtersOpen, setFiltersOpen] = useState(false);
  const [createType, setCreateType] = useState<CreateType>('charge'), [creating, setCreating] = useState(false), [amount, setAmount] = useState(''), [description, setDescription] = useState(''), [dueDate, setDueDate] = useState(''), [key, setKey] = useState(() => crypto.randomUUID());
  const [reversal, setReversal] = useState<Entry | null>(null), [reversalReason, setReason] = useState(''), [reverseKey, setReverseKey] = useState(() => crypto.randomUUID()), [detail, setDetail] = useState<Entry | null>(null);
  const customers = useQuery({ queryKey: ['customer-dues-customers', ...scope, search], queryFn: async ({ signal }) => (await client.get<Paginated<{ id: string; name: string; status: string }>>('/customer-dues/customers', { signal, params: { search: search || undefined, page: 1, limit: 50 } })).data });
  const entries = useQuery({ queryKey: ['customer-dues-entries', ...scope, page, customerId, type, from, to], queryFn: async ({ signal }) => (await client.get<Paginated<Entry>>('/customer-dues/entries', { signal, params: { page, limit: 20, customerId: customerId || undefined, entryType: type || undefined, dateFrom: from || undefined, dateTo: to || undefined } })).data });
  const balance = useQuery({ queryKey: ['customer-dues-balance', ...scope, customerId], enabled: Boolean(customerId), queryFn: async ({ signal }) => (await client.get<{ data: Balance }>(`/customer-dues/customers/${customerId}/balance`, { signal })).data.data });
  const selected = customers.data?.data.find(c => c.id === customerId), amountMinor = decimalUnits(amount, 2);
  const paymentTooLarge = createType === 'payment' && amountMinor !== null && balance.data && amountMinor > BigInt(balance.data.organizationBalanceMinor);
  const valid = manage && Boolean(selected && amountMinor !== null && amountMinor > 0n) && (!createType.startsWith('adjustment_') || description.trim().length >= 3) && !paymentTooLarge && (createType !== 'payment' || Boolean(balance.data && !balance.isError && !balance.isFetching));
  const refresh = () => Promise.all(['customer-dues-entries', 'customer-dues-balance', 'dashboardStats'].map(key => cache.invalidateQueries({ queryKey: [key] })));
  const create = useMutation({ mutationFn: () => client.post('/customer-dues/entries', { customerId, entryType: createType, amount: amount.trim(), currency: 'INR', dueDate: createType === 'charge' ? dueDate || null : null, description: description.trim() || null, idempotencyKey: key }), onSuccess: async () => { setCreating(false); toast.success(`${labels[createType]} recorded`); await refresh(); } });
  const reverse = useMutation({ mutationFn: () => client.post(`/customer-dues/entries/${reversal!.id}/reversal`, { description: reversalReason.trim(), idempotencyKey: reverseKey }), onSuccess: async () => { setReversal(null); toast.success('Reversal recorded; original retained'); await refresh(); } });
  const begin = (type: CreateType) => { create.reset(); setCreateType(type); setAmount(''); setDescription(''); setDueDate(''); setKey(crypto.randomUUID()); setCreating(true); };
  const beginReverse = (entry: Entry) => { setDetail(null); reverse.reset(); setReason(''); setReverseKey(crypto.randomUUID()); setReversal(entry); };
  const badge = (e: Entry) => <StatusBadge tone={BigInt(e.signedEffectMinor) > 0n ? 'warning' : 'success'}>{labels[e.entryType]}{e.reversedByEntryId ? ' · Reversed' : ''}</StatusBadge>;
  const actions = (entry: Entry) => <div className="record-actions"><button className="quiet-button" onClick={() => setDetail(entry)}>Details</button>{manage && entry.entryType !== 'reversal' && !entry.reversedByEntryId && <button className="quiet-button" onClick={() => beginReverse(entry)}>Reverse</button>}</div>;
  const columns: Column<Entry>[] = [{ header: 'Customer', accessor: 'customerName' }, { header: 'Type', accessor: 'entryType', cell: ({ row }) => badge(row) }, { header: 'Amount (INR)', accessor: 'amountMinor', cell: ({ row }) => exactRupees(row.amountMinor) }, { header: 'Balance effect', accessor: 'signedEffectMinor', cell: ({ row }) => exactRupees(row.signedEffectMinor) }, { header: 'Recorded', accessor: 'occurredAt', cell: ({ row }) => branchTime(row.occurredAt, context.timezone, true) }, { header: 'Actions', accessor: 'actions', cell: ({ row }) => actions(row) }];
  const selection = <div className="operations-toolbar"><SearchField label="Search dues customers" maxLength={200} placeholder="Find an organization customer" value={search} onChange={e => { setSearch(e.target.value); setCustomer(''); setPage(1); }} /><label className="field">Customer<select aria-label="Customer" value={customerId} onChange={e => { setCustomer(e.target.value); setPage(1); }}><option value="">{creating ? 'Select customer' : 'All customers'}</option>{customers.data?.data.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><p className="muted">Up to 50 server matches; refine search for more.</p></div>;
  const filtered = Boolean(customerId || type || from || to), clear = () => { setCustomer(''); setType(''); setFrom(''); setTo(''); setPage(1); };
  return <AppPage className="operations-workspace"><PageHeader title="Customer Dues" eyebrow="Daily operations · Customer balances" description={`${context.branchName} · INR transactions, not sales revenue or full accounting`} actions={<><button className="quiet-button" disabled={!entries.data?.data.length} onClick={() => exportToCSV((entries.data?.data ?? []).map(e => ({ customer: e.customerName, type: labels[e.entryType], amount: exactRupees(e.amountMinor), balanceEffect: exactRupees(e.signedEffectMinor), recordedAt: e.occurredAt, dueDate: e.dueDate ?? '', description: e.description ?? '', reversalState: e.reversedByEntryId ? 'Reversed' : e.reversesEntryId ? 'Reversal' : '' })), 'customer-dues-current-page')}>Export current page</button>{manage && <><button className="action-link" onClick={() => begin('charge')}>Record Charge</button><button className="quiet-button" onClick={() => begin('payment')}>Record Payment</button><button className="quiet-button" onClick={() => begin('adjustment_increase')}>Record Adjustment</button></>}</>} />
    {context.isError && <ErrorState title="Branch time unavailable" message="Timestamps wait for the authorized branch timezone; no device-time fallback is used." retry={() => void context.refetch()} />}
    {!manage && <p className="muted">Read-only transactions; recording and reversals require Customer Dues manage permission.</p>}
    {!creating && <section className="panel">{selection}</section>}{customers.isError && <ErrorState title="Customer choices unavailable" message={getErrorMessage(customers.error, 'Retry customer search')} retry={() => void customers.refetch()} />}{customers.data?.data.length === 0 && permissions.includes('customers.manage') && <Link className="quiet-button" to="/customers">Create customer</Link>}
    {customerId && <>{balance.isError ? <ErrorState title="Balances unavailable" message="No page-local or zero balance is substituted." retry={() => void balance.refetch()} /> : <div className="operations-summary"><section className="panel"><h2>Organization-wide customer balance</h2><p className="stat-value">{balance.data ? exactRupees(balance.data.organizationBalanceMinor) : '—'}</p><p className="muted">Across all branches · {selected?.name ?? 'Selected customer'}</p></section><section className="panel"><h2>Selected branch balance</h2><p className="stat-value">{balance.data ? exactRupees(balance.data.branchBalanceMinor) : '—'}</p><p className="muted">{context.branchName} only</p></section></div>}</>}
    <FilterPanel label="Transaction filters" open={filtersOpen} onToggle={() => setFiltersOpen(v => !v)} count={[type, from, to].filter(Boolean).length}><label className="field">Transaction type<select aria-label="Transaction type" value={type} onChange={e => { setType(e.target.value); setPage(1); }}><option value="">All types</option>{Object.entries(labels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><Input label="From date" type="date" value={from} onChange={e => { setFrom(e.target.value); setPage(1); }} /><Input label="To date" type="date" value={to} onChange={e => { setTo(e.target.value); setPage(1); }} /></FilterPanel>{filtered && <FilterChip label="Transaction filters" onRemove={clear} />}
    <AdvancedTable mode="server" title="Transaction history" description="Append-only selected-branch journal · Server date/type/customer filters · No current-page running balance" columns={columns} rowKey={e => e.id} data={entries.data?.data ?? []} loading={entries.isPending} error={entries.isError ? getErrorMessage(entries.error, 'Transactions unavailable') : null} onRetry={() => void entries.refetch()} server={{ search: '', page, pageSize: 20, total: entries.data?.total ?? 0, totalPages: entries.data?.totalPages ?? 1, onPage: setPage }} emptyState={<EmptyState title={filtered ? 'No matching transactions' : 'No transactions yet'} description={filtered ? 'Change the customer/type/date filters.' : 'Record a charge or payment for a canonical customer.'} action={filtered ? 'Reset filters' : undefined} onAction={clear} />} mobileCard={e => <article className="panel mobile-record-card"><div className="operations-record-heading"><h2>{e.customerName}</h2>{badge(e)}</div><p className="stat-value">{exactRupees(e.amountMinor)}</p><p>Balance effect {exactRupees(e.signedEffectMinor)}</p><p className="muted">{branchTime(e.occurredAt, context.timezone, true)}</p>{e.description && <p>{e.description}</p>}{actions(e)}</article>} />
    <OperationForm open={creating} title={`Record ${labels[createType]}`} valid={Boolean(valid)} busy={create.isPending} dirty={Boolean(amount || description || dueDate)} error={create.error} confirmLabel={`Record ${labels[createType]}`} onClose={() => setCreating(false)} onConfirm={() => { if (valid && !create.isPending) create.mutate(); }} review={<DetailSection title={selected?.name ?? 'Customer'}><p>{labels[createType]} · {amountMinor !== null ? exactRupees(amountMinor.toString()) : '—'} · {context.branchName}</p><p>{effect(createType)}. {createType === 'payment' ? 'Cannot exceed the current organization-wide balance; revalidated transactionally.' : 'Permanent journal entry.'}</p><p>{dueDate && createType === 'charge' ? `Due ${dueDate}` : 'No due date'} · {description || 'No description'}</p></DetailSection>}>
      {selection}<label className="field">Entry type<select aria-label="Entry type" value={createType} onChange={e => setCreateType(e.target.value as CreateType)}>{Object.entries(labels).filter(([key]) => key !== 'reversal').map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><p>{effect(createType)}. Money is entered as exact INR decimal text, not a floating-point amount.</p><Input label="Amount (INR decimal)" required inputMode="decimal" maxLength={32} placeholder="1500.50" value={amount} error={amount && (amountMinor === null || amountMinor <= 0n) ? 'Enter a positive amount with at most two decimal places.' : paymentTooLarge ? 'Payment exceeds the organization-wide balance.' : undefined} onChange={e => setAmount(e.target.value)} />{createType === 'charge' && <Input label="Due date (optional)" type="date" value={dueDate} onChange={e => setDueDate(e.target.value)} />}<Input label={createType.startsWith('adjustment_') ? 'Adjustment reason' : 'Description (optional)'} required={createType.startsWith('adjustment_')} maxLength={1000} value={description} onChange={e => setDescription(e.target.value)} />{createType === 'payment' && <p>Organization-wide balance: {balance.data && !balance.isError ? exactRupees(balance.data.organizationBalanceMinor) : 'Unavailable'}</p>}
    </OperationForm>
    <AdvancedModal isOpen={Boolean(detail)} title="Transaction details" presentation="drawer" onClose={() => setDetail(null)} actions={detail && manage && detail.entryType !== 'reversal' && !detail.reversedByEntryId && <button className="danger-button" onClick={() => beginReverse(detail)}>Reverse transaction</button>}>{detail && <div className="page-stack"><h2>{detail.customerName}</h2>{badge(detail)}<DetailSection title="Amount and effect"><p>{exactRupees(detail.amountMinor)} · effect {exactRupees(detail.signedEffectMinor)}</p><p>{context.branchName} · {branchTime(detail.occurredAt, context.timezone, true)}</p></DetailSection><DetailSection title="Description"><p>{detail.description ?? 'No description'}</p><p>{detail.dueDate ? `Due ${detail.dueDate}` : 'No due date'}</p></DetailSection><p>{detail.reversesEntryId ? 'Exact inverse of a prior transaction.' : 'Original journal fact.'} {detail.reversedByEntryId ? 'Reversed by another retained entry.' : ''}</p></div>}</AdvancedModal>
    <OperationForm open={Boolean(reversal)} title="Reverse transaction" valid={manage && reversalReason.trim().length >= 3} busy={reverse.isPending} dirty={Boolean(reversalReason)} error={reverse.error} confirmLabel="Confirm reversal" onClose={() => setReversal(null)} onConfirm={() => { if (!reverse.isPending && reversalReason.trim().length >= 3) reverse.mutate(); }} review={reversal && <DetailSection title="Exact inverse"><p>{reversal.customerName} · {labels[reversal.entryType]} · {exactRupees(reversal.amountMinor)}</p><p>New balance effect {exactRupees((-BigInt(reversal.signedEffectMinor)).toString())} · {context.branchName}</p><p>{reversalReason}</p><p>The original remains visible. One full reversal is allowed; no deletion.</p></DetailSection>}>
      {reversal && <p>Original: {reversal.customerName} · {labels[reversal.entryType]} · {exactRupees(reversal.amountMinor)} · {branchTime(reversal.occurredAt, context.timezone, true)}. Appends the exact inverse; cannot reverse an already reversed entry.</p>}<Input label="Reversal reason" required minLength={3} maxLength={1000} value={reversalReason} onChange={e => setReason(e.target.value)} />
    </OperationForm>
  </AppPage>;
}
export default LedgerPage;
