import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import { client } from '../../api/client';
import { getErrorMessage } from '../../api/errors';
import { useAppStore } from '../../store/useAppStore';
import { queueKeys, type Paginated } from '../../hooks/useQueue';
import { useOperationalContext, useOperationalScope } from '../../hooks/useOperationalContext';
import { useDynamicForm } from '../../hooks/useDynamicForm';
import { branchTime, nominalEnd, shiftBusinessDate } from '../../utils/operations';
import { ReceptionFields } from '../../components/forms/ReceptionSelection';
import { useReceptionSelection } from '../../hooks/useReceptionSelection';
import { DynamicForm } from '../../components/forms/DynamicForm';
import { EntityFields } from '../../components/forms/EntityFields';
import { AdvancedTable, type Column } from '../../components/ui/AdvancedTable';
import { AdvancedModal } from '../../components/ui/AdvancedModal';
import { OperationForm } from '../../components/ui/OperationForm';
import { Input } from '../../components/ui/Input';
import { EmptyState } from '../../components/ui/EmptyState';
import { AppPage, PageHeader, DetailSection, StatusBadge, Skeleton, ErrorState } from '../../components/ui/WorkspacePrimitives';
interface Appointment { id: string; customerId: string; serviceId: string; startsAt: string; endsAt: string; status: 'scheduled' | 'confirmed' | 'checked_in' | 'completed' | 'cancelled' | 'no_show'; version: number; notes?: string | null; customer: { name: string; phone: string | null }; service: { name: string }; provider: { name: string | null } | null }
const labels = { scheduled: 'Scheduled', confirmed: 'Confirmed', checked_in: 'Checked in', completed: 'Completed', cancelled: 'Cancelled', no_show: 'No-show' };
const badge = (a: Appointment) => <StatusBadge tone={a.status === 'checked_in' ? 'info' : a.status === 'completed' ? 'success' : a.status === 'cancelled' || a.status === 'no_show' ? 'neutral' : 'warning'}>{labels[a.status]}</StatusBadge>;
export function AppointmentsPage() {
  const permissions = useAppStore(s => s.user?.permissions ?? []), manage = permissions.includes('queue.manage');
  const scope = useOperationalScope(), context = useOperationalContext(), selection = useReceptionSelection(), cache = useQueryClient();
  const [chosenDate, setDate] = useState(''), date = chosenDate || context.businessDate || '';
  const [page, setPage] = useState(1), [open, setOpen] = useState(false), [detailId, setDetailId] = useState<string | null>(null), [edit, setEdit] = useState(false);
  const [localTime, setTime] = useState('09:00'), [providerId, setProvider] = useState(''), [notes, setNotes] = useState(''), [key, setKey] = useState(() => crypto.randomUUID());
  const [editVersion, setEditVersion] = useState(0);
  const [checking, setChecking] = useState<Appointment | null>(null);
  const fields = useDynamicForm('appointment', null, open), editFields = useDynamicForm('appointment', detailId, Boolean(detailId));
  const appointments = useQuery({ queryKey: ['operational-appointments', ...scope, date, page], enabled: Boolean(date && context.timezone), queryFn: async ({ signal }) => (await client.get<Paginated<Appointment>>('/appointments', { signal, params: { date, page, limit: 20 } })).data });
  const detail = useQuery({ queryKey: ['appointment-detail', ...scope, detailId], enabled: Boolean(detailId), queryFn: async ({ signal }) => (await client.get<{ data: Appointment }>(`/appointments/${detailId}`, { signal })).data.data });
  const providers = useQuery({ queryKey: ['service-providers', ...scope, selection.serviceId], enabled: Boolean(open && selection.serviceId && permissions.includes('services.read')), queryFn: async ({ signal }) => (await client.get<{ data: { membershipId: string; name: string }[] }>(`/services/${selection.serviceId}/providers`, { signal })).data.data });
  const refresh = async () => { await Promise.all(['operational-appointments', 'appointment-detail', 'form-values', 'dashboardStats', queueKeys.root[0]].map(key => cache.invalidateQueries({ queryKey: [key] }))); };
  const create = useMutation({ mutationFn: () => client.post('/appointments', { customerId: selection.customerId, serviceId: selection.serviceId, providerMembershipId: providerId || null, localStart: `${date}T${localTime}:00`, notes: notes.trim() || null, customFields: fields.patch, idempotencyKey: key }), onSuccess: async () => { setOpen(false); toast.success('Appointment created'); await refresh(); } });
  const checkIn = useMutation({ mutationFn: (id: string) => client.post(`/appointments/${id}/check-in`, { idempotencyKey: `check-in:${id}` }), onSuccess: async response => { setChecking(null); toast.success(`Checked in · Queue token #${response.data.data.tokenNumber}`); await refresh(); } });
  const saveFields = useMutation({ mutationFn: () => client.patch(`/forms/appointment/values/${detailId}`, { customFields: editFields.patch, expectedVersion: editVersion }), onSuccess: async () => { setEdit(false); editFields.reset(); toast.success('Appointment fields saved'); await refresh(); } });
  const begin = () => { selection.reset(); fields.reset(); create.reset(); setKey(crypto.randomUUID()); setTime('09:00'); setProvider(''); setNotes(''); setOpen(true); };
  const timeRange = (a: Appointment) => `${branchTime(a.startsAt, context.timezone)}–${branchTime(a.endsAt, context.timezone)}`;
  const actions = (a: Appointment) => <div className="record-actions"><button className="quiet-button" onClick={() => { setDetailId(a.id); editFields.reset(); saveFields.reset(); }}>Details</button>{manage && ['scheduled', 'confirmed'].includes(a.status) && <button className="action-link" disabled={checkIn.isPending} onClick={() => { checkIn.reset(); setChecking(a); setDetailId(null); }}>Check in</button>}</div>;
  const columns: Column<Appointment>[] = [{ header: 'Branch time', accessor: 'startsAt', cell: ({ row }) => <strong>{timeRange(row)}</strong> }, { header: 'Customer', accessor: 'customer', cell: ({ row }) => row.customer.name }, { header: 'Service', accessor: 'service', cell: ({ row }) => row.service.name }, { header: 'Provider', accessor: 'provider', cell: ({ row }) => row.provider?.name ?? 'Unassigned' }, { header: 'Status', accessor: 'status', cell: ({ row }) => badge(row) }, { header: 'Actions', accessor: 'actions', cell: ({ row }) => actions(row) }];
  const valid = manage && selection.ready && Boolean(date && localTime && context.timezone) && fields.ready && fields.valid && !fields.error && (!providerId || Boolean(providers.data?.some(p => p.membershipId === providerId))) && !providers.isError;
  return <AppPage className="operations-workspace"><PageHeader title="Appointments" eyebrow="Daily operations · Schedule" description={`${context.branchName} · ${context.timezone ?? 'Loading branch timezone…'}`} actions={manage && <button className="action-link" disabled={!date || !context.timezone} onClick={begin}>New appointment</button>} />
    {context.isError ? <ErrorState title="Branch date unavailable" message="No device-timezone fallback is used. Reload the authorized business date." retry={() => void context.refetch()} /> : !context.businessDate ? <Skeleton label="Loading branch business date…" /> : <section className="panel operations-toolbar"><div className="record-actions"><button className="quiet-button" aria-label="Previous day" onClick={() => { setDate(shiftBusinessDate(date, -1)); setPage(1); }}>Previous day</button><button className="quiet-button" onClick={() => { setDate(''); setPage(1); void context.refetch(); }}>Today</button><button className="quiet-button" aria-label="Next day" onClick={() => { setDate(shiftBusinessDate(date, 1)); setPage(1); }}>Next day</button></div><Input label="Appointment date" type="date" value={date} onChange={e => { setDate(e.target.value); setPage(1); }} /><p className="muted">{appointments.isError ? 'Count unavailable' : appointments.data ? `${appointments.data.pagination.total} appointments` : 'Loading schedule…'} · selected branch/date</p></section>}
    {!manage && <p className="muted">Read-only schedule. Check-in and editing require Queue manage permission.</p>}
    {date && context.timezone && <AdvancedTable mode="server" title="Daily appointments" description={`${date} · ${context.timezone} · Scheduled and checked-in are distinct statuses`} columns={columns} data={appointments.data?.data ?? []} rowKey={a => a.id} loading={appointments.isPending} error={appointments.isError ? getErrorMessage(appointments.error, 'Appointments unavailable') : null} onRetry={() => void appointments.refetch()} retryLabel="Retry appointments" server={{ search: '', page, pageSize: 20, total: appointments.data?.pagination.total ?? 0, totalPages: appointments.data?.pagination.totalPages ?? 1, onPage: setPage }} emptyState={<EmptyState title="No appointments on this date" description="Choose another branch business date or book an appointment." action={manage ? 'Book first appointment' : undefined} onAction={begin} />} mobileCard={a => <article className="panel mobile-record-card"><div className="operations-record-heading"><strong className="appointment-time">{timeRange(a)}</strong>{badge(a)}</div><h2>{a.customer.name}</h2><p>{a.service.name}</p><p className="muted">{a.provider?.name ?? 'Unassigned provider'}</p>{actions(a)}</article>} />}
    <OperationForm open={open} title="Create appointment" valid={valid} busy={create.isPending} dirty={Boolean(selection.customerId || selection.serviceId || notes || Object.keys(fields.patch).length)} error={create.error} confirmLabel="Create appointment" onConfirm={() => { if (valid && !create.isPending) create.mutate(); }} onClose={() => setOpen(false)} review={<DetailSection title="Booking"><p>{selection.customer?.name} · {selection.service?.name}</p><p>{date} {localTime} · {context.timezone} · {context.branchName}</p><p>{selection.service?.durationMinutes} minutes · Nominal end {nominalEnd(date, localTime, selection.service?.durationMinutes)}</p><p>{providers.data?.find(p => p.membershipId === providerId)?.name ?? 'Unassigned provider'}</p><p>{notes || 'No notes'}</p>{fields.schema && <DynamicForm schema={fields.schema} values={fields.values} readOnly />}<p className="muted">Ending preview assumes no clock change. The server computes the authoritative end instant and rejects DST gaps/folds or provider overlaps.</p></DetailSection>}>
      <ReceptionFields selection={selection} />{fields.error ? <ErrorState title="Appointment form unavailable" message="Reload authorized fields." retry={fields.retry} /> : !fields.ready ? <Skeleton label="Loading appointment fields…" /> : fields.schema && <DynamicForm schema={fields.schema} values={fields.values} onChange={fields.change} builtins={{ localStart: <Input label="Local start time" type="time" value={localTime} onChange={e => setTime(e.target.value)} />, providerMembershipId: <label className="field">Provider (optional)<select aria-label="Provider (optional)" value={providerId} disabled={providers.isPending || providers.isError || !selection.serviceId} onChange={e => setProvider(e.target.value)}><option value="">Unassigned</option>{providers.data?.map(p => <option key={p.membershipId} value={p.membershipId}>{p.name}</option>)}</select></label>, notes: <Input label="Appointment notes (optional)" maxLength={2000} value={notes} onChange={e => setNotes(e.target.value)} /> }} />}
      {providers.isError && <ErrorState title="Provider choices unavailable" message="Retry before booking." retry={() => void providers.refetch()} />}
      <p className="muted">{context.timezone} · Duration {selection.service?.durationMinutes ?? '—'} min · Nominal end {nominalEnd(date, localTime, selection.service?.durationMinutes)}. Assignment does not prove availability; the server checks overlap.</p>
    </OperationForm>
    <AdvancedModal isOpen={Boolean(detailId) && !edit} title="Appointment details" onClose={() => setDetailId(null)} presentation="drawer" size="xl" actions={<><button className="quiet-button" onClick={() => setDetailId(null)}>Back to schedule</button>{manage && detail.data && <button className="action-link" onClick={() => { saveFields.reset(); setEditVersion(detail.data!.version); setEdit(true); }}>Edit appointment fields</button>}</>}>
      {detail.isPending ? <Skeleton label="Loading appointment details…" /> : detail.isError ? <ErrorState title="Appointment unavailable" message="Reload this authorized record." retry={() => void detail.refetch()} /> : detail.data && <div className="page-stack"><h2>{detail.data.customer.name}</h2>{badge(detail.data)}<DetailSection title="Schedule"><p>{branchTime(detail.data.startsAt, context.timezone, true)}–{branchTime(detail.data.endsAt, context.timezone)} · {context.timezone}</p><p>{detail.data.service.name} · {detail.data.provider?.name ?? 'Unassigned provider'}</p></DetailSection><DetailSection title="Notes"><p>{detail.data.notes ?? 'No notes'}</p></DetailSection><DetailSection title="Additional information"><EntityFields entity="appointment" id={detail.data.id} /></DetailSection>{actions(detail.data)}<p className="muted">Version {detail.data.version}. Existing status/history is preserved; this form does not edit scheduling.</p></div>}
    </AdvancedModal>
    <OperationForm open={edit} title="Edit appointment fields" retryAdvice="Reviewed fields and the original record version are retained. Reopen the refreshed record after a version conflict." valid={manage && Boolean(detail.data) && editFields.ready && editFields.valid && !editFields.error} busy={saveFields.isPending} dirty={Boolean(Object.keys(editFields.patch).length)} error={saveFields.error} confirmLabel="Save appointment fields" onConfirm={() => { if (!saveFields.isPending) saveFields.mutate(); }} onClose={() => setEdit(false)} review={<><p>Save additional information for {detail.data?.customer.name} using record version {editVersion}. Schedule and status remain unchanged.</p>{editFields.schema && <DynamicForm schema={editFields.schema} values={editFields.values} readOnly />}</>}>
      {editFields.error ? <ErrorState title="Fields unavailable" message="Retry before editing." retry={editFields.retry} /> : editFields.schema && <DynamicForm schema={editFields.schema} values={editFields.values} onChange={editFields.change} />}
    </OperationForm>
    <AdvancedModal isOpen={Boolean(checking)} title="Check in appointment" onClose={() => { if (!checkIn.isPending) setChecking(null); }} closeOnEscape={!checkIn.isPending} closeOnBackdropClick={!checkIn.isPending} actions={<><button className="quiet-button" disabled={checkIn.isPending} onClick={() => setChecking(null)}>Cancel</button><button className="action-link" disabled={checkIn.isPending} onClick={() => { if (checking && !checkIn.isPending) checkIn.mutate(checking.id); }}>{checkIn.isPending ? 'Checking in…' : 'Confirm check-in'}</button></>}>{checking && <p>{checking.customer.name} · {checking.service.name} · {timeRange(checking)}. Creates one canonical Queue token and marks this appointment checked in atomically. Retries reuse the same check-in key.</p>}{checkIn.error && <p role="alert" className="error-text">{getErrorMessage(checkIn.error, 'Check-in failed safely')}</p>}</AdvancedModal>
  </AppPage>;
}
export default AppointmentsPage;
