import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import { client } from '../../api/client';
import { getErrorMessage } from '../../api/errors';
import { useAppStore } from '../../store/useAppStore';
import { type Paginated, useBranchServices } from '../../hooks/useQueue';
import { AdvancedModal } from '../../components/ui/AdvancedModal';
import { EmptyState } from '../../components/ui/EmptyState';
import { Input } from '../../components/ui/Input';

interface Service { id: string; name: string; description: string | null; durationMinutes: number; active: boolean }
interface Staff { id: string; membershipId: string; name: string; branchIds: string[] }
interface Provider { membershipId: string; name: string }
const blank = { name: '', description: '', durationMinutes: '30', active: true };
export default function ServicesPage() {
  const { activeTenantId, activeBranchId, user } = useAppStore();
  const manage = Boolean(user?.permissions?.includes('queue.manage'));
  const staffRead = Boolean(user?.permissions?.includes('staff.read'));
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const [editing, setEditing] = useState<Service | null | undefined>();
  const [form, setForm] = useState(blank);
  const [providerService, setProviderService] = useState<Service | null>(null);
  const cache = useQueryClient();
  const services = useQuery({ queryKey: ['operational-services-admin', activeTenantId, search, page], queryFn: async () => (await client.get<Paginated<Service>>('/services', { params: { scope: 'organization', search: search || undefined, page, limit: 20 } })).data });
  const available = useBranchServices();
  const providers = useQuery({ queryKey: ['service-providers', activeTenantId, activeBranchId, providerService?.id], enabled: Boolean(providerService), queryFn: async () => (await client.get<{ data: Provider[] }>(`/services/${providerService!.id}/providers`)).data.data });
  const staff = useQuery({ queryKey: ['service-assignment-staff', activeTenantId], enabled: Boolean(providerService && staffRead), queryFn: async () => (await client.get<{ data: Staff[] }>('/staff')).data.data });
  const save = useMutation({ mutationFn: async () => {
    const body = { name: form.name.trim(), description: form.description.trim() || null, durationMinutes: Number(form.durationMinutes), ...(editing ? { active: form.active } : {}) };
    return editing ? client.patch(`/services/${editing.id}`, body) : client.post('/services', body);
  }, onSuccess: async () => { await cache.invalidateQueries({ queryKey: ['operational-services-admin'] }); await cache.invalidateQueries({ queryKey: ['operational-services'] }); setEditing(undefined); toast.success('Service saved'); } });
  const assign = useMutation({ mutationFn: async (input: { membershipId: string; active: boolean }) => client.put(`/services/${providerService!.id}/providers`, input), onSuccess: () => cache.invalidateQueries({ queryKey: ['service-providers'] }) });
  const open = (service: Service | null) => { save.reset(); setEditing(service); setForm(service ? { name: service.name, description: service.description ?? '', durationMinutes: String(service.durationMinutes), active: service.active } : blank); };
  return <div className="page-stack"><header className="page-heading"><div><h1>Services</h1><p>One catalogue for Queue and Appointments. New services are available in the selected branch.</p></div>{manage && <button className="action-link" disabled={!activeBranchId} onClick={() => open(null)}>Create service</button>}</header>
    <Input label="Search services" type="search" maxLength={200} value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} />
    {services.isLoading ? <p role="status">Loading services…</p> : services.isError ? <section className="panel" role="alert"><p>{getErrorMessage(services.error, 'Services could not be loaded.')}</p><button className="quiet-button mt-3" onClick={() => void services.refetch()}>Retry services</button></section> : services.data?.data.length === 0 ? <EmptyState title={search ? 'No matching services' : 'No services yet'} description={search ? 'Try a different service name.' : 'Create your first service before booking appointments or issuing tokens.'} action={search ? 'Clear search' : manage ? 'Create your first service' : undefined} onAction={search ? () => setSearch('') : () => open(null)} /> : <div className="catalogue-grid">{services.data?.data.map((service) => <article className="panel record-card" key={service.id}><h2>{service.name}</h2><p className="muted">{service.durationMinutes} minutes · {service.active ? 'Active' : 'Inactive'}</p><p className="mt-2">{service.description ?? 'No description added'}</p><p className="muted mt-2">{available.data?.data.some((item) => item.id === service.id) ? 'Available in selected branch' : service.active ? 'Branch availability not confirmed' : 'Unavailable while inactive'}</p><div className="record-actions">{manage && <button className="quiet-button" onClick={() => open(service)}>Edit {service.name}</button>}<button className="quiet-button" onClick={() => { assign.reset(); setProviderService(service); }}>Providers for {service.name}</button></div></article>)}</div>}
    {services.data && <div className="pagination"><button className="quiet-button" disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} of {Math.max(1, services.data.pagination.totalPages)}</span><button className="quiet-button" disabled={page >= services.data.pagination.totalPages} onClick={() => setPage(page + 1)}>Next</button></div>}
    <AdvancedModal isOpen={editing !== undefined} onClose={() => setEditing(undefined)} title={editing ? 'Edit service' : 'Create service'}><form className="page-stack" onSubmit={(event) => { event.preventDefault(); if (manage) save.mutate(); }}><Input label="Service name" required maxLength={200} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><Input label="Duration (minutes)" type="number" min={1} max={1440} step={1} required value={form.durationMinutes} onChange={(event) => setForm({ ...form, durationMinutes: event.target.value })} /><div className="field"><label htmlFor="service-description">Description (optional)</label><textarea id="service-description" rows={3} maxLength={2000} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></div>{editing && <label className="flex items-center gap-2"><input type="checkbox" checked={form.active} onChange={(event) => setForm({ ...form, active: event.target.checked })} />Active service</label>}<p className="muted">Availability follows the existing branch assignment. Turning a service inactive hides it from new bookings.</p>{save.isError && <p className="error-text" role="alert">{getErrorMessage(save.error, 'Service could not be saved.')}</p>}<button className="action-link" type="submit" disabled={save.isPending || !form.name.trim()}>{save.isPending ? 'Saving…' : 'Save service'}</button></form></AdvancedModal>
    <AdvancedModal isOpen={Boolean(providerService)} onClose={() => setProviderService(null)} title={`Providers · ${providerService?.name ?? ''}`}><div className="page-stack">{providers.isLoading ? <p>Loading providers…</p> : providers.isError ? <><p role="alert">Providers could not be loaded.</p><button className="quiet-button" onClick={() => void providers.refetch()}>Retry providers</button></> : <><h2 className="font-semibold">Assigned in selected branch</h2>{providers.data?.length ? providers.data.map((provider) => <div key={provider.membershipId} className="flex items-center justify-between gap-2"><span>{provider.name}</span>{manage && <button className="quiet-button" disabled={assign.isPending} onClick={() => assign.mutate({ membershipId: provider.membershipId, active: false })}>Unassign {provider.name}</button>}</div>) : <p className="muted">No providers assigned. Bookings may remain unassigned.</p>}</>}
      {manage && staffRead && <><h2 className="font-semibold">Available staff</h2>{staff.isLoading ? <p>Loading staff…</p> : staff.isError ? <><p role="alert">Staff could not be loaded.</p><button className="quiet-button" onClick={() => void staff.refetch()}>Retry staff</button></> : staff.data?.filter((person) => person.branchIds.includes(activeBranchId ?? '') && !providers.data?.some((provider) => provider.membershipId === person.membershipId)).map((person) => <button key={person.membershipId} className="quiet-button" disabled={assign.isPending || providers.isError} onClick={() => assign.mutate({ membershipId: person.membershipId, active: true })}>Assign {person.name}</button>)}</>}{assign.isError && <p role="alert" className="error-text">{getErrorMessage(assign.error, 'Assignment could not be saved.')}</p>}</div></AdvancedModal>
  </div>;
}
