import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import { client } from '../../api/client';
import { getErrorMessage } from '../../api/errors';
import { useAppStore } from '../../store/useAppStore';
import { useOperationalScope } from '../../hooks/useOperationalContext';
import { branchTime } from '../../utils/operations';
import { AppPage, PageHeader, StatusBadge, SearchField, DetailSection, Skeleton, ErrorState } from '../../components/ui/WorkspacePrimitives';
import { Input } from '../../components/ui/Input';
import { AdvancedModal } from '../../components/ui/AdvancedModal';
import { OperationForm } from '../../components/ui/OperationForm';
import { EmptyState } from '../../components/ui/EmptyState';
type Status = 'present' | 'absent' | 'half_day';
interface Record { id: string; status: Status; version: number; checkInLocal: string | null; checkOutLocal: string | null; source: string }
interface Entry { membershipId: string; displayName: string; role: string; membershipStatus: string; attendance: Record | null; correctionCount: number }
interface Roster { attendanceDate: string; branch: { id: string; name: string; timezone: string }; roster: Entry[]; summary: { total: number; present: number; absent: number; half_day: number; unmarked: number } }
interface Pending { entry: Entry; status: Status; checkIn: string; checkOut: string; reason: string; date: string; key: string }
interface Change { id: string; priorStatus: Status; newStatus: Status; reason: string; resultingVersion: number; occurredAt: string; priorCheckInLocal: string | null; newCheckInLocal: string | null; priorCheckOutLocal: string | null; newCheckOutLocal: string | null }
const labels = { present: 'Present', absent: 'Absent', half_day: 'Half-day', unmarked: 'Unmarked' };
const badge = (status: Status | 'unmarked') => <StatusBadge tone={status === 'present' ? 'success' : status === 'absent' ? 'danger' : status === 'half_day' ? 'warning' : 'neutral'}>{labels[status]}</StatusBadge>;
const local = (value: string | null | undefined) => value?.replace('T', ' ') ?? 'Not recorded';
export function AttendancePage() {
  const permissions = useAppStore(s => s.user?.permissions ?? []), manage = permissions.includes('attendance.manage'), scope = useOperationalScope(), cache = useQueryClient();
  const [selectedDate, setDate] = useState(''), [search, setSearch] = useState(''), [status, setStatus] = useState(''), [pending, setPending] = useState<Pending | null>(null), [historyEntry, setHistory] = useState<Entry | null>(null);
  const roster = useQuery({ queryKey: ['attendance-roster', ...scope, selectedDate || 'branch-today'], queryFn: async ({ signal }) => (await client.get<{ data: Roster }>('/attendance', { signal, params: selectedDate ? { date: selectedDate } : undefined })).data.data });
  const history = useQuery({ queryKey: ['attendance-history', ...scope, historyEntry?.attendance?.id], enabled: Boolean(historyEntry?.attendance), queryFn: async ({ signal }) => (await client.get<{ data: { branch: Roster['branch']; changes: Change[] } }>(`/attendance/${historyEntry!.attendance!.id}/history`, { signal })).data.data });
  const mark = useMutation({ mutationFn: (p: Pending) => client.post('/attendance', { membershipId: p.entry.membershipId, attendanceDate: p.date, status: p.status, checkInAt: p.status === 'absent' ? null : p.checkIn || null, checkOutAt: p.status === 'absent' ? null : p.checkOut || null, ...(p.entry.attendance ? { expectedVersion: p.entry.attendance.version, correctionReason: p.reason.trim() } : { idempotencyKey: p.key }) }), onSuccess: async () => { setPending(null); toast.success('Attendance saved'); await Promise.all(['attendance-roster', 'attendance-history', 'dashboardStats'].map(key => cache.invalidateQueries({ queryKey: [key] }))); }, onError: () => { void cache.invalidateQueries({ queryKey: ['attendance-roster'] }); } });
  const begin = (entry: Entry) => { mark.reset(); setPending({ entry, status: entry.attendance?.status ?? 'present', checkIn: entry.attendance?.checkInLocal?.slice(0, 16) ?? '', checkOut: entry.attendance?.checkOutLocal?.slice(0, 16) ?? '', reason: '', date: roster.data!.attendanceDate, key: crypto.randomUUID() }); };
  const visible = roster.data?.roster.filter(entry => entry.displayName.toLowerCase().includes(search.toLowerCase()) && (!status || (entry.attendance?.status ?? 'unmarked') === status)) ?? [];
  const valid = Boolean(manage && pending && (!pending.entry.attendance || pending.reason.trim().length >= 3) && (pending.status === 'absent' || !pending.checkOut || Boolean(pending.checkIn && pending.checkOut > pending.checkIn)));
  const set = (patch: Partial<Pending>) => setPending(p => p ? { ...p, ...patch } : null);
  return <AppPage className="operations-workspace"><PageHeader title="Daily Attendance" eyebrow="Daily operations · People" description={roster.data ? `${roster.data.branch.name} · ${roster.data.branch.timezone}` : 'Selected branch roster'} actions={<button className="quiet-button" onClick={() => void roster.refetch()}>Refresh attendance</button>} />
    <div className="operations-toolbar"><Input label="Business date" type="date" value={selectedDate || roster.data?.attendanceDate || ''} onChange={e => setDate(e.target.value)} /><button className="quiet-button" onClick={() => { setDate(''); void roster.refetch(); }}>Today in branch</button></div>
    {roster.data && !roster.isError && <div className="operations-summary">{(['total', 'present', 'absent', 'half_day', 'unmarked'] as const).map(key => <section className="panel" key={key}><h2>{key === 'total' ? 'Roster' : labels[key]}</h2><p className="stat-value">{roster.data.summary[key]}</p></section>)}</div>}
    <p className="muted">Unmarked means no attendance recorded, not Absent. Shifts and approved leave do not create attendance.</p>{!manage && <p className="muted">Read-only roster. Marking and corrections require Attendance manage permission.</p>}
    <section className="panel operations-toolbar"><SearchField label="Filter loaded daily roster" placeholder="Find staff in this complete branch/day roster" maxLength={200} value={search} onChange={e => setSearch(e.target.value)} /><label className="field">Attendance state<select aria-label="Attendance state" value={status} onChange={e => setStatus(e.target.value)}><option value="">All roster states</option>{Object.entries(labels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>{(search || status) && <button className="quiet-button" onClick={() => { setSearch(''); setStatus(''); }}>Reset roster filters</button>}</section>
    {roster.isPending ? <Skeleton label="Loading branch roster…" rows={5} /> : roster.isError ? <ErrorState title="Attendance unavailable" message={getErrorMessage(roster.error, 'Roster could not be loaded')} retry={() => void roster.refetch()} retryLabel="Retry attendance" /> : visible.length === 0 ? <EmptyState title={search || status ? 'No matching staff' : 'No staff assigned to this branch'} description={search || status ? 'Change the local roster filters.' : 'Ask an organization administrator to review staff branch assignments.'} /> : <div className="operations-roster">{visible.map(entry => <article className="panel record-card" key={entry.membershipId}><div className="operations-record-heading"><h2>{entry.displayName}</h2>{badge(entry.attendance?.status ?? 'unmarked')}</div><p className="muted">{entry.role} · {entry.membershipStatus}</p><dl className="operations-facts"><dt>Check-in</dt><dd>{local(entry.attendance?.checkInLocal)}</dd><dt>Check-out</dt><dd>{local(entry.attendance?.checkOutLocal)}</dd></dl><div className="record-actions">{manage && entry.membershipStatus === 'active' && <button className="action-link" onClick={() => begin(entry)}>{entry.attendance ? 'Correct attendance' : 'Mark attendance'}</button>}{entry.attendance && <button className="quiet-button" onClick={() => setHistory(entry)}>History ({entry.correctionCount})</button>}</div></article>)}</div>}
    <OperationForm open={Boolean(pending)} title={pending?.entry.attendance ? 'Correct attendance' : 'Mark attendance'} retryAdvice={pending?.entry.attendance ? 'Reviewed values and the original record version are retained. Reopen the refreshed attendance record after a version conflict.' : undefined} valid={valid} busy={mark.isPending} dirty error={mark.error} confirmLabel="Save attendance" onClose={() => setPending(null)} onConfirm={() => { if (pending && valid && !mark.isPending) mark.mutate(pending); }} review={pending && <DetailSection title={pending.entry.displayName}><p>{pending.date} · {roster.data?.branch.name}</p><p>{labels[pending.entry.attendance?.status ?? 'unmarked']} → {labels[pending.status]}</p><p>Check-in: {pending.status === 'absent' ? 'Not recorded' : local(pending.checkIn || null)}</p><p>Check-out: {pending.status === 'absent' ? 'Not recorded' : local(pending.checkOut || null)}</p><p>{pending.reason || 'Initial attendance mark'}</p><p className="muted">{pending.entry.attendance ? `Reasoned correction using version ${pending.entry.attendance.version}; previous facts stay in history.` : 'Creates one attendance record, with an idempotent retry key.'}</p></DetailSection>}>
      {pending && <><h2>{pending.entry.displayName}</h2>{pending.entry.attendance && <DetailSection title="Existing record"><p>{labels[pending.entry.attendance.status]} · {local(pending.entry.attendance.checkInLocal)} → {local(pending.entry.attendance.checkOutLocal)}</p></DetailSection>}<label className="field">Proposed attendance status<select aria-label="Proposed attendance status" value={pending.status} onChange={e => set({ status: e.target.value as Status })}>{(['present', 'absent', 'half_day'] as const).map(key => <option key={key} value={key}>{labels[key]}</option>)}</select></label>{pending.status !== 'absent' && <><Input label="Check-in (branch local, optional)" type="datetime-local" value={pending.checkIn} onChange={e => set({ checkIn: e.target.value })} /><Input label="Check-out (branch local, optional)" type="datetime-local" value={pending.checkOut} onChange={e => set({ checkOut: e.target.value })} /></>}{pending.entry.attendance && <Input label="Correction reason" required minLength={3} maxLength={500} value={pending.reason} onChange={e => set({ reason: e.target.value })} />}<p className="muted">All times use {roster.data?.branch.timezone}, not your device timezone. Times must belong to {pending.date}; check-out must follow check-in. DST validation is server-side.</p></>}
    </OperationForm>
    <AdvancedModal isOpen={Boolean(historyEntry)} title="Attendance history" presentation="drawer" size="xl" onClose={() => setHistory(null)}><div className="page-stack"><h2>{historyEntry?.displayName}</h2>{history.isPending ? <Skeleton label="Loading correction history…" /> : history.isError ? <ErrorState title="History unavailable" message={getErrorMessage(history.error, 'History could not be loaded')} retry={() => void history.refetch()} /> : history.data?.changes.length === 0 ? <p>No corrections. The initial mark remains the current fact.</p> : history.data?.changes.map(change => <DetailSection key={change.id} title={`Correction · version ${change.resultingVersion}`}><p>{labels[change.priorStatus]} → {labels[change.newStatus]}</p><p>{change.reason}</p><p>Check-in: {local(change.priorCheckInLocal)} → {local(change.newCheckInLocal)}</p><p>Check-out: {local(change.priorCheckOutLocal)} → {local(change.newCheckOutLocal)}</p><p className="muted">{branchTime(change.occurredAt, history.data.branch.timezone, true)}</p></DetailSection>)}</div></AdvancedModal>
  </AppPage>;
}
export default AttendancePage;
