import {test,expect,type Page,type APIRequestContext} from '@playwright/test';
import { randomUUID } from 'node:crypto';
const api='http://127.0.0.1:5011';
interface Fixture {phone:string;password:string;organizationId:string;branchId:string}
let fixture:Fixture,errors:string[];
test.beforeEach(async({page,request})=>{fixture=await(await request.post(api+'/__test/fixture',{data:{modules:['queue','inventory','attendance','ledger']}})).json();errors=[];page.on('pageerror',e=>errors.push(e.name));});
test.afterEach(()=>expect(errors).toEqual([]));
async function login(page:Page,f=fixture){await page.goto('/login');await page.getByLabel('Phone or email').fill(f.phone);await page.getByLabel('Password',{exact:true}).fill(f.password);await page.getByRole('button',{name:'Sign In to Ekavio'}).click();await expect(page).toHaveURL(/dashboard/);}
async function headers(request:APIRequestContext,f=fixture){const r=await request.post(api+'/api/auth/login',{data:{phone:f.phone,password:f.password}});expect(r.status()).toBe(200);const data=await r.json();return {authorization:'Bearer '+data.accessToken,'x-tenant-id':f.organizationId,'x-branch-id':f.branchId};}
async function seed(request:APIRequestContext){const h=await headers(request);const post=async(path:string,data:unknown)=>{const r=await request.post(api+'/api/'+path,{headers:h,data});expect(r.ok(),path+' status '+r.status()).toBeTruthy();return (await r.json()).data;};
 const field=await post('forms/customer/definitions',{key:'report_note',label:'QA report note',help:'Disposable',fieldType:'text',status:'active',required:false,searchable:true,filterable:true,reportable:true,defaultValue:null,options:[]});
 const customer=await post('customers',{name:'=QA formula',customFields:{report_note:'Reportable note'}}),service=await post('services',{name:'QA report service',durationMinutes:30});
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 await post('appointments',{customerId:customer.id,serviceId:service.id,localStart:today+'T10:30',idempotencyKey:randomUUID()});
 await post('queue',{customerId:customer.id,serviceId:service.id,idempotencyKey:randomUUID()});
 const members=await(await request.get(api+'/api/members',{headers:h})).json();const member=members.data[0];
 await post('attendance',{membershipId:member.membershipId,attendanceDate:today,status:'present',idempotencyKey:randomUUID()});
 await post('customer-dues/entries',{customerId:customer.id,entryType:'charge',amount:'100.01',idempotencyKey:randomUUID()});
 await post('inventory',{name:'QA stock item',unitCode:'piece',openingQuantity:'1.250',reorderThreshold:'2.000',idempotencyKey:randomUUID()});
 return {h,member,field,today,customer};
}
test('owner Dashboard, permitted widgets, hide/reorder and durable preferences',async({page,request})=>{await seed(request);await login(page);await expect(page.getByRole('heading',{name:'Active customers',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Outstanding Customer Dues',exact:true})).toBeVisible();await page.getByRole('button',{name:'Customize dashboard'}).click();await page.getByRole('checkbox',{name:'Available services',exact:true}).uncheck();await expect(page.getByRole('heading',{name:'Available services',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Move Low-stock items up'}).click();await expect(page.getByRole('button',{name:'Reset layout'})).toBeEnabled();await page.reload();await expect(page.getByRole('heading',{name:'Available services',exact:true})).toHaveCount(0);});
test('curated reports, custom column/filter, CSV and all canonical domain records',async({page,request})=>{await seed(request);await login(page);await page.goto('/reports');await expect(page.getByRole('heading',{name:'Reports',exact:true})).toBeVisible();await expect(page.getByRole('cell',{name:'=QA formula',exact:true})).toBeVisible();await page.getByText('Choose columns',{exact:true}).click();await page.getByRole('checkbox',{name:'QA report note',exact:true}).check();await expect(page.getByRole('cell',{name:'Reportable note',exact:true})).toBeVisible();await page.getByLabel('Customer field filter').selectOption('report_note');await page.getByLabel('Field value',{exact:true}).fill('Reportable note');await page.getByRole('button',{name:'Apply customer field filter'}).click();await expect(page.getByRole('cell',{name:'=QA formula',exact:true})).toBeVisible();const response=page.waitForResponse(r=>r.url().includes('/reports/customers/export'));const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export CSV'}).click();const r=await response;expect(r.status()).toBe(200);expect(await r.text()).toContain('"\'=QA formula"');expect((await download).suggestedFilename()).toBe('ekavio-customers.csv');
 for(const [key,text] of [['services','QA report service'],['appointments','QA report service'],['queue','QA report service'],['attendance','QA owner'],['dues-balances','₹100.01'],['dues-journal','charge'],['inventory','QA stock item'],['stock-movements','opening'],['staff','QA owner']]){await page.getByRole('combobox',{name:'Report',exact:true}).selectOption(key!);await expect(page.getByRole('cell',{name:text!,exact:true})).toBeVisible();}
});
test('restricted custom role Dashboard without reports.read and report/entitlement negatives',async({page,request})=>{const limited:Fixture=await(await request.post(api+'/__test/fixture',{data:{permissions:['customers.read','services.read']}})).json();await login(page,limited);await expect(page.getByRole('heading',{name:'Active customers',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Low-stock items',exact:true})).toHaveCount(0);await expect(page.getByRole('link',{name:'Reports',exact:true})).toHaveCount(0);await page.goto('/reports');await expect(page).toHaveURL(/dashboard/);const h=await headers(request,limited);expect((await request.get(api+'/api/reports/customers',{headers:h})).status()).toBe(403);
 const reportOnly:Fixture=await(await request.post(api+'/__test/fixture',{data:{permissions:['reports.read','inventory.read','queue.read']}})).json();const rh=await headers(request,reportOnly);for(const key of ['inventory','appointments','customers','inventory/export','customers/export'])expect((await request.get(api+'/api/reports/'+key,{headers:rh})).status()).toBe(403);expect((await request.get(api+'/api/reports/customers',{headers:{...rh,'x-tenant-id':fixture.organizationId}})).status()).toBe(403);expect((await request.get(api+'/api/reports/inventory',{headers:{...rh,'x-branch-id':fixture.branchId}})).status()).toBe(403);expect((await request.get(api+'/api/reports/customers/export',{headers:{...rh,'x-tenant-id':fixture.organizationId}})).status()).toBe(403);expect((await request.get(api+'/api/reports/inventory/export',{headers:{...rh,'x-branch-id':fixture.branchId}})).status()).toBe(403);
});
test('bell unread, own access event, read/all, preference and safe deep link',async({page,request})=>{const {h,member}=await seed(request);const update=await request.patch(api+'/api/members/'+member.membershipId,{headers:h,data:{role:member.role,customRoleId:member.customRoleId,status:'active',branchIds:[fixture.branchId],version:member.version}});expect(update.status()).toBe(200);await login(page);await page.getByRole('button',{name:'Notifications, 1 unread'}).click();await expect(page.getByText('Your workspace access changed',{exact:true})).toBeVisible();await page.getByRole('link',{name:'View all',exact:true}).click();await page.getByRole('button',{name:'Mark read',exact:true}).click();await expect(page.getByText(/0 unread · Updates/)).toBeVisible();await page.getByRole('button',{name:'Mark unread',exact:true}).click();await page.getByRole('button',{name:'Mark all read',exact:true}).click();await expect(page.getByText(/0 unread · Updates/)).toBeVisible();await page.getByRole('link',{name:'Review access'}).click();await expect(page).toHaveURL(/settings/);await page.goto('/settings?section=notifications');await page.getByRole('checkbox',{name:'Organization changes'}).uncheck();await expect(page.getByRole('checkbox',{name:'Organization changes'})).toBeEnabled();await page.reload();await expect(page.getByRole('checkbox',{name:'Organization changes'})).not.toBeChecked();});
for(const width of [390,768,1440])for(const theme of ['light','dark','system'])test(`reports notifications dashboard fit ${width}px ${theme}`,async({page,request})=>{
 const {h,customer}=await seed(request),longLabel='Long reportable note with a descriptive human label '.repeat(2).slice(0,100),longValue='QA '.repeat(300);
 expect((await request.post(api+'/api/forms/customer/definitions',{headers:h,data:{key:'long_report',label:longLabel,help:'Disposable long field',fieldType:'textarea',status:'active',required:false,searchable:false,filterable:false,reportable:true,defaultValue:null,options:[]}})).status()).toBe(200);
 expect((await request.patch(api+'/api/customers/'+customer.id,{headers:h,data:{customFields:{long_report:longValue}}})).status()).toBe(200);
 await page.setViewportSize({width,height:900});await login(page);await page.goto('/settings?section=appearance');await page.getByRole('radio',{name:new RegExp(theme,'i')}).click();
 for(const path of ['/dashboard','/reports','/notifications','/settings?section=notifications']){
  await page.goto(path);await expect(page.getByRole('heading',{name:path==='/dashboard'?/^Welcome,/:path==='/reports'?'Reports':path==='/notifications'?'Notifications':'Settings',exact:path!=='/dashboard'})).toBeVisible();
  if(path==='/dashboard')await expect(page.getByRole('heading',{name:'Active customers',exact:true})).toBeVisible();
  if(path==='/notifications')await expect(page.getByText("You're all caught up.",{exact:true})).toBeVisible();
  if(path.includes('section=notifications'))await expect(page.getByRole('checkbox',{name:'Organization changes'})).toBeVisible();
  if(path==='/reports'){
   await expect(page.getByText('Choose columns',{exact:true})).toBeVisible();await page.getByText('Choose columns',{exact:true}).click();await page.getByRole('checkbox',{name:longLabel.trim(),exact:true}).check();await expect(page.getByText(longValue.trim(),{exact:true}).filter({visible:true})).toBeVisible();
   if(width===390){await page.getByRole('button',{name:'Filters',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Report filters'});await expect(dialog).toBeVisible();await expect(page.getByLabel('Search names')).toHaveCount(1);await dialog.getByLabel('Search names').fill('QA nonexistent match');await expect(page.getByText('No records matched these filters.',{exact:true})).toBeVisible();await dialog.getByLabel('Search names').fill('=QA formula');await expect(page.getByText(longValue.trim(),{exact:true}).filter({visible:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await dialog.getByRole('button',{name:'Done',exact:true}).click();}else await expect(page.getByRole('button',{name:'Filters',exact:true})).toHaveCount(0);
  }
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 }
 if(width===1440&&theme==='light'){await page.goto('/reports');await expect(page.getByRole('heading',{name:'Reports',exact:true})).toBeVisible();await expect(page.getByRole('cell',{name:'=QA formula',exact:true})).toBeVisible();await page.screenshot({path:'test-results/analytics/safe-reports-preview.png'});}
});
